 `timescale 1 ns / 1 ps
// Generated by Cadence Encounter(R) RTL Compiler v11.20-s017_1

// Verification Directory fv/asy_fifo_input 

module asy_fifo_input(data_to_mosi, spi_cs, wdata, clk, rst, data_av,
     control_clk);
  input [7:0] wdata;
  input clk, rst, data_av, control_clk;
  output [7:0] data_to_mosi;
  output spi_cs;
  wire [7:0] wdata;
  wire clk, rst, data_av, control_clk;
  wire [7:0] data_to_mosi;
  wire spi_cs;
  wire [7:0] rdata;
  wire [7:0] \ex_mem[1] ;
  wire [7:0] \ex_mem[13] ;
  wire [7:0] \ex_mem[3] ;
  wire [7:0] \ex_mem[7] ;
  wire [7:0] \ex_mem[8] ;
  wire [7:0] \ex_mem[4] ;
  wire [7:0] \ex_mem[2] ;
  wire [7:0] \ex_mem[11] ;
  wire [7:0] \ex_mem[0] ;
  wire [7:0] \ex_mem[9] ;
  wire [7:0] \ex_mem[10] ;
  wire [7:0] \ex_mem[14] ;
  wire [7:0] \ex_mem[12] ;
  wire [7:0] \ex_mem[6] ;
  wire [7:0] \ex_mem[5] ;
  wire [3:0] r_pointer;
  wire [3:0] w_pointer;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66,
       UNCONNECTED67, UNCONNECTED68, UNCONNECTED69, UNCONNECTED70;
  wire UNCONNECTED71, UNCONNECTED72, UNCONNECTED73, UNCONNECTED74,
       UNCONNECTED75, UNCONNECTED76, UNCONNECTED77, UNCONNECTED78;
  wire UNCONNECTED79, UNCONNECTED80, UNCONNECTED81, UNCONNECTED82,
       UNCONNECTED83, UNCONNECTED84, UNCONNECTED85, UNCONNECTED86;
  wire UNCONNECTED87, UNCONNECTED88, UNCONNECTED89, UNCONNECTED90,
       UNCONNECTED91, UNCONNECTED92, UNCONNECTED93, UNCONNECTED94;
  wire UNCONNECTED95, UNCONNECTED96, UNCONNECTED97, UNCONNECTED98,
       UNCONNECTED99, UNCONNECTED100, UNCONNECTED101, UNCONNECTED102;
  wire UNCONNECTED103, UNCONNECTED104, UNCONNECTED105, UNCONNECTED106,
       UNCONNECTED107, UNCONNECTED108, UNCONNECTED109, UNCONNECTED110;
  wire UNCONNECTED111, UNCONNECTED112, UNCONNECTED113, UNCONNECTED114,
       UNCONNECTED115, UNCONNECTED116, UNCONNECTED117, UNCONNECTED118;
  wire UNCONNECTED119, UNCONNECTED120, UNCONNECTED121, UNCONNECTED122,
       UNCONNECTED123, UNCONNECTED124, UNCONNECTED125, UNCONNECTED126;
  wire UNCONNECTED127, UNCONNECTED128, UNCONNECTED129, UNCONNECTED130,
       UNCONNECTED131, UNCONNECTED132, UNCONNECTED133, UNCONNECTED134;
  wire UNCONNECTED135, UNCONNECTED136, UNCONNECTED137, n_1, n_2, n_3,
       n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_217, n_218, r_empty, rinc, w_full;
  wire winc;
  DFC3 \rdata_reg[0] (.RN (rst), .C (control_clk), .D (n_199), .Q
       (rdata[0]), .QN (UNCONNECTED));
  DFC3 \rdata_reg[1] (.RN (rst), .C (control_clk), .D (n_201), .Q
       (rdata[1]), .QN (UNCONNECTED0));
  DFC3 \rdata_reg[2] (.RN (rst), .C (control_clk), .D (n_198), .Q
       (rdata[2]), .QN (UNCONNECTED1));
  DFC3 \rdata_reg[3] (.RN (rst), .C (control_clk), .D (n_200), .Q
       (rdata[3]), .QN (UNCONNECTED2));
  DFC3 \rdata_reg[4] (.RN (rst), .C (control_clk), .D (n_197), .Q
       (rdata[4]), .QN (UNCONNECTED3));
  DFC3 \rdata_reg[5] (.RN (rst), .C (control_clk), .D (n_196), .Q
       (rdata[5]), .QN (UNCONNECTED4));
  NAND40 g5597(.A (n_192), .B (n_116), .C (n_111), .D (n_86), .Q
       (n_201));
  NAND40 g5598(.A (n_191), .B (n_68), .C (n_76), .D (n_77), .Q (n_200));
  DFC3 \rdata_reg[7] (.RN (rst), .C (control_clk), .D (n_194), .Q
       (rdata[7]), .QN (UNCONNECTED5));
  DFC3 \rdata_reg[6] (.RN (rst), .C (control_clk), .D (n_195), .Q
       (rdata[6]), .QN (UNCONNECTED6));
  NAND40 g5595(.A (n_193), .B (n_105), .C (n_93), .D (n_94), .Q
       (n_199));
  NAND40 g5596(.A (n_188), .B (n_109), .C (n_80), .D (n_112), .Q
       (n_198));
  NAND40 g5599(.A (n_190), .B (n_97), .C (n_71), .D (n_72), .Q (n_197));
  NAND40 g5600(.A (n_187), .B (n_65), .C (n_78), .D (n_121), .Q
       (n_196));
  NAND40 g5609(.A (n_171), .B (n_148), .C (n_64), .D (n_114), .Q
       (n_195));
  NAND40 g5610(.A (n_170), .B (n_150), .C (n_59), .D (n_106), .Q
       (n_194));
  AOI2110 g5603(.A (n_147), .B (\ex_mem[1] [0]), .C (n_125), .D
       (n_168), .Q (n_193));
  AOI2110 g5604(.A (n_120), .B (\ex_mem[13] [1]), .C (n_127), .D
       (n_167), .Q (n_192));
  AOI2110 g5605(.A (n_189), .B (\ex_mem[3] [3]), .C (n_124), .D
       (n_165), .Q (n_191));
  AOI2110 g5606(.A (n_189), .B (\ex_mem[3] [4]), .C (n_126), .D
       (n_164), .Q (n_190));
  AOI2110 g5607(.A (n_169), .B (\ex_mem[7] [2]), .C (n_131), .D
       (n_166), .Q (n_188));
  AOI2110 g5608(.A (n_98), .B (\ex_mem[8] [5]), .C (n_132), .D (n_163),
       .Q (n_187));
  DFE1 \ex_mem_reg[4][1] (.C (clk), .D (wdata[1]), .E (n_185), .Q
       (\ex_mem[4] [1]), .QN (UNCONNECTED7));
  DFE1 \ex_mem_reg[8][0] (.C (clk), .D (wdata[0]), .E (n_186), .Q
       (\ex_mem[8] [0]), .QN (UNCONNECTED8));
  DFE1 \ex_mem_reg[8][3] (.C (clk), .D (wdata[3]), .E (n_186), .Q
       (\ex_mem[8] [3]), .QN (UNCONNECTED9));
  DFE1 \ex_mem_reg[4][5] (.C (clk), .D (wdata[5]), .E (n_185), .Q
       (\ex_mem[4] [5]), .QN (UNCONNECTED10));
  DFE1 \ex_mem_reg[3][2] (.C (clk), .D (wdata[2]), .E (n_173), .Q
       (\ex_mem[3] [2]), .QN (UNCONNECTED11));
  DFE1 \ex_mem_reg[8][4] (.C (clk), .D (wdata[4]), .E (n_186), .Q
       (\ex_mem[8] [4]), .QN (UNCONNECTED12));
  DFE1 \ex_mem_reg[8][5] (.C (clk), .D (wdata[5]), .E (n_186), .Q
       (\ex_mem[8] [5]), .QN (UNCONNECTED13));
  DFE1 \ex_mem_reg[8][6] (.C (clk), .D (wdata[6]), .E (n_186), .Q
       (\ex_mem[8] [6]), .QN (UNCONNECTED14));
  DFE1 \ex_mem_reg[2][6] (.C (clk), .D (wdata[6]), .E (n_174), .Q
       (\ex_mem[2] [6]), .QN (UNCONNECTED15));
  DFE1 \ex_mem_reg[8][7] (.C (clk), .D (wdata[7]), .E (n_186), .Q
       (\ex_mem[8] [7]), .QN (UNCONNECTED16));
  DFE1 \ex_mem_reg[8][1] (.C (clk), .D (wdata[1]), .E (n_186), .Q
       (\ex_mem[8] [1]), .QN (UNCONNECTED17));
  DFE1 \ex_mem_reg[8][2] (.C (clk), .D (wdata[2]), .E (n_186), .Q
       (\ex_mem[8] [2]), .QN (UNCONNECTED18));
  DFE1 \ex_mem_reg[11][5] (.C (clk), .D (wdata[5]), .E (n_183), .Q
       (\ex_mem[11] [5]), .QN (UNCONNECTED19));
  DFE1 \ex_mem_reg[0][7] (.C (clk), .D (wdata[7]), .E (n_184), .Q
       (\ex_mem[0] [7]), .QN (UNCONNECTED20));
  DFE1 \ex_mem_reg[0][0] (.C (clk), .D (wdata[0]), .E (n_184), .Q
       (\ex_mem[0] [0]), .QN (UNCONNECTED21));
  DFE1 \ex_mem_reg[0][2] (.C (clk), .D (wdata[2]), .E (n_184), .Q
       (\ex_mem[0] [2]), .QN (UNCONNECTED22));
  DFE1 \ex_mem_reg[0][1] (.C (clk), .D (wdata[1]), .E (n_184), .Q
       (\ex_mem[0] [1]), .QN (UNCONNECTED23));
  DFE1 \ex_mem_reg[0][3] (.C (clk), .D (wdata[3]), .E (n_184), .Q
       (\ex_mem[0] [3]), .QN (UNCONNECTED24));
  DFE1 \ex_mem_reg[0][4] (.C (clk), .D (wdata[4]), .E (n_184), .Q
       (\ex_mem[0] [4]), .QN (UNCONNECTED25));
  DFE1 \ex_mem_reg[0][5] (.C (clk), .D (wdata[5]), .E (n_184), .Q
       (\ex_mem[0] [5]), .QN (UNCONNECTED26));
  DFE1 \ex_mem_reg[11][2] (.C (clk), .D (wdata[2]), .E (n_183), .Q
       (\ex_mem[11] [2]), .QN (UNCONNECTED27));
  DFE1 \ex_mem_reg[0][6] (.C (clk), .D (wdata[6]), .E (n_184), .Q
       (\ex_mem[0] [6]), .QN (UNCONNECTED28));
  DFE1 \ex_mem_reg[9][0] (.C (clk), .D (wdata[0]), .E (n_182), .Q
       (\ex_mem[9] [0]), .QN (UNCONNECTED29));
  DFE1 \ex_mem_reg[9][1] (.C (clk), .D (wdata[1]), .E (n_182), .Q
       (\ex_mem[9] [1]), .QN (UNCONNECTED30));
  DFE1 \ex_mem_reg[1][4] (.C (clk), .D (wdata[4]), .E (n_175), .Q
       (\ex_mem[1] [4]), .QN (UNCONNECTED31));
  DFE1 \ex_mem_reg[9][2] (.C (clk), .D (wdata[2]), .E (n_182), .Q
       (\ex_mem[9] [2]), .QN (UNCONNECTED32));
  DFE1 \ex_mem_reg[9][3] (.C (clk), .D (wdata[3]), .E (n_182), .Q
       (\ex_mem[9] [3]), .QN (UNCONNECTED33));
  DFE1 \ex_mem_reg[9][4] (.C (clk), .D (wdata[4]), .E (n_182), .Q
       (\ex_mem[9] [4]), .QN (UNCONNECTED34));
  DFE1 \ex_mem_reg[11][0] (.C (clk), .D (wdata[0]), .E (n_183), .Q
       (\ex_mem[11] [0]), .QN (UNCONNECTED35));
  DFE1 \ex_mem_reg[9][5] (.C (clk), .D (wdata[5]), .E (n_182), .Q
       (\ex_mem[9] [5]), .QN (UNCONNECTED36));
  DFE1 \ex_mem_reg[9][7] (.C (clk), .D (wdata[7]), .E (n_182), .Q
       (\ex_mem[9] [7]), .QN (UNCONNECTED37));
  DFE1 \ex_mem_reg[9][6] (.C (clk), .D (wdata[6]), .E (n_182), .Q
       (\ex_mem[9] [6]), .QN (UNCONNECTED38));
  DFE1 \ex_mem_reg[10][0] (.C (clk), .D (wdata[0]), .E (n_181), .Q
       (\ex_mem[10] [0]), .QN (UNCONNECTED39));
  DFE1 \ex_mem_reg[10][2] (.C (clk), .D (wdata[2]), .E (n_181), .Q
       (\ex_mem[10] [2]), .QN (UNCONNECTED40));
  DFE1 \ex_mem_reg[10][1] (.C (clk), .D (wdata[1]), .E (n_181), .Q
       (\ex_mem[10] [1]), .QN (UNCONNECTED41));
  DFE1 \ex_mem_reg[10][3] (.C (clk), .D (wdata[3]), .E (n_181), .Q
       (\ex_mem[10] [3]), .QN (UNCONNECTED42));
  DFE1 \ex_mem_reg[14][1] (.C (clk), .D (wdata[1]), .E (n_176), .Q
       (\ex_mem[14] [1]), .QN (UNCONNECTED43));
  DFE1 \ex_mem_reg[10][4] (.C (clk), .D (wdata[4]), .E (n_181), .Q
       (\ex_mem[10] [4]), .QN (UNCONNECTED44));
  DFE1 \ex_mem_reg[10][5] (.C (clk), .D (wdata[5]), .E (n_181), .Q
       (\ex_mem[10] [5]), .QN (UNCONNECTED45));
  DFE1 \ex_mem_reg[10][6] (.C (clk), .D (wdata[6]), .E (n_181), .Q
       (\ex_mem[10] [6]), .QN (UNCONNECTED46));
  DFE1 \ex_mem_reg[13][6] (.C (clk), .D (wdata[6]), .E (n_179), .Q
       (\ex_mem[13] [6]), .QN (UNCONNECTED47));
  DFE1 \ex_mem_reg[10][7] (.C (clk), .D (wdata[7]), .E (n_181), .Q
       (\ex_mem[10] [7]), .QN (UNCONNECTED48));
  DFE1 \ex_mem_reg[12][7] (.C (clk), .D (wdata[7]), .E (n_180), .Q
       (\ex_mem[12] [7]), .QN (UNCONNECTED49));
  DFE1 \ex_mem_reg[12][0] (.C (clk), .D (wdata[0]), .E (n_180), .Q
       (\ex_mem[12] [0]), .QN (UNCONNECTED50));
  DFE1 \ex_mem_reg[6][4] (.C (clk), .D (wdata[4]), .E (n_177), .Q
       (\ex_mem[6] [4]), .QN (UNCONNECTED51));
  DFE1 \ex_mem_reg[12][1] (.C (clk), .D (wdata[1]), .E (n_180), .Q
       (\ex_mem[12] [1]), .QN (UNCONNECTED52));
  DFE1 \ex_mem_reg[12][2] (.C (clk), .D (wdata[2]), .E (n_180), .Q
       (\ex_mem[12] [2]), .QN (UNCONNECTED53));
  DFE1 \ex_mem_reg[12][3] (.C (clk), .D (wdata[3]), .E (n_180), .Q
       (\ex_mem[12] [3]), .QN (UNCONNECTED54));
  DFE1 \ex_mem_reg[12][4] (.C (clk), .D (wdata[4]), .E (n_180), .Q
       (\ex_mem[12] [4]), .QN (UNCONNECTED55));
  DFE1 \ex_mem_reg[12][5] (.C (clk), .D (wdata[5]), .E (n_180), .Q
       (\ex_mem[12] [5]), .QN (UNCONNECTED56));
  DFE1 \ex_mem_reg[12][6] (.C (clk), .D (wdata[6]), .E (n_180), .Q
       (\ex_mem[12] [6]), .QN (UNCONNECTED57));
  DFE1 \ex_mem_reg[13][0] (.C (clk), .D (wdata[0]), .E (n_179), .Q
       (\ex_mem[13] [0]), .QN (UNCONNECTED58));
  DFE1 \ex_mem_reg[5][0] (.C (clk), .D (wdata[0]), .E (n_178), .Q
       (\ex_mem[5] [0]), .QN (UNCONNECTED59));
  DFE1 \ex_mem_reg[5][1] (.C (clk), .D (wdata[1]), .E (n_178), .Q
       (\ex_mem[5] [1]), .QN (UNCONNECTED60));
  DFE1 \ex_mem_reg[5][2] (.C (clk), .D (wdata[2]), .E (n_178), .Q
       (\ex_mem[5] [2]), .QN (UNCONNECTED61));
  DFE1 \ex_mem_reg[5][3] (.C (clk), .D (wdata[3]), .E (n_178), .Q
       (\ex_mem[5] [3]), .QN (UNCONNECTED62));
  DFE1 \ex_mem_reg[13][1] (.C (clk), .D (wdata[1]), .E (n_179), .Q
       (\ex_mem[13] [1]), .QN (UNCONNECTED63));
  DFE1 \ex_mem_reg[5][4] (.C (clk), .D (wdata[4]), .E (n_178), .Q
       (\ex_mem[5] [4]), .QN (UNCONNECTED64));
  DFE1 \ex_mem_reg[5][5] (.C (clk), .D (wdata[5]), .E (n_178), .Q
       (\ex_mem[5] [5]), .QN (UNCONNECTED65));
  DFE1 \ex_mem_reg[5][6] (.C (clk), .D (wdata[6]), .E (n_178), .Q
       (\ex_mem[5] [6]), .QN (UNCONNECTED66));
  DFE1 \ex_mem_reg[13][2] (.C (clk), .D (wdata[2]), .E (n_179), .Q
       (\ex_mem[13] [2]), .QN (UNCONNECTED67));
  DFE1 \ex_mem_reg[5][7] (.C (clk), .D (wdata[7]), .E (n_178), .Q
       (\ex_mem[5] [7]), .QN (UNCONNECTED68));
  DFE1 \ex_mem_reg[6][0] (.C (clk), .D (wdata[0]), .E (n_177), .Q
       (\ex_mem[6] [0]), .QN (UNCONNECTED69));
  DFE1 \ex_mem_reg[6][1] (.C (clk), .D (wdata[1]), .E (n_177), .Q
       (\ex_mem[6] [1]), .QN (UNCONNECTED70));
  DFE1 \ex_mem_reg[13][3] (.C (clk), .D (wdata[3]), .E (n_179), .Q
       (\ex_mem[13] [3]), .QN (UNCONNECTED71));
  DFE1 \ex_mem_reg[6][2] (.C (clk), .D (wdata[2]), .E (n_177), .Q
       (\ex_mem[6] [2]), .QN (UNCONNECTED72));
  DFE1 \ex_mem_reg[13][4] (.C (clk), .D (wdata[4]), .E (n_179), .Q
       (\ex_mem[13] [4]), .QN (UNCONNECTED73));
  DFE1 \ex_mem_reg[6][3] (.C (clk), .D (wdata[3]), .E (n_177), .Q
       (\ex_mem[6] [3]), .QN (UNCONNECTED74));
  DFE1 \ex_mem_reg[13][5] (.C (clk), .D (wdata[5]), .E (n_179), .Q
       (\ex_mem[13] [5]), .QN (UNCONNECTED75));
  DFE1 \ex_mem_reg[6][5] (.C (clk), .D (wdata[5]), .E (n_177), .Q
       (\ex_mem[6] [5]), .QN (UNCONNECTED76));
  DFE1 \ex_mem_reg[6][6] (.C (clk), .D (wdata[6]), .E (n_177), .Q
       (\ex_mem[6] [6]), .QN (UNCONNECTED77));
  DFE1 \ex_mem_reg[6][7] (.C (clk), .D (wdata[7]), .E (n_177), .Q
       (\ex_mem[6] [7]), .QN (UNCONNECTED78));
  DFE1 \ex_mem_reg[13][7] (.C (clk), .D (wdata[7]), .E (n_179), .Q
       (\ex_mem[13] [7]), .QN (UNCONNECTED79));
  DFE1 \ex_mem_reg[14][0] (.C (clk), .D (wdata[0]), .E (n_176), .Q
       (\ex_mem[14] [0]), .QN (UNCONNECTED80));
  DFE1 \ex_mem_reg[14][2] (.C (clk), .D (wdata[2]), .E (n_176), .Q
       (\ex_mem[14] [2]), .QN (UNCONNECTED81));
  DFE1 \ex_mem_reg[14][3] (.C (clk), .D (wdata[3]), .E (n_176), .Q
       (\ex_mem[14] [3]), .QN (UNCONNECTED82));
  DFE1 \ex_mem_reg[14][4] (.C (clk), .D (wdata[4]), .E (n_176), .Q
       (\ex_mem[14] [4]), .QN (UNCONNECTED83));
  DFE1 \ex_mem_reg[14][5] (.C (clk), .D (wdata[5]), .E (n_176), .Q
       (\ex_mem[14] [5]), .QN (UNCONNECTED84));
  DFE1 \ex_mem_reg[14][6] (.C (clk), .D (wdata[6]), .E (n_176), .Q
       (\ex_mem[14] [6]), .QN (UNCONNECTED85));
  DFE1 \ex_mem_reg[14][7] (.C (clk), .D (wdata[7]), .E (n_176), .Q
       (\ex_mem[14] [7]), .QN (UNCONNECTED86));
  DFE1 \ex_mem_reg[1][0] (.C (clk), .D (wdata[0]), .E (n_175), .Q
       (\ex_mem[1] [0]), .QN (UNCONNECTED87));
  DFE1 \ex_mem_reg[1][2] (.C (clk), .D (wdata[2]), .E (n_175), .Q
       (\ex_mem[1] [2]), .QN (UNCONNECTED88));
  DFE1 \ex_mem_reg[1][1] (.C (clk), .D (wdata[1]), .E (n_175), .Q
       (\ex_mem[1] [1]), .QN (UNCONNECTED89));
  DFE1 \ex_mem_reg[1][3] (.C (clk), .D (wdata[3]), .E (n_175), .Q
       (\ex_mem[1] [3]), .QN (UNCONNECTED90));
  DFE1 \ex_mem_reg[11][1] (.C (clk), .D (wdata[1]), .E (n_183), .Q
       (\ex_mem[11] [1]), .QN (UNCONNECTED91));
  DFE1 \ex_mem_reg[1][5] (.C (clk), .D (wdata[5]), .E (n_175), .Q
       (\ex_mem[1] [5]), .QN (UNCONNECTED92));
  DFE1 \ex_mem_reg[1][6] (.C (clk), .D (wdata[6]), .E (n_175), .Q
       (\ex_mem[1] [6]), .QN (UNCONNECTED93));
  DFE1 \ex_mem_reg[1][7] (.C (clk), .D (wdata[7]), .E (n_175), .Q
       (\ex_mem[1] [7]), .QN (UNCONNECTED94));
  DFE1 \ex_mem_reg[11][3] (.C (clk), .D (wdata[3]), .E (n_183), .Q
       (\ex_mem[11] [3]), .QN (UNCONNECTED95));
  DFE1 \ex_mem_reg[2][0] (.C (clk), .D (wdata[0]), .E (n_174), .Q
       (\ex_mem[2] [0]), .QN (UNCONNECTED96));
  DFE1 \ex_mem_reg[2][1] (.C (clk), .D (wdata[1]), .E (n_174), .Q
       (\ex_mem[2] [1]), .QN (UNCONNECTED97));
  DFE1 \ex_mem_reg[2][2] (.C (clk), .D (wdata[2]), .E (n_174), .Q
       (\ex_mem[2] [2]), .QN (UNCONNECTED98));
  DFE1 \ex_mem_reg[11][4] (.C (clk), .D (wdata[4]), .E (n_183), .Q
       (\ex_mem[11] [4]), .QN (UNCONNECTED99));
  DFE1 \ex_mem_reg[2][3] (.C (clk), .D (wdata[3]), .E (n_174), .Q
       (\ex_mem[2] [3]), .QN (UNCONNECTED100));
  DFE1 \ex_mem_reg[2][4] (.C (clk), .D (wdata[4]), .E (n_174), .Q
       (\ex_mem[2] [4]), .QN (UNCONNECTED101));
  DFE1 \ex_mem_reg[2][5] (.C (clk), .D (wdata[5]), .E (n_174), .Q
       (\ex_mem[2] [5]), .QN (UNCONNECTED102));
  DFE1 \ex_mem_reg[11][6] (.C (clk), .D (wdata[6]), .E (n_183), .Q
       (\ex_mem[11] [6]), .QN (UNCONNECTED103));
  DFE1 \ex_mem_reg[2][7] (.C (clk), .D (wdata[7]), .E (n_174), .Q
       (\ex_mem[2] [7]), .QN (UNCONNECTED104));
  DFE1 \ex_mem_reg[3][0] (.C (clk), .D (wdata[0]), .E (n_173), .Q
       (\ex_mem[3] [0]), .QN (UNCONNECTED105));
  DFE1 \ex_mem_reg[3][1] (.C (clk), .D (wdata[1]), .E (n_173), .Q
       (\ex_mem[3] [1]), .QN (UNCONNECTED106));
  DFE1 \ex_mem_reg[11][7] (.C (clk), .D (wdata[7]), .E (n_183), .Q
       (\ex_mem[11] [7]), .QN (UNCONNECTED107));
  DFE1 \ex_mem_reg[3][3] (.C (clk), .D (wdata[3]), .E (n_173), .Q
       (\ex_mem[3] [3]), .QN (UNCONNECTED108));
  DFE1 \ex_mem_reg[3][4] (.C (clk), .D (wdata[4]), .E (n_173), .Q
       (\ex_mem[3] [4]), .QN (UNCONNECTED109));
  DFE1 \ex_mem_reg[3][5] (.C (clk), .D (wdata[5]), .E (n_173), .Q
       (\ex_mem[3] [5]), .QN (UNCONNECTED110));
  DFE1 \ex_mem_reg[3][6] (.C (clk), .D (wdata[6]), .E (n_173), .Q
       (\ex_mem[3] [6]), .QN (UNCONNECTED111));
  DFE1 \ex_mem_reg[3][7] (.C (clk), .D (wdata[7]), .E (n_173), .Q
       (\ex_mem[3] [7]), .QN (UNCONNECTED112));
  DFE1 \ex_mem_reg[4][0] (.C (clk), .D (wdata[0]), .E (n_185), .Q
       (\ex_mem[4] [0]), .QN (UNCONNECTED113));
  DFE1 \ex_mem_reg[4][2] (.C (clk), .D (wdata[2]), .E (n_185), .Q
       (\ex_mem[4] [2]), .QN (UNCONNECTED114));
  DFE1 \ex_mem_reg[4][3] (.C (clk), .D (wdata[3]), .E (n_185), .Q
       (\ex_mem[4] [3]), .QN (UNCONNECTED115));
  DFE1 \ex_mem_reg[4][4] (.C (clk), .D (wdata[4]), .E (n_185), .Q
       (\ex_mem[4] [4]), .QN (UNCONNECTED116));
  DFE1 \ex_mem_reg[4][6] (.C (clk), .D (wdata[6]), .E (n_185), .Q
       (\ex_mem[4] [6]), .QN (UNCONNECTED117));
  DFE1 \ex_mem_reg[4][7] (.C (clk), .D (wdata[7]), .E (n_185), .Q
       (\ex_mem[4] [7]), .QN (UNCONNECTED118));
  DFE1 \ex_mem_reg[7][4] (.C (clk), .D (wdata[4]), .E (n_172), .Q
       (\ex_mem[7] [4]), .QN (UNCONNECTED119));
  DFE1 \ex_mem_reg[7][0] (.C (clk), .D (wdata[0]), .E (n_172), .Q
       (\ex_mem[7] [0]), .QN (UNCONNECTED120));
  DFE1 \ex_mem_reg[7][1] (.C (clk), .D (wdata[1]), .E (n_172), .Q
       (\ex_mem[7] [1]), .QN (UNCONNECTED121));
  DFE1 \ex_mem_reg[7][2] (.C (clk), .D (wdata[2]), .E (n_172), .Q
       (\ex_mem[7] [2]), .QN (UNCONNECTED122));
  DFE1 \ex_mem_reg[7][3] (.C (clk), .D (wdata[3]), .E (n_172), .Q
       (\ex_mem[7] [3]), .QN (UNCONNECTED123));
  DFE1 \ex_mem_reg[7][5] (.C (clk), .D (wdata[5]), .E (n_172), .Q
       (\ex_mem[7] [5]), .QN (UNCONNECTED124));
  DFE1 \ex_mem_reg[7][6] (.C (clk), .D (wdata[6]), .E (n_172), .Q
       (\ex_mem[7] [6]), .QN (UNCONNECTED125));
  DFE1 \ex_mem_reg[7][7] (.C (clk), .D (wdata[7]), .E (n_172), .Q
       (\ex_mem[7] [7]), .QN (UNCONNECTED126));
  AOI2110 g5750(.A (n_108), .B (\ex_mem[9] [6]), .C (n_133), .D
       (n_153), .Q (n_171));
  AOI2110 g5751(.A (n_169), .B (\ex_mem[7] [7]), .C (n_130), .D
       (n_154), .Q (n_170));
  NAND40 g5723(.A (n_145), .B (n_88), .C (n_90), .D (n_74), .Q (n_168));
  NAND40 g5724(.A (n_144), .B (n_85), .C (n_82), .D (n_81), .Q (n_167));
  NAND40 g5725(.A (n_143), .B (n_84), .C (n_79), .D (n_104), .Q
       (n_166));
  NAND40 g5726(.A (n_142), .B (n_95), .C (n_113), .D (n_75), .Q
       (n_165));
  NAND40 g5727(.A (n_152), .B (n_69), .C (n_66), .D (n_70), .Q (n_164));
  NAND40 g5728(.A (n_146), .B (n_67), .C (n_92), .D (n_60), .Q (n_163));
  NOR21 g5769(.A (n_157), .B (n_161), .Q (n_186));
  NOR21 g5770(.A (n_162), .B (n_156), .Q (n_173));
  NOR21 g5771(.A (n_160), .B (n_158), .Q (n_177));
  NOR21 g5772(.A (n_162), .B (n_161), .Q (n_184));
  NOR21 g5773(.A (n_159), .B (n_161), .Q (n_180));
  NOR21 g5774(.A (n_160), .B (n_161), .Q (n_185));
  NOR21 g5775(.A (n_160), .B (n_155), .Q (n_178));
  NOR21 g5779(.A (n_159), .B (n_158), .Q (n_176));
  NOR21 g5780(.A (n_157), .B (n_156), .Q (n_183));
  NOR21 g5781(.A (n_159), .B (n_155), .Q (n_179));
  NOR21 g5782(.A (n_157), .B (n_155), .Q (n_182));
  NOR21 g5783(.A (n_157), .B (n_158), .Q (n_181));
  NOR21 g5784(.A (n_162), .B (n_158), .Q (n_174));
  NOR21 g5785(.A (n_162), .B (n_155), .Q (n_175));
  DFC3 \r_pointer_reg[0] (.RN (rst), .C (control_clk), .D (n_141), .Q
       (r_pointer[0]), .QN (n_4));
  NAND40 g5787(.A (n_100), .B (n_102), .C (n_83), .D (n_87), .Q
       (n_154));
  NAND40 g5788(.A (n_61), .B (n_117), .C (n_63), .D (n_62), .Q (n_153));
  DFC3 \r_pointer_reg[3] (.RN (rst), .C (control_clk), .D (n_134), .Q
       (r_pointer[3]), .QN (n_27));
  DFC3 \r_pointer_reg[1] (.RN (rst), .C (control_clk), .D (n_140), .Q
       (r_pointer[1]), .QN (n_3));
  DFC3 \r_pointer_reg[2] (.RN (rst), .C (control_clk), .D (n_138), .Q
       (r_pointer[2]), .QN (n_218));
  AOI220 g5766(.A (n_99), .B (\ex_mem[2] [4]), .C (n_149), .D
       (rdata[4]), .Q (n_152));
  DFC3 \w_pointer_reg[2] (.RN (rst), .C (clk), .D (n_129), .Q
       (w_pointer[2]), .QN (n_136));
  NOR21 g5795(.A (n_118), .B (n_19), .Q (n_172));
  DFC3 \w_pointer_reg[1] (.RN (rst), .C (clk), .D (n_73), .Q
       (w_pointer[1]), .QN (n_6));
  DFC3 \w_pointer_reg[3] (.RN (rst), .C (clk), .D (n_123), .Q
       (w_pointer[3]), .QN (n_47));
  DFEC1 \data_to_mosi_reg[0] (.RN (rst), .C (control_clk), .D
       (rdata[0]), .E (n_151), .Q (data_to_mosi[0]), .QN
       (UNCONNECTED127));
  DFEC1 \data_to_mosi_reg[5] (.RN (rst), .C (control_clk), .D
       (rdata[5]), .E (n_151), .Q (data_to_mosi[5]), .QN
       (UNCONNECTED128));
  DFEC1 \data_to_mosi_reg[6] (.RN (rst), .C (control_clk), .D
       (rdata[6]), .E (n_151), .Q (data_to_mosi[6]), .QN
       (UNCONNECTED129));
  DFEC1 \data_to_mosi_reg[7] (.RN (rst), .C (control_clk), .D
       (rdata[7]), .E (n_151), .Q (data_to_mosi[7]), .QN
       (UNCONNECTED130));
  DFEC1 \data_to_mosi_reg[1] (.RN (rst), .C (control_clk), .D
       (rdata[1]), .E (n_151), .Q (data_to_mosi[1]), .QN
       (UNCONNECTED131));
  DFEC1 \data_to_mosi_reg[2] (.RN (rst), .C (control_clk), .D
       (rdata[2]), .E (n_151), .Q (data_to_mosi[2]), .QN
       (UNCONNECTED132));
  DFEC1 \data_to_mosi_reg[3] (.RN (rst), .C (control_clk), .D
       (rdata[3]), .E (n_151), .Q (data_to_mosi[3]), .QN
       (UNCONNECTED133));
  DFEC1 \data_to_mosi_reg[4] (.RN (rst), .C (control_clk), .D
       (rdata[4]), .E (n_151), .Q (data_to_mosi[4]), .QN
       (UNCONNECTED134));
  DFP3 r_empty_reg(.SN (rst), .C (control_clk), .D (n_119), .Q
       (r_empty), .QN (n_25));
  AOI220 g5759(.A (n_189), .B (\ex_mem[3] [7]), .C (n_149), .D
       (rdata[7]), .Q (n_150));
  AOI220 g5760(.A (n_147), .B (\ex_mem[1] [6]), .C (n_149), .D
       (rdata[6]), .Q (n_148));
  AOI220 g5761(.A (n_107), .B (\ex_mem[5] [5]), .C (n_149), .D
       (rdata[5]), .Q (n_146));
  AOI220 g5762(.A (n_189), .B (\ex_mem[3] [0]), .C (n_149), .D
       (rdata[0]), .Q (n_145));
  AOI220 g5763(.A (n_147), .B (\ex_mem[1] [1]), .C (n_149), .D
       (rdata[1]), .Q (n_144));
  AOI220 g5764(.A (n_115), .B (\ex_mem[11] [2]), .C (n_149), .D
       (rdata[2]), .Q (n_143));
  AOI220 g5765(.A (n_147), .B (\ex_mem[1] [3]), .C (n_149), .D
       (rdata[3]), .Q (n_142));
  NOR20 g5776(.A (n_23), .B (n_139), .Q (n_141));
  NOR20 g5777(.A (n_18), .B (n_139), .Q (n_140));
  NOR20 g5778(.A (n_31), .B (n_139), .Q (n_138));
  NAND22 g5794(.A (w_pointer[2]), .B (n_137), .Q (n_160));
  NAND22 g5796(.A (n_136), .B (n_137), .Q (n_162));
  NAND22 g5797(.A (w_pointer[2]), .B (n_135), .Q (n_159));
  NAND22 g5798(.A (n_136), .B (n_135), .Q (n_157));
  JKC3 \w_pointer_reg[0] (.RN (rst), .C (clk), .J (n_45), .K (n_128),
       .Q (w_pointer[0]), .QN (n_5));
  NOR20 g5757(.A (n_139), .B (n_50), .Q (n_134));
  INV0 g5853(.A (n_58), .Q (n_133));
  INV0 g5855(.A (n_57), .Q (n_132));
  INV0 g5857(.A (n_56), .Q (n_131));
  INV0 g5859(.A (n_55), .Q (n_130));
  OAI222 g5767(.A (n_136), .B (n_128), .C (n_15), .D (n_122), .Q
       (n_129));
  INV0 g5861(.A (n_54), .Q (n_127));
  INV0 g5863(.A (n_53), .Q (n_126));
  INV0 g5865(.A (n_52), .Q (n_125));
  INV0 g5867(.A (n_51), .Q (n_124));
  OAI222 g5768(.A (n_47), .B (n_128), .C (n_21), .D (n_122), .Q
       (n_123));
  AOI220 g5812(.A (n_189), .B (\ex_mem[3] [5]), .C (n_120), .D
       (\ex_mem[13] [5]), .Q (n_121));
  OAI210 g5786(.A (n_25), .B (n_26), .C (n_49), .Q (n_119));
  DFEC1 w_full_reg(.RN (rst), .C (clk), .D (n_33), .E (n_35), .Q
       (w_full), .QN (n_24));
  INV2 g5800(.A (n_137), .Q (n_118));
  AOI220 g5804(.A (n_189), .B (\ex_mem[3] [6]), .C (n_120), .D
       (\ex_mem[13] [6]), .Q (n_117));
  AOI220 g5805(.A (n_115), .B (\ex_mem[11] [1]), .C (n_169), .D
       (\ex_mem[7] [1]), .Q (n_116));
  AOI220 g5806(.A (n_110), .B (\ex_mem[0] [6]), .C (n_103), .D
       (\ex_mem[12] [6]), .Q (n_114));
  AOI220 g5807(.A (n_89), .B (\ex_mem[10] [3]), .C (n_115), .D
       (\ex_mem[11] [3]), .Q (n_113));
  AOI220 g5808(.A (n_147), .B (\ex_mem[1] [2]), .C (n_120), .D
       (\ex_mem[13] [2]), .Q (n_112));
  AOI220 g5809(.A (n_110), .B (\ex_mem[0] [1]), .C (n_91), .D
       (\ex_mem[4] [1]), .Q (n_111));
  AOI220 g5810(.A (n_108), .B (\ex_mem[9] [2]), .C (n_107), .D
       (\ex_mem[5] [2]), .Q (n_109));
  AOI220 g5811(.A (n_108), .B (\ex_mem[9] [7]), .C (n_96), .D
       (\ex_mem[6] [7]), .Q (n_106));
  AOI220 g5813(.A (n_108), .B (\ex_mem[9] [0]), .C (n_115), .D
       (\ex_mem[11] [0]), .Q (n_105));
  AOI220 g5814(.A (n_103), .B (\ex_mem[12] [2]), .C (n_101), .D
       (\ex_mem[14] [2]), .Q (n_104));
  AOI220 g5815(.A (n_103), .B (\ex_mem[12] [7]), .C (n_101), .D
       (\ex_mem[14] [7]), .Q (n_102));
  AOI220 g5816(.A (n_99), .B (\ex_mem[2] [7]), .C (n_98), .D
       (\ex_mem[8] [7]), .Q (n_100));
  AOI220 g5817(.A (n_96), .B (\ex_mem[6] [4]), .C (n_120), .D
       (\ex_mem[13] [4]), .Q (n_97));
  AOI220 g5818(.A (n_110), .B (\ex_mem[0] [3]), .C (n_98), .D
       (\ex_mem[8] [3]), .Q (n_95));
  AOI220 g5819(.A (n_103), .B (\ex_mem[12] [0]), .C (n_101), .D
       (\ex_mem[14] [0]), .Q (n_94));
  AOI220 g5820(.A (n_110), .B (\ex_mem[0] [0]), .C (n_98), .D
       (\ex_mem[8] [0]), .Q (n_93));
  AOI220 g5821(.A (n_91), .B (\ex_mem[4] [5]), .C (n_108), .D
       (\ex_mem[9] [5]), .Q (n_92));
  AOI220 g5822(.A (n_99), .B (\ex_mem[2] [0]), .C (n_89), .D
       (\ex_mem[10] [0]), .Q (n_90));
  AOI220 g5823(.A (n_91), .B (\ex_mem[4] [0]), .C (n_169), .D
       (\ex_mem[7] [0]), .Q (n_88));
  AOI220 g5824(.A (n_110), .B (\ex_mem[0] [7]), .C (n_120), .D
       (\ex_mem[13] [7]), .Q (n_87));
  AOI220 g5825(.A (n_98), .B (\ex_mem[8] [1]), .C (n_96), .D
       (\ex_mem[6] [1]), .Q (n_86));
  AOI220 g5826(.A (n_189), .B (\ex_mem[3] [1]), .C (n_108), .D
       (\ex_mem[9] [1]), .Q (n_85));
  AOI220 g5827(.A (n_98), .B (\ex_mem[8] [2]), .C (n_89), .D
       (\ex_mem[10] [2]), .Q (n_84));
  AOI220 g5828(.A (n_147), .B (\ex_mem[1] [7]), .C (n_89), .D
       (\ex_mem[10] [7]), .Q (n_83));
  AOI220 g5829(.A (n_99), .B (\ex_mem[2] [1]), .C (n_89), .D
       (\ex_mem[10] [1]), .Q (n_82));
  AOI220 g5830(.A (n_103), .B (\ex_mem[12] [1]), .C (n_101), .D
       (\ex_mem[14] [1]), .Q (n_81));
  AOI220 g5831(.A (n_189), .B (\ex_mem[3] [2]), .C (n_96), .D
       (\ex_mem[6] [2]), .Q (n_80));
  AOI220 g5832(.A (n_110), .B (\ex_mem[0] [2]), .C (n_99), .D
       (\ex_mem[2] [2]), .Q (n_79));
  AOI220 g5833(.A (n_110), .B (\ex_mem[0] [5]), .C (n_89), .D
       (\ex_mem[10] [5]), .Q (n_78));
  AOI220 g5834(.A (n_99), .B (\ex_mem[2] [3]), .C (n_169), .D
       (\ex_mem[7] [3]), .Q (n_77));
  AOI220 g5835(.A (n_91), .B (\ex_mem[4] [3]), .C (n_96), .D
       (\ex_mem[6] [3]), .Q (n_76));
  AOI220 g5836(.A (n_103), .B (\ex_mem[12] [3]), .C (n_101), .D
       (\ex_mem[14] [3]), .Q (n_75));
  AOI220 g5837(.A (n_96), .B (\ex_mem[6] [0]), .C (n_107), .D
       (\ex_mem[5] [0]), .Q (n_74));
  OAI212 g5758(.A (n_128), .B (n_6), .C (n_44), .Q (n_73));
  AOI220 g5838(.A (n_147), .B (\ex_mem[1] [4]), .C (n_169), .D
       (\ex_mem[7] [4]), .Q (n_72));
  AOI220 g5839(.A (n_91), .B (\ex_mem[4] [4]), .C (n_115), .D
       (\ex_mem[11] [4]), .Q (n_71));
  AOI220 g5840(.A (n_103), .B (\ex_mem[12] [4]), .C (n_101), .D
       (\ex_mem[14] [4]), .Q (n_70));
  AOI220 g5841(.A (n_98), .B (\ex_mem[8] [4]), .C (n_89), .D
       (\ex_mem[10] [4]), .Q (n_69));
  AOI220 g5842(.A (n_108), .B (\ex_mem[9] [3]), .C (n_120), .D
       (\ex_mem[13] [3]), .Q (n_68));
  AOI220 g5843(.A (n_147), .B (\ex_mem[1] [5]), .C (n_115), .D
       (\ex_mem[11] [5]), .Q (n_67));
  AOI220 g5844(.A (n_110), .B (\ex_mem[0] [4]), .C (n_108), .D
       (\ex_mem[9] [4]), .Q (n_66));
  AOI220 g5845(.A (n_99), .B (\ex_mem[2] [5]), .C (n_101), .D
       (\ex_mem[14] [5]), .Q (n_65));
  AOI220 g5846(.A (n_98), .B (\ex_mem[8] [6]), .C (n_115), .D
       (\ex_mem[11] [6]), .Q (n_64));
  AOI220 g5847(.A (n_89), .B (\ex_mem[10] [6]), .C (n_107), .D
       (\ex_mem[5] [6]), .Q (n_63));
  AOI220 g5848(.A (n_96), .B (\ex_mem[6] [6]), .C (n_169), .D
       (\ex_mem[7] [6]), .Q (n_62));
  AOI220 g5849(.A (n_99), .B (\ex_mem[2] [6]), .C (n_91), .D
       (\ex_mem[4] [6]), .Q (n_61));
  AOI220 g5850(.A (n_96), .B (\ex_mem[6] [5]), .C (n_169), .D
       (\ex_mem[7] [5]), .Q (n_60));
  AOI220 g5851(.A (n_91), .B (\ex_mem[4] [7]), .C (n_115), .D
       (\ex_mem[11] [7]), .Q (n_59));
  NAND20 g5854(.A (n_101), .B (\ex_mem[14] [6]), .Q (n_58));
  NAND20 g5856(.A (n_103), .B (\ex_mem[12] [5]), .Q (n_57));
  NAND20 g5858(.A (n_91), .B (\ex_mem[4] [2]), .Q (n_56));
  NAND20 g5860(.A (n_107), .B (\ex_mem[5] [7]), .Q (n_55));
  NAND20 g5862(.A (n_107), .B (\ex_mem[5] [1]), .Q (n_54));
  NAND20 g5864(.A (n_107), .B (\ex_mem[5] [4]), .Q (n_53));
  NAND20 g5866(.A (n_120), .B (\ex_mem[13] [0]), .Q (n_52));
  NAND20 g5868(.A (n_107), .B (\ex_mem[5] [3]), .Q (n_51));
  IMUX20 g5789(.A (r_pointer[3]), .B (n_32), .S (n_30), .Q (n_50));
  INV0 g5790(.A (n_49), .Q (n_139));
  CLKIN0 g5792(.A (n_151), .Q (n_149));
  NOR21 g5801(.A (n_48), .B (w_pointer[3]), .Q (n_137));
  NOR21 g5803(.A (n_48), .B (n_47), .Q (n_135));
  NAND20 g5791(.A (n_46), .B (rinc), .Q (n_49));
  NOR20 g5793(.A (n_22), .B (n_46), .Q (n_151));
  NAND22 g5869(.A (n_45), .B (rst), .Q (n_48));
  OAI212 g5871(.A (n_8), .B (n_9), .C (n_45), .Q (n_44));
  NOR20 g5875(.A (n_39), .B (n_42), .Q (n_115));
  NOR20 g5876(.A (n_43), .B (n_36), .Q (n_103));
  NOR20 g5877(.A (n_43), .B (n_41), .Q (n_91));
  NOR20 g5878(.A (n_43), .B (n_37), .Q (n_110));
  NOR20 g5879(.A (n_40), .B (n_42), .Q (n_89));
  NOR20 g5880(.A (n_38), .B (n_41), .Q (n_107));
  NOR20 g5881(.A (n_40), .B (n_41), .Q (n_96));
  NOR20 g5882(.A (n_39), .B (n_41), .Q (n_169));
  NOR20 g5883(.A (n_38), .B (n_42), .Q (n_108));
  NOR20 g5884(.A (n_43), .B (n_42), .Q (n_98));
  NOR20 g5885(.A (n_39), .B (n_37), .Q (n_189));
  NOR20 g5886(.A (n_38), .B (n_36), .Q (n_120));
  NOR20 g5887(.A (n_40), .B (n_36), .Q (n_101));
  NOR20 g5888(.A (n_38), .B (n_37), .Q (n_147));
  NOR20 g5889(.A (n_40), .B (n_37), .Q (n_99));
  OAI212 g5799(.A (n_10), .B (n_34), .C (n_122), .Q (n_128));
  NAND22 g5802(.A (n_34), .B (n_33), .Q (n_35));
  ADD21 g5852(.A (n_16), .B (r_pointer[3]), .CO (n_46), .S (n_32));
  IMUX20 g5873(.A (r_pointer[2]), .B (n_17), .S (n_30), .Q (n_31));
  INV3 g5890(.A (n_122), .Q (n_45));
  NAND20 g5892(.A (n_29), .B (n_27), .Q (n_41));
  NAND20 g5893(.A (n_28), .B (r_pointer[3]), .Q (n_42));
  NAND20 g5894(.A (n_29), .B (r_pointer[3]), .Q (n_36));
  NAND20 g5895(.A (n_28), .B (n_27), .Q (n_37));
  NAND31 g5870(.A (n_20), .B (w_pointer[3]), .C (winc), .Q (n_34));
  NOR40 g5872(.A (winc), .B (1'b0), .C (n_14), .D (n_24), .Q (n_26));
  NAND31 g5891(.A (n_24), .B (n_33), .C (winc), .Q (n_122));
  IMUX20 g5899(.A (n_30), .B (n_22), .S (r_pointer[0]), .Q (n_23));
  IMUX21 g5874(.A (n_20), .B (n_19), .S (w_pointer[3]), .Q (n_21));
  IMUX20 g5896(.A (r_pointer[1]), .B (n_13), .S (n_30), .Q (n_18));
  NOR20 g5901(.A (n_218), .B (n_22), .Q (n_29));
  NOR20 g5902(.A (r_pointer[2]), .B (n_22), .Q (n_28));
  ADD21 g5898(.A (n_7), .B (r_pointer[2]), .CO (n_16), .S (n_17));
  INV0 g5907(.A (n_30), .Q (n_22));
  DFC3 winc_reg(.RN (rst), .C (clk), .D (n_217), .Q (winc), .QN
       (UNCONNECTED135));
  CLKIN3 g5897(.A (n_20), .Q (n_19));
  IMUX21 g5903(.A (n_136), .B (w_pointer[2]), .S (n_156), .Q (n_15));
  NOR20 g5908(.A (r_empty), .B (n_14), .Q (n_30));
  NAND20 g5909(.A (n_38), .B (n_40), .Q (n_13));
  DFC3 data_en_reg(.RN (rst), .C (data_av), .D (n_2), .Q
       (UNCONNECTED136), .QN (n_11));
  NOR21 g5906(.A (n_136), .B (n_156), .Q (n_20));
  INV0 g5913(.A (n_33), .Q (n_10));
  INV2 g5921(.A (n_158), .Q (n_9));
  CLKIN2 g5924(.A (n_155), .Q (n_8));
  DFC3 spi_cs_reg(.RN (rst), .C (clk), .D (n_1), .Q (spi_cs), .QN
       (UNCONNECTED137));
  NAND20 g5914(.A (n_11), .B (r_empty), .Q (n_33));
  INV0 g5916(.A (n_39), .Q (n_7));
  NAND20 g5918(.A (n_4), .B (n_3), .Q (n_43));
  NAND22 g5919(.A (n_6), .B (n_5), .Q (n_161));
  NAND22 g5922(.A (n_5), .B (w_pointer[1]), .Q (n_158));
  NAND20 g5923(.A (n_4), .B (r_pointer[1]), .Q (n_40));
  NAND22 g5925(.A (n_6), .B (w_pointer[0]), .Q (n_155));
  NAND20 g5926(.A (r_pointer[0]), .B (n_3), .Q (n_38));
  NAND20 g5927(.A (w_full), .B (n_25), .Q (n_2));
  NOR21 g5920(.A (r_empty), .B (w_full), .Q (n_1));
  DFC3 rinc_reg(.RN (rst), .C (clk), .D (w_full), .Q (rinc), .QN
       (n_14));
  NAND20 g5917(.A (r_pointer[0]), .B (r_pointer[1]), .Q (n_39));
  NAND22 g5915(.A (w_pointer[0]), .B (w_pointer[1]), .Q (n_156));
  NOR21 g2(.A (n_11), .B (w_full), .Q (n_217));
endmodule

