`timescale 1 ns / 1 ps
// Generated by Cadence Encounter(R) RTL Compiler v11.20-s017_1

// Verification Directory fv/spi_final 

module spi_mosi(control_clk, spi_mosi_out, spi_cs, spi_clk, n_reset,
     spi_mosi_in);
  input spi_cs, spi_clk, n_reset;
  input [7:0] spi_mosi_in;
  output control_clk, spi_mosi_out;
  wire spi_cs, spi_clk, n_reset;
  wire [7:0] spi_mosi_in;
  wire control_clk, spi_mosi_out;
  wire [2:0] control;
  wire [7:0] data;
  wire [3:0] point_add;
  wire [2:0] point;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81;
  TFEC3 control_clk_reg(.RN (n_reset), .C (spi_clk), .T (n_55), .Q
       (control_clk), .QN (n_11));
  DFC3 \control_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_67), .Q
       (control[0]), .QN (UNCONNECTED));
  DFP3 \control_reg[1] (.SN (n_reset), .C (spi_clk), .D (n_66), .Q
       (control[1]), .QN (UNCONNECTED0));
  DFC3 \control_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_65), .Q
       (control[2]), .QN (UNCONNECTED1));
  DFC3 \data_reg[0] (.RN (n_reset), .C (control_clk), .D (n_27), .Q
       (data[0]), .QN (UNCONNECTED2));
  DFC3 \data_reg[1] (.RN (n_reset), .C (control_clk), .D (n_21), .Q
       (data[1]), .QN (UNCONNECTED3));
  DFC3 \data_reg[2] (.RN (n_reset), .C (control_clk), .D (n_24), .Q
       (data[2]), .QN (UNCONNECTED4));
  DFC3 \data_reg[3] (.RN (n_reset), .C (control_clk), .D (n_26), .Q
       (data[3]), .QN (UNCONNECTED5));
  DFC3 \data_reg[4] (.RN (n_reset), .C (control_clk), .D (n_23), .Q
       (data[4]), .QN (UNCONNECTED6));
  DFC3 \data_reg[5] (.RN (n_reset), .C (control_clk), .D (n_22), .Q
       (UNCONNECTED7), .QN (data[5]));
  DFC3 \data_reg[6] (.RN (n_reset), .C (control_clk), .D (n_25), .Q
       (data[6]), .QN (UNCONNECTED8));
  DFP3 \point_add_reg[0] (.SN (n_reset), .C (spi_clk), .D (n_60), .Q
       (point_add[0]), .QN (UNCONNECTED9));
  DFC3 \point_add_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_53), .Q
       (point_add[1]), .QN (UNCONNECTED10));
  DFP3 \point_add_reg[2] (.SN (n_reset), .C (spi_clk), .D (n_72), .Q
       (point_add[2]), .QN (n_0));
  DFC3 \point_add_reg[3] (.RN (n_reset), .C (spi_clk), .D (n_78), .Q
       (point_add[3]), .QN (UNCONNECTED11));
  DFC3 \point_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_68), .Q
       (point[0]), .QN (UNCONNECTED12));
  DFC3 \point_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_69), .Q
       (point[1]), .QN (n_2));
  DFC3 \point_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_70), .Q
       (point[2]), .QN (n_1));
  DFC3 spi_mosi_out_reg(.RN (n_reset), .C (spi_clk), .D (n_81), .Q
       (spi_mosi_out), .QN (UNCONNECTED13));
  AOI310 g1635(.A (n_37), .B (n_40), .C (n_80), .D (spi_cs), .Q (n_81));
  NAND20 g1636(.A (n_79), .B (n_17), .Q (n_80));
  IMUX20 g1638(.A (n_28), .B (n_77), .S (point_add[3]), .Q (n_79));
  NOR20 g1639(.A (n_75), .B (spi_cs), .Q (n_78));
  INV2 g1640(.A (n_76), .Q (n_77));
  OAI2110 g1641(.A (point_add[0]), .B (n_71), .C (n_30), .D (n_12), .Q
       (n_76));
  INV2 g1642(.A (n_74), .Q (n_75));
  OAI220 g1643(.A (n_73), .B (n_17), .C (n_36), .D (n_32), .Q (n_74));
  XNR20 g1649(.A (n_61), .B (point_add[3]), .Q (n_73));
  NOR20 g1653(.A (n_63), .B (spi_cs), .Q (n_72));
  AOI310 g1654(.A (point[2]), .B (control_clk), .C (n_52), .D (n_64),
       .Q (n_71));
  OAI310 g1655(.A (point[2]), .B (n_20), .C (n_51), .D (n_58), .Q
       (n_70));
  OAI220 g1656(.A (spi_cs), .B (n_59), .C (n_51), .D (n_15), .Q (n_69));
  OAI220 g1657(.A (spi_cs), .B (n_57), .C (n_51), .D (point[0]), .Q
       (n_68));
  NOR20 g1659(.A (control[0]), .B (n_55), .Q (n_67));
  NOR20 g1660(.A (n_35), .B (n_55), .Q (n_66));
  NOR20 g1661(.A (n_55), .B (n_56), .Q (n_65));
  AOI2110 g1662(.A (n_46), .B (n_47), .C (point[2]), .D (n_11), .Q
       (n_64));
  INV2 g1663(.A (n_62), .Q (n_63));
  ADD21 g1664(.A (n_43), .B (point_add[2]), .CO (n_61), .S (n_62));
  NOR20 g1666(.A (n_50), .B (spi_cs), .Q (n_60));
  AOI210 g1667(.A (n_49), .B (point[1]), .C (n_16), .Q (n_59));
  OAI2110 g1668(.A (n_20), .B (n_41), .C (n_4), .D (point[2]), .Q
       (n_58));
  AOI220 g1669(.A (n_49), .B (point[0]), .C (n_14), .D (n_11), .Q
       (n_57));
  INV2 g1670(.A (n_54), .Q (n_56));
  ADD21 g1671(.A (n_33), .B (control[2]), .CO (n_55), .S (n_54));
  NOR20 g1672(.A (n_45), .B (spi_cs), .Q (n_53));
  OAI2110 g1673(.A (data[5]), .B (n_15), .C (n_48), .D (n_38), .Q
       (n_52));
  NAND30 g1674(.A (n_4), .B (n_42), .C (control_clk), .Q (n_51));
  IMUX20 g1675(.A (point_add[0]), .B (n_39), .S (n_11), .Q (n_50));
  OAI210 g1676(.A (point[2]), .B (control_clk), .C (n_42), .Q (n_49));
  AOI220 g1677(.A (n_18), .B (data[4]), .C (n_19), .D (spi_mosi_out),
       .Q (n_48));
  AOI220 g1678(.A (n_18), .B (data[0]), .C (n_16), .D (data[2]), .Q
       (n_47));
  AOI220 g1679(.A (n_14), .B (data[1]), .C (n_19), .D (data[3]), .Q
       (n_46));
  INV2 g1680(.A (n_44), .Q (n_45));
  ADD21 g1681(.A (n_13), .B (point_add[1]), .CO (n_43), .S (n_44));
  INV2 g1682(.A (n_42), .Q (n_41));
  NOR20 g1683(.A (point_add[0]), .B (n_32), .Q (n_42));
  NAND20 g1684(.A (n_29), .B (point_add[2]), .Q (n_40));
  NOR20 g1685(.A (point_add[0]), .B (n_31), .Q (n_39));
  NAND20 g1686(.A (n_16), .B (data[6]), .Q (n_38));
  OAI2110 g1687(.A (spi_mosi_out), .B (n_11), .C (point_add[1]), .D
       (n_0), .Q (n_37));
  NOR30 g1688(.A (n_20), .B (n_1), .C (point_add[0]), .Q (n_36));
  INV2 g1689(.A (n_34), .Q (n_35));
  ADD21 g1690(.A (control[0]), .B (control[1]), .CO (n_33), .S (n_34));
  INV2 g1698(.A (n_32), .Q (n_31));
  NAND20 g1699(.A (n_17), .B (point_add[3]), .Q (n_32));
  OAI210 g1700(.A (point_add[0]), .B (n_11), .C (spi_mosi_out), .Q
       (n_30));
  INV2 g1701(.A (n_28), .Q (n_29));
  AOI210 g1702(.A (control_clk), .B (spi_mosi_out), .C (n_13), .Q
       (n_28));
  NOR20 g1703(.A (n_6), .B (spi_cs), .Q (n_27));
  NOR20 g1704(.A (n_9), .B (spi_cs), .Q (n_26));
  NOR20 g1705(.A (n_7), .B (spi_cs), .Q (n_25));
  NOR20 g1706(.A (n_8), .B (spi_cs), .Q (n_24));
  NOR20 g1707(.A (n_3), .B (spi_cs), .Q (n_23));
  NOR20 g1708(.A (n_5), .B (spi_cs), .Q (n_22));
  NOR20 g1709(.A (n_10), .B (spi_cs), .Q (n_21));
  INV2 g1710(.A (n_20), .Q (n_19));
  NAND20 g1711(.A (point[1]), .B (point[0]), .Q (n_20));
  NOR20 g1712(.A (point[1]), .B (point[0]), .Q (n_18));
  NOR20 g1713(.A (point_add[2]), .B (point_add[1]), .Q (n_17));
  NOR20 g1714(.A (point[0]), .B (n_2), .Q (n_16));
  INV2 g1715(.A (n_15), .Q (n_14));
  NAND20 g1716(.A (n_2), .B (point[0]), .Q (n_15));
  CLKIN3 g1717(.A (n_12), .Q (n_13));
  NAND20 g1718(.A (n_11), .B (point_add[0]), .Q (n_12));
  INV2 g1721(.A (spi_mosi_in[1]), .Q (n_10));
  INV2 g1722(.A (spi_mosi_in[3]), .Q (n_9));
  INV2 g1723(.A (spi_mosi_in[2]), .Q (n_8));
  INV2 g1724(.A (spi_mosi_in[6]), .Q (n_7));
  INV2 g1726(.A (spi_mosi_in[0]), .Q (n_6));
  INV2 g1727(.A (spi_mosi_in[5]), .Q (n_5));
  INV2 g1728(.A (spi_cs), .Q (n_4));
  INV2 g1729(.A (spi_mosi_in[4]), .Q (n_3));
endmodule

module spi_final(spi_mosi_out, m_clk, n_reset, data_in, data_av);
  input m_clk, n_reset, data_av;
  input [7:0] data_in;
  output spi_mosi_out;
  wire m_clk, n_reset, data_av;
  wire [7:0] data_in;
  wire spi_mosi_out;
  wire [7:0] spi_mosi_in;
  wire [0:3] A_counter;
  wire [7:0] I1_rdata;
  wire [7:0] \I1_ex_mem[0] ;
  wire [7:0] \I1_ex_mem[10] ;
  wire [7:0] \I1_ex_mem[11] ;
  wire [7:0] \I1_ex_mem[12] ;
  wire [7:0] \I1_ex_mem[13] ;
  wire [7:0] \I1_ex_mem[14] ;
  wire [7:0] \I1_ex_mem[1] ;
  wire [7:0] \I1_ex_mem[2] ;
  wire [7:0] \I1_ex_mem[3] ;
  wire [7:0] \I1_ex_mem[4] ;
  wire [7:0] \I1_ex_mem[5] ;
  wire [7:0] \I1_ex_mem[6] ;
  wire [7:0] \I1_ex_mem[7] ;
  wire [7:0] \I1_ex_mem[8] ;
  wire [7:0] \I1_ex_mem[9] ;
  wire [3:0] I1_r_pointer;
  wire [3:0] I1_w_pointer;
  wire I1_data_en, I1_r_empty, I1_rinc, I1_w_full, I1_winc,
       UNCONNECTED14, UNCONNECTED15, UNCONNECTED16;
  wire UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, UNCONNECTED20,
       UNCONNECTED21, UNCONNECTED22, UNCONNECTED23, UNCONNECTED24;
  wire UNCONNECTED25, UNCONNECTED26, UNCONNECTED27, UNCONNECTED28,
       UNCONNECTED29, UNCONNECTED30, UNCONNECTED31, UNCONNECTED32;
  wire UNCONNECTED33, UNCONNECTED34, UNCONNECTED35, UNCONNECTED36,
       UNCONNECTED37, UNCONNECTED38, UNCONNECTED39, UNCONNECTED40;
  wire UNCONNECTED41, UNCONNECTED42, UNCONNECTED43, UNCONNECTED44,
       UNCONNECTED45, UNCONNECTED46, UNCONNECTED47, UNCONNECTED48;
  wire UNCONNECTED49, UNCONNECTED50, UNCONNECTED51, UNCONNECTED52,
       UNCONNECTED53, UNCONNECTED54, UNCONNECTED55, UNCONNECTED56;
  wire UNCONNECTED57, UNCONNECTED58, UNCONNECTED59, UNCONNECTED60,
       UNCONNECTED61, UNCONNECTED62, UNCONNECTED63, UNCONNECTED64;
  wire UNCONNECTED65, UNCONNECTED66, UNCONNECTED67, UNCONNECTED68,
       UNCONNECTED69, UNCONNECTED70, UNCONNECTED71, UNCONNECTED72;
  wire UNCONNECTED73, UNCONNECTED74, UNCONNECTED75, UNCONNECTED76,
       UNCONNECTED77, UNCONNECTED78, UNCONNECTED79, UNCONNECTED80;
  wire UNCONNECTED81, UNCONNECTED82, UNCONNECTED83, UNCONNECTED84,
       UNCONNECTED85, UNCONNECTED86, UNCONNECTED87, UNCONNECTED88;
  wire UNCONNECTED89, UNCONNECTED90, UNCONNECTED91, UNCONNECTED92,
       UNCONNECTED93, UNCONNECTED94, UNCONNECTED95, UNCONNECTED96;
  wire UNCONNECTED97, UNCONNECTED98, UNCONNECTED99, UNCONNECTED100,
       UNCONNECTED101, UNCONNECTED102, UNCONNECTED103, UNCONNECTED104;
  wire UNCONNECTED105, UNCONNECTED106, UNCONNECTED107, UNCONNECTED108,
       UNCONNECTED109, UNCONNECTED110, UNCONNECTED111, UNCONNECTED112;
  wire UNCONNECTED113, UNCONNECTED114, UNCONNECTED115, UNCONNECTED116,
       UNCONNECTED117, UNCONNECTED118, UNCONNECTED119, UNCONNECTED120;
  wire UNCONNECTED121, UNCONNECTED122, UNCONNECTED123, UNCONNECTED124,
       UNCONNECTED125, UNCONNECTED126, UNCONNECTED127, UNCONNECTED128;
  wire UNCONNECTED129, UNCONNECTED130, UNCONNECTED131, UNCONNECTED132,
       UNCONNECTED133, UNCONNECTED134, UNCONNECTED135, UNCONNECTED136;
  wire UNCONNECTED137, UNCONNECTED138, UNCONNECTED139, control_clk,
       n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_223, n_224, spi_clk, spi_cs;
  spi_mosi I2(.control_clk (control_clk), .spi_mosi_out (spi_mosi_out),
       .spi_cs (spi_cs), .spi_clk (spi_clk), .n_reset (n_reset),
       .spi_mosi_in ({1'b0, spi_mosi_in[6:0]}));
  DFC3 \A_counter_reg[0] (.RN (n_reset), .C (m_clk), .D (n_156), .Q
       (A_counter[0]), .QN (n_11));
  TFSC1 \A_counter_reg[1] (.RN (n_reset), .C (m_clk), .SD
       (A_counter[1]), .SE (n_47), .Q (A_counter[1]), .QN
       (UNCONNECTED14));
  JKC3 \A_counter_reg[2] (.RN (n_reset), .C (m_clk), .J (n_43), .K
       (n_25), .Q (A_counter[2]), .QN (UNCONNECTED15));
  TFSC1 \A_counter_reg[3] (.RN (n_reset), .C (m_clk), .SD
       (A_counter[3]), .SE (spi_cs), .Q (A_counter[3]), .QN
       (UNCONNECTED16));
  TFEC3 A_spi_clk_reg(.RN (n_reset), .C (m_clk), .T (n_49), .Q
       (spi_clk), .QN (UNCONNECTED17));
  DFC3 I1_data_en_reg(.RN (n_reset), .C (data_av), .D (n_13), .Q
       (I1_data_en), .QN (UNCONNECTED18));
  DFEC1 \I1_data_to_mosi_reg[0] (.RN (n_reset), .C (control_clk), .D
       (I1_rdata[0]), .E (n_96), .Q (spi_mosi_in[0]), .QN
       (UNCONNECTED19));
  DFEC1 \I1_data_to_mosi_reg[1] (.RN (n_reset), .C (control_clk), .D
       (I1_rdata[1]), .E (n_96), .Q (spi_mosi_in[1]), .QN
       (UNCONNECTED20));
  DFEC1 \I1_data_to_mosi_reg[2] (.RN (n_reset), .C (control_clk), .D
       (I1_rdata[2]), .E (n_96), .Q (spi_mosi_in[2]), .QN
       (UNCONNECTED21));
  DFEC1 \I1_data_to_mosi_reg[3] (.RN (n_reset), .C (control_clk), .D
       (I1_rdata[3]), .E (n_96), .Q (spi_mosi_in[3]), .QN
       (UNCONNECTED22));
  DFEC1 \I1_data_to_mosi_reg[4] (.RN (n_reset), .C (control_clk), .D
       (I1_rdata[4]), .E (n_96), .Q (spi_mosi_in[4]), .QN
       (UNCONNECTED23));
  DFEC1 \I1_data_to_mosi_reg[5] (.RN (n_reset), .C (control_clk), .D
       (I1_rdata[5]), .E (n_96), .Q (spi_mosi_in[5]), .QN
       (UNCONNECTED24));
  DFEC1 \I1_data_to_mosi_reg[6] (.RN (n_reset), .C (control_clk), .D
       (I1_rdata[6]), .E (n_96), .Q (spi_mosi_in[6]), .QN
       (UNCONNECTED25));
  DFE1 \I1_ex_mem_reg[0][0] (.C (m_clk), .D (data_in[0]), .E (n_192),
       .Q (\I1_ex_mem[0] [0]), .QN (UNCONNECTED26));
  DFE1 \I1_ex_mem_reg[0][1] (.C (m_clk), .D (data_in[1]), .E (n_192),
       .Q (\I1_ex_mem[0] [1]), .QN (UNCONNECTED27));
  DFE1 \I1_ex_mem_reg[0][2] (.C (m_clk), .D (data_in[2]), .E (n_192),
       .Q (\I1_ex_mem[0] [2]), .QN (UNCONNECTED28));
  DFE1 \I1_ex_mem_reg[0][3] (.C (m_clk), .D (data_in[3]), .E (n_192),
       .Q (\I1_ex_mem[0] [3]), .QN (UNCONNECTED29));
  DFE1 \I1_ex_mem_reg[0][4] (.C (m_clk), .D (data_in[4]), .E (n_192),
       .Q (\I1_ex_mem[0] [4]), .QN (UNCONNECTED30));
  DFE1 \I1_ex_mem_reg[0][5] (.C (m_clk), .D (data_in[5]), .E (n_192),
       .Q (\I1_ex_mem[0] [5]), .QN (UNCONNECTED31));
  DFE1 \I1_ex_mem_reg[0][6] (.C (m_clk), .D (data_in[6]), .E (n_192),
       .Q (\I1_ex_mem[0] [6]), .QN (UNCONNECTED32));
  DFE1 \I1_ex_mem_reg[10][0] (.C (m_clk), .D (data_in[0]), .E (n_193),
       .Q (\I1_ex_mem[10] [0]), .QN (UNCONNECTED33));
  DFE1 \I1_ex_mem_reg[10][1] (.C (m_clk), .D (data_in[1]), .E (n_193),
       .Q (\I1_ex_mem[10] [1]), .QN (UNCONNECTED34));
  DFE1 \I1_ex_mem_reg[10][2] (.C (m_clk), .D (data_in[2]), .E (n_193),
       .Q (\I1_ex_mem[10] [2]), .QN (UNCONNECTED35));
  DFE1 \I1_ex_mem_reg[10][3] (.C (m_clk), .D (data_in[3]), .E (n_193),
       .Q (\I1_ex_mem[10] [3]), .QN (UNCONNECTED36));
  DFE1 \I1_ex_mem_reg[10][4] (.C (m_clk), .D (data_in[4]), .E (n_193),
       .Q (\I1_ex_mem[10] [4]), .QN (UNCONNECTED37));
  DFE1 \I1_ex_mem_reg[10][5] (.C (m_clk), .D (data_in[5]), .E (n_193),
       .Q (\I1_ex_mem[10] [5]), .QN (UNCONNECTED38));
  DFE1 \I1_ex_mem_reg[10][6] (.C (m_clk), .D (data_in[6]), .E (n_193),
       .Q (\I1_ex_mem[10] [6]), .QN (UNCONNECTED39));
  DFE1 \I1_ex_mem_reg[11][0] (.C (m_clk), .D (data_in[0]), .E (n_182),
       .Q (\I1_ex_mem[11] [0]), .QN (UNCONNECTED40));
  DFE1 \I1_ex_mem_reg[11][1] (.C (m_clk), .D (data_in[1]), .E (n_182),
       .Q (\I1_ex_mem[11] [1]), .QN (UNCONNECTED41));
  DFE1 \I1_ex_mem_reg[11][2] (.C (m_clk), .D (data_in[2]), .E (n_182),
       .Q (\I1_ex_mem[11] [2]), .QN (UNCONNECTED42));
  DFE1 \I1_ex_mem_reg[11][3] (.C (m_clk), .D (data_in[3]), .E (n_182),
       .Q (\I1_ex_mem[11] [3]), .QN (UNCONNECTED43));
  DFE1 \I1_ex_mem_reg[11][4] (.C (m_clk), .D (data_in[4]), .E (n_182),
       .Q (\I1_ex_mem[11] [4]), .QN (UNCONNECTED44));
  DFE1 \I1_ex_mem_reg[11][5] (.C (m_clk), .D (data_in[5]), .E (n_182),
       .Q (\I1_ex_mem[11] [5]), .QN (UNCONNECTED45));
  DFE1 \I1_ex_mem_reg[11][6] (.C (m_clk), .D (data_in[6]), .E (n_182),
       .Q (\I1_ex_mem[11] [6]), .QN (UNCONNECTED46));
  DFE1 \I1_ex_mem_reg[12][0] (.C (m_clk), .D (data_in[0]), .E (n_191),
       .Q (\I1_ex_mem[12] [0]), .QN (UNCONNECTED47));
  DFE1 \I1_ex_mem_reg[12][1] (.C (m_clk), .D (data_in[1]), .E (n_191),
       .Q (\I1_ex_mem[12] [1]), .QN (UNCONNECTED48));
  DFE1 \I1_ex_mem_reg[12][2] (.C (m_clk), .D (data_in[2]), .E (n_191),
       .Q (\I1_ex_mem[12] [2]), .QN (UNCONNECTED49));
  DFE1 \I1_ex_mem_reg[12][3] (.C (m_clk), .D (data_in[3]), .E (n_191),
       .Q (\I1_ex_mem[12] [3]), .QN (UNCONNECTED50));
  DFE1 \I1_ex_mem_reg[12][4] (.C (m_clk), .D (data_in[4]), .E (n_191),
       .Q (\I1_ex_mem[12] [4]), .QN (UNCONNECTED51));
  DFE1 \I1_ex_mem_reg[12][5] (.C (m_clk), .D (data_in[5]), .E (n_191),
       .Q (\I1_ex_mem[12] [5]), .QN (UNCONNECTED52));
  DFE1 \I1_ex_mem_reg[12][6] (.C (m_clk), .D (data_in[6]), .E (n_191),
       .Q (\I1_ex_mem[12] [6]), .QN (UNCONNECTED53));
  DFE1 \I1_ex_mem_reg[13][0] (.C (m_clk), .D (data_in[0]), .E (n_181),
       .Q (\I1_ex_mem[13] [0]), .QN (UNCONNECTED54));
  DFE1 \I1_ex_mem_reg[13][1] (.C (m_clk), .D (data_in[1]), .E (n_181),
       .Q (\I1_ex_mem[13] [1]), .QN (UNCONNECTED55));
  DFE1 \I1_ex_mem_reg[13][2] (.C (m_clk), .D (data_in[2]), .E (n_181),
       .Q (\I1_ex_mem[13] [2]), .QN (UNCONNECTED56));
  DFE1 \I1_ex_mem_reg[13][3] (.C (m_clk), .D (data_in[3]), .E (n_181),
       .Q (\I1_ex_mem[13] [3]), .QN (UNCONNECTED57));
  DFE1 \I1_ex_mem_reg[13][4] (.C (m_clk), .D (data_in[4]), .E (n_181),
       .Q (\I1_ex_mem[13] [4]), .QN (UNCONNECTED58));
  DFE1 \I1_ex_mem_reg[13][5] (.C (m_clk), .D (data_in[5]), .E (n_181),
       .Q (\I1_ex_mem[13] [5]), .QN (UNCONNECTED59));
  DFE1 \I1_ex_mem_reg[13][6] (.C (m_clk), .D (data_in[6]), .E (n_181),
       .Q (\I1_ex_mem[13] [6]), .QN (UNCONNECTED60));
  DFE1 \I1_ex_mem_reg[14][0] (.C (m_clk), .D (data_in[0]), .E (n_184),
       .Q (\I1_ex_mem[14] [0]), .QN (UNCONNECTED61));
  DFE1 \I1_ex_mem_reg[14][1] (.C (m_clk), .D (data_in[1]), .E (n_184),
       .Q (\I1_ex_mem[14] [1]), .QN (UNCONNECTED62));
  DFE1 \I1_ex_mem_reg[14][2] (.C (m_clk), .D (data_in[2]), .E (n_184),
       .Q (\I1_ex_mem[14] [2]), .QN (UNCONNECTED63));
  DFE1 \I1_ex_mem_reg[14][3] (.C (m_clk), .D (data_in[3]), .E (n_184),
       .Q (\I1_ex_mem[14] [3]), .QN (UNCONNECTED64));
  DFE1 \I1_ex_mem_reg[14][4] (.C (m_clk), .D (data_in[4]), .E (n_184),
       .Q (\I1_ex_mem[14] [4]), .QN (UNCONNECTED65));
  DFE1 \I1_ex_mem_reg[14][5] (.C (m_clk), .D (data_in[5]), .E (n_184),
       .Q (\I1_ex_mem[14] [5]), .QN (UNCONNECTED66));
  DFE1 \I1_ex_mem_reg[14][6] (.C (m_clk), .D (data_in[6]), .E (n_184),
       .Q (\I1_ex_mem[14] [6]), .QN (UNCONNECTED67));
  DFE1 \I1_ex_mem_reg[1][0] (.C (m_clk), .D (data_in[0]), .E (n_179),
       .Q (\I1_ex_mem[1] [0]), .QN (UNCONNECTED68));
  DFE1 \I1_ex_mem_reg[1][1] (.C (m_clk), .D (data_in[1]), .E (n_179),
       .Q (\I1_ex_mem[1] [1]), .QN (UNCONNECTED69));
  DFE1 \I1_ex_mem_reg[1][2] (.C (m_clk), .D (data_in[2]), .E (n_179),
       .Q (\I1_ex_mem[1] [2]), .QN (UNCONNECTED70));
  DFE1 \I1_ex_mem_reg[1][3] (.C (m_clk), .D (data_in[3]), .E (n_179),
       .Q (\I1_ex_mem[1] [3]), .QN (UNCONNECTED71));
  DFE1 \I1_ex_mem_reg[1][4] (.C (m_clk), .D (data_in[4]), .E (n_179),
       .Q (\I1_ex_mem[1] [4]), .QN (UNCONNECTED72));
  DFE1 \I1_ex_mem_reg[1][5] (.C (m_clk), .D (data_in[5]), .E (n_179),
       .Q (\I1_ex_mem[1] [5]), .QN (UNCONNECTED73));
  DFE1 \I1_ex_mem_reg[1][6] (.C (m_clk), .D (data_in[6]), .E (n_179),
       .Q (\I1_ex_mem[1] [6]), .QN (UNCONNECTED74));
  DFE1 \I1_ex_mem_reg[2][0] (.C (m_clk), .D (data_in[0]), .E (n_190),
       .Q (\I1_ex_mem[2] [0]), .QN (UNCONNECTED75));
  DFE1 \I1_ex_mem_reg[2][1] (.C (m_clk), .D (data_in[1]), .E (n_190),
       .Q (\I1_ex_mem[2] [1]), .QN (UNCONNECTED76));
  DFE1 \I1_ex_mem_reg[2][2] (.C (m_clk), .D (data_in[2]), .E (n_190),
       .Q (\I1_ex_mem[2] [2]), .QN (UNCONNECTED77));
  DFE1 \I1_ex_mem_reg[2][3] (.C (m_clk), .D (data_in[3]), .E (n_190),
       .Q (\I1_ex_mem[2] [3]), .QN (UNCONNECTED78));
  DFE1 \I1_ex_mem_reg[2][4] (.C (m_clk), .D (data_in[4]), .E (n_190),
       .Q (\I1_ex_mem[2] [4]), .QN (UNCONNECTED79));
  DFE1 \I1_ex_mem_reg[2][5] (.C (m_clk), .D (data_in[5]), .E (n_190),
       .Q (\I1_ex_mem[2] [5]), .QN (UNCONNECTED80));
  DFE1 \I1_ex_mem_reg[2][6] (.C (m_clk), .D (data_in[6]), .E (n_190),
       .Q (\I1_ex_mem[2] [6]), .QN (UNCONNECTED81));
  DFE1 \I1_ex_mem_reg[3][0] (.C (m_clk), .D (data_in[0]), .E (n_177),
       .Q (\I1_ex_mem[3] [0]), .QN (UNCONNECTED82));
  DFE1 \I1_ex_mem_reg[3][1] (.C (m_clk), .D (data_in[1]), .E (n_177),
       .Q (\I1_ex_mem[3] [1]), .QN (UNCONNECTED83));
  DFE1 \I1_ex_mem_reg[3][2] (.C (m_clk), .D (data_in[2]), .E (n_177),
       .Q (\I1_ex_mem[3] [2]), .QN (UNCONNECTED84));
  DFE1 \I1_ex_mem_reg[3][3] (.C (m_clk), .D (data_in[3]), .E (n_177),
       .Q (\I1_ex_mem[3] [3]), .QN (UNCONNECTED85));
  DFE1 \I1_ex_mem_reg[3][4] (.C (m_clk), .D (data_in[4]), .E (n_177),
       .Q (\I1_ex_mem[3] [4]), .QN (UNCONNECTED86));
  DFE1 \I1_ex_mem_reg[3][5] (.C (m_clk), .D (data_in[5]), .E (n_177),
       .Q (\I1_ex_mem[3] [5]), .QN (UNCONNECTED87));
  DFE1 \I1_ex_mem_reg[3][6] (.C (m_clk), .D (data_in[6]), .E (n_177),
       .Q (\I1_ex_mem[3] [6]), .QN (UNCONNECTED88));
  DFE1 \I1_ex_mem_reg[4][0] (.C (m_clk), .D (data_in[0]), .E (n_189),
       .Q (\I1_ex_mem[4] [0]), .QN (UNCONNECTED89));
  DFE1 \I1_ex_mem_reg[4][1] (.C (m_clk), .D (data_in[1]), .E (n_189),
       .Q (\I1_ex_mem[4] [1]), .QN (UNCONNECTED90));
  DFE1 \I1_ex_mem_reg[4][2] (.C (m_clk), .D (data_in[2]), .E (n_189),
       .Q (\I1_ex_mem[4] [2]), .QN (UNCONNECTED91));
  DFE1 \I1_ex_mem_reg[4][3] (.C (m_clk), .D (data_in[3]), .E (n_189),
       .Q (\I1_ex_mem[4] [3]), .QN (UNCONNECTED92));
  DFE1 \I1_ex_mem_reg[4][4] (.C (m_clk), .D (data_in[4]), .E (n_189),
       .Q (\I1_ex_mem[4] [4]), .QN (UNCONNECTED93));
  DFE1 \I1_ex_mem_reg[4][5] (.C (m_clk), .D (data_in[5]), .E (n_189),
       .Q (\I1_ex_mem[4] [5]), .QN (UNCONNECTED94));
  DFE1 \I1_ex_mem_reg[4][6] (.C (m_clk), .D (data_in[6]), .E (n_189),
       .Q (\I1_ex_mem[4] [6]), .QN (UNCONNECTED95));
  DFE1 \I1_ex_mem_reg[5][0] (.C (m_clk), .D (data_in[0]), .E (n_176),
       .Q (\I1_ex_mem[5] [0]), .QN (UNCONNECTED96));
  DFE1 \I1_ex_mem_reg[5][1] (.C (m_clk), .D (data_in[1]), .E (n_176),
       .Q (\I1_ex_mem[5] [1]), .QN (UNCONNECTED97));
  DFE1 \I1_ex_mem_reg[5][2] (.C (m_clk), .D (data_in[2]), .E (n_176),
       .Q (\I1_ex_mem[5] [2]), .QN (UNCONNECTED98));
  DFE1 \I1_ex_mem_reg[5][3] (.C (m_clk), .D (data_in[3]), .E (n_176),
       .Q (\I1_ex_mem[5] [3]), .QN (UNCONNECTED99));
  DFE1 \I1_ex_mem_reg[5][4] (.C (m_clk), .D (data_in[4]), .E (n_176),
       .Q (\I1_ex_mem[5] [4]), .QN (UNCONNECTED100));
  DFE1 \I1_ex_mem_reg[5][5] (.C (m_clk), .D (data_in[5]), .E (n_176),
       .Q (\I1_ex_mem[5] [5]), .QN (UNCONNECTED101));
  DFE1 \I1_ex_mem_reg[5][6] (.C (m_clk), .D (data_in[6]), .E (n_176),
       .Q (\I1_ex_mem[5] [6]), .QN (UNCONNECTED102));
  DFE1 \I1_ex_mem_reg[6][0] (.C (m_clk), .D (data_in[0]), .E (n_195),
       .Q (\I1_ex_mem[6] [0]), .QN (UNCONNECTED103));
  DFE1 \I1_ex_mem_reg[6][1] (.C (m_clk), .D (data_in[1]), .E (n_195),
       .Q (\I1_ex_mem[6] [1]), .QN (UNCONNECTED104));
  DFE1 \I1_ex_mem_reg[6][2] (.C (m_clk), .D (data_in[2]), .E (n_195),
       .Q (\I1_ex_mem[6] [2]), .QN (UNCONNECTED105));
  DFE1 \I1_ex_mem_reg[6][3] (.C (m_clk), .D (data_in[3]), .E (n_195),
       .Q (\I1_ex_mem[6] [3]), .QN (UNCONNECTED106));
  DFE1 \I1_ex_mem_reg[6][4] (.C (m_clk), .D (data_in[4]), .E (n_195),
       .Q (\I1_ex_mem[6] [4]), .QN (UNCONNECTED107));
  DFE1 \I1_ex_mem_reg[6][5] (.C (m_clk), .D (data_in[5]), .E (n_195),
       .Q (\I1_ex_mem[6] [5]), .QN (UNCONNECTED108));
  DFE1 \I1_ex_mem_reg[6][6] (.C (m_clk), .D (data_in[6]), .E (n_195),
       .Q (\I1_ex_mem[6] [6]), .QN (UNCONNECTED109));
  DFE1 \I1_ex_mem_reg[7][0] (.C (m_clk), .D (data_in[0]), .E (n_178),
       .Q (\I1_ex_mem[7] [0]), .QN (UNCONNECTED110));
  DFE1 \I1_ex_mem_reg[7][1] (.C (m_clk), .D (data_in[1]), .E (n_178),
       .Q (\I1_ex_mem[7] [1]), .QN (UNCONNECTED111));
  DFE1 \I1_ex_mem_reg[7][2] (.C (m_clk), .D (data_in[2]), .E (n_178),
       .Q (\I1_ex_mem[7] [2]), .QN (UNCONNECTED112));
  DFE1 \I1_ex_mem_reg[7][3] (.C (m_clk), .D (data_in[3]), .E (n_178),
       .Q (\I1_ex_mem[7] [3]), .QN (UNCONNECTED113));
  DFE1 \I1_ex_mem_reg[7][4] (.C (m_clk), .D (data_in[4]), .E (n_178),
       .Q (\I1_ex_mem[7] [4]), .QN (UNCONNECTED114));
  DFE1 \I1_ex_mem_reg[7][5] (.C (m_clk), .D (data_in[5]), .E (n_178),
       .Q (\I1_ex_mem[7] [5]), .QN (UNCONNECTED115));
  DFE1 \I1_ex_mem_reg[7][6] (.C (m_clk), .D (data_in[6]), .E (n_178),
       .Q (\I1_ex_mem[7] [6]), .QN (UNCONNECTED116));
  DFE1 \I1_ex_mem_reg[8][0] (.C (m_clk), .D (data_in[0]), .E (n_194),
       .Q (\I1_ex_mem[8] [0]), .QN (UNCONNECTED117));
  DFE1 \I1_ex_mem_reg[8][1] (.C (m_clk), .D (data_in[1]), .E (n_194),
       .Q (\I1_ex_mem[8] [1]), .QN (UNCONNECTED118));
  DFE1 \I1_ex_mem_reg[8][2] (.C (m_clk), .D (data_in[2]), .E (n_194),
       .Q (\I1_ex_mem[8] [2]), .QN (UNCONNECTED119));
  DFE1 \I1_ex_mem_reg[8][3] (.C (m_clk), .D (data_in[3]), .E (n_194),
       .Q (\I1_ex_mem[8] [3]), .QN (UNCONNECTED120));
  DFE1 \I1_ex_mem_reg[8][4] (.C (m_clk), .D (data_in[4]), .E (n_194),
       .Q (\I1_ex_mem[8] [4]), .QN (UNCONNECTED121));
  DFE1 \I1_ex_mem_reg[8][5] (.C (m_clk), .D (data_in[5]), .E (n_194),
       .Q (\I1_ex_mem[8] [5]), .QN (UNCONNECTED122));
  DFE1 \I1_ex_mem_reg[8][6] (.C (m_clk), .D (data_in[6]), .E (n_194),
       .Q (\I1_ex_mem[8] [6]), .QN (UNCONNECTED123));
  DFE1 \I1_ex_mem_reg[9][0] (.C (m_clk), .D (data_in[0]), .E (n_180),
       .Q (\I1_ex_mem[9] [0]), .QN (UNCONNECTED124));
  DFE1 \I1_ex_mem_reg[9][1] (.C (m_clk), .D (data_in[1]), .E (n_180),
       .Q (\I1_ex_mem[9] [1]), .QN (UNCONNECTED125));
  DFE1 \I1_ex_mem_reg[9][2] (.C (m_clk), .D (data_in[2]), .E (n_180),
       .Q (\I1_ex_mem[9] [2]), .QN (UNCONNECTED126));
  DFE1 \I1_ex_mem_reg[9][3] (.C (m_clk), .D (data_in[3]), .E (n_180),
       .Q (\I1_ex_mem[9] [3]), .QN (UNCONNECTED127));
  DFE1 \I1_ex_mem_reg[9][4] (.C (m_clk), .D (data_in[4]), .E (n_180),
       .Q (\I1_ex_mem[9] [4]), .QN (UNCONNECTED128));
  DFE1 \I1_ex_mem_reg[9][5] (.C (m_clk), .D (data_in[5]), .E (n_180),
       .Q (\I1_ex_mem[9] [5]), .QN (UNCONNECTED129));
  DFE1 \I1_ex_mem_reg[9][6] (.C (m_clk), .D (data_in[6]), .E (n_180),
       .Q (\I1_ex_mem[9] [6]), .QN (UNCONNECTED130));
  DFP3 I1_r_empty_reg(.SN (n_reset), .C (control_clk), .D (n_155), .Q
       (I1_r_empty), .QN (n_6));
  DFC3 \I1_r_pointer_reg[0] (.RN (n_reset), .C (control_clk), .D
       (n_159), .Q (I1_r_pointer[0]), .QN (n_2));
  DFC3 \I1_r_pointer_reg[1] (.RN (n_reset), .C (control_clk), .D
       (n_158), .Q (I1_r_pointer[1]), .QN (n_12));
  DFC3 \I1_r_pointer_reg[2] (.RN (n_reset), .C (control_clk), .D
       (n_157), .Q (I1_r_pointer[2]), .QN (n_0));
  DFC3 \I1_r_pointer_reg[3] (.RN (n_reset), .C (control_clk), .D
       (n_170), .Q (I1_r_pointer[3]), .QN (n_7));
  DFC3 \I1_rdata_reg[0] (.RN (n_reset), .C (control_clk), .D (n_208),
       .Q (I1_rdata[0]), .QN (UNCONNECTED131));
  DFC3 \I1_rdata_reg[1] (.RN (n_reset), .C (control_clk), .D (n_207),
       .Q (I1_rdata[1]), .QN (UNCONNECTED132));
  DFC3 \I1_rdata_reg[2] (.RN (n_reset), .C (control_clk), .D (n_206),
       .Q (I1_rdata[2]), .QN (n_1));
  DFC3 \I1_rdata_reg[3] (.RN (n_reset), .C (control_clk), .D (n_204),
       .Q (I1_rdata[3]), .QN (UNCONNECTED133));
  DFC3 \I1_rdata_reg[4] (.RN (n_reset), .C (control_clk), .D (n_205),
       .Q (I1_rdata[4]), .QN (UNCONNECTED134));
  DFC3 \I1_rdata_reg[5] (.RN (n_reset), .C (control_clk), .D (n_209),
       .Q (I1_rdata[5]), .QN (UNCONNECTED135));
  DFC3 \I1_rdata_reg[6] (.RN (n_reset), .C (control_clk), .D (n_203),
       .Q (I1_rdata[6]), .QN (UNCONNECTED136));
  DFC3 I1_rinc_reg(.RN (n_reset), .C (m_clk), .D (n_34), .Q (I1_rinc),
       .QN (UNCONNECTED137));
  DFC3 I1_spi_cs_reg(.RN (n_reset), .C (m_clk), .D (n_19), .Q (spi_cs),
       .QN (UNCONNECTED138));
  DFEC1 I1_w_full_reg(.RN (n_reset), .C (m_clk), .D (n_29), .E (n_59),
       .Q (I1_w_full), .QN (n_5));
  DFC3 \I1_w_pointer_reg[0] (.RN (n_reset), .C (m_clk), .D (n_71), .Q
       (I1_w_pointer[0]), .QN (UNCONNECTED139));
  JKC3 \I1_w_pointer_reg[1] (.RN (n_reset), .C (m_clk), .J (n_64), .K
       (n_72), .Q (I1_w_pointer[1]), .QN (n_9));
  DFC3 \I1_w_pointer_reg[2] (.RN (n_reset), .C (m_clk), .D (n_154), .Q
       (I1_w_pointer[2]), .QN (n_10));
  JKC3 \I1_w_pointer_reg[3] (.RN (n_reset), .C (m_clk), .J (n_85), .K
       (n_65), .Q (I1_w_pointer[3]), .QN (n_8));
  DFC3 I1_winc_reg(.RN (n_reset), .C (m_clk), .D (n_223), .Q (I1_winc),
       .QN (n_38));
  NAND40 g5431(.A (n_200), .B (n_146), .C (n_121), .D (n_120), .Q
       (n_209));
  NAND40 g5432(.A (n_202), .B (n_145), .C (n_144), .D (n_143), .Q
       (n_208));
  NAND40 g5433(.A (n_201), .B (n_151), .C (n_139), .D (n_138), .Q
       (n_207));
  NAND40 g5483(.A (n_198), .B (n_134), .C (n_132), .D (n_133), .Q
       (n_206));
  NAND40 g5484(.A (n_196), .B (n_163), .C (n_149), .D (n_124), .Q
       (n_205));
  NAND40 g5485(.A (n_197), .B (n_153), .C (n_128), .D (n_127), .Q
       (n_204));
  NAND40 g5486(.A (n_199), .B (n_162), .C (n_125), .D (n_117), .Q
       (n_203));
  AOI2110 g5543(.A (n_79), .B (\I1_ex_mem[9] [0]), .C (n_108), .D
       (n_188), .Q (n_202));
  AOI2110 g5544(.A (n_74), .B (\I1_ex_mem[1] [1]), .C (n_100), .D
       (n_187), .Q (n_201));
  AOI2110 g5545(.A (n_80), .B (\I1_ex_mem[8] [5]), .C (n_106), .D
       (n_186), .Q (n_200));
  AOI2110 g5546(.A (n_75), .B (\I1_ex_mem[14] [6]), .C (n_98), .D
       (n_172), .Q (n_199));
  AOI2110 g5547(.A (n_80), .B (\I1_ex_mem[8] [2]), .C (n_161), .D
       (n_175), .Q (n_198));
  AOI2110 g5548(.A (n_95), .B (I1_rdata[3]), .C (n_102), .D (n_174), .Q
       (n_197));
  AOI2110 g5549(.A (n_76), .B (\I1_ex_mem[13] [4]), .C (n_104), .D
       (n_173), .Q (n_196));
  NOR21 g5550(.A (n_183), .B (n_21), .Q (n_195));
  NOR21 g5551(.A (n_185), .B (n_20), .Q (n_194));
  NOR21 g5552(.A (n_185), .B (n_14), .Q (n_193));
  NOR21 g5553(.A (n_183), .B (n_20), .Q (n_192));
  NOR21 g5554(.A (n_185), .B (n_16), .Q (n_191));
  NOR21 g5555(.A (n_183), .B (n_14), .Q (n_190));
  NOR21 g5556(.A (n_183), .B (n_16), .Q (n_189));
  NAND40 g5557(.A (n_165), .B (n_140), .C (n_141), .D (n_142), .Q
       (n_188));
  NAND40 g5558(.A (n_164), .B (n_135), .C (n_136), .D (n_137), .Q
       (n_187));
  NAND40 g5559(.A (n_166), .B (n_118), .C (n_150), .D (n_119), .Q
       (n_186));
  NAND22 g5568(.A (I1_w_pointer[3]), .B (n_167), .Q (n_185));
  NOR21 g5569(.A (n_168), .B (n_33), .Q (n_184));
  NAND22 g5570(.A (n_8), .B (n_167), .Q (n_183));
  NOR21 g5571(.A (n_171), .B (n_14), .Q (n_182));
  NOR21 g5572(.A (n_171), .B (n_16), .Q (n_181));
  NOR21 g5573(.A (n_171), .B (n_20), .Q (n_180));
  NOR21 g5574(.A (n_169), .B (n_20), .Q (n_179));
  NOR21 g5575(.A (n_169), .B (n_21), .Q (n_178));
  NOR21 g5576(.A (n_169), .B (n_14), .Q (n_177));
  NOR21 g5577(.A (n_169), .B (n_16), .Q (n_176));
  NAND40 g5578(.A (n_129), .B (n_148), .C (n_130), .D (n_152), .Q
       (n_175));
  NAND40 g5579(.A (n_147), .B (n_116), .C (n_126), .D (n_131), .Q
       (n_174));
  NAND40 g5580(.A (n_122), .B (n_110), .C (n_123), .D (n_115), .Q
       (n_173));
  NAND40 g5581(.A (n_112), .B (n_111), .C (n_113), .D (n_114), .Q
       (n_172));
  NAND22 g5590(.A (I1_w_pointer[3]), .B (n_160), .Q (n_171));
  NOR20 g5591(.A (n_94), .B (n_109), .Q (n_170));
  NAND22 g5592(.A (n_8), .B (n_160), .Q (n_169));
  INV2 g5593(.A (n_167), .Q (n_168));
  NOR31 g5594(.A (I1_w_pointer[0]), .B (n_92), .C (n_38), .Q (n_167));
  AOI220 g5595(.A (n_88), .B (\I1_ex_mem[11] [5]), .C (n_95), .D
       (I1_rdata[5]), .Q (n_166));
  AOI220 g5596(.A (n_82), .B (\I1_ex_mem[5] [0]), .C (n_95), .D
       (I1_rdata[0]), .Q (n_165));
  AOI220 g5597(.A (n_75), .B (\I1_ex_mem[14] [1]), .C (n_95), .D
       (I1_rdata[1]), .Q (n_164));
  AOI220 g5598(.A (n_80), .B (\I1_ex_mem[8] [4]), .C (n_95), .D
       (I1_rdata[4]), .Q (n_163));
  AOI220 g5599(.A (n_88), .B (\I1_ex_mem[11] [6]), .C (n_95), .D
       (I1_rdata[6]), .Q (n_162));
  NOR20 g5601(.A (n_1), .B (n_96), .Q (n_161));
  NOR21 g5602(.A (n_92), .B (n_48), .Q (n_160));
  NOR20 g5603(.A (n_55), .B (n_94), .Q (n_159));
  NOR20 g5604(.A (n_57), .B (n_94), .Q (n_158));
  NOR20 g5605(.A (n_56), .B (n_94), .Q (n_157));
  OAI212 g5606(.A (n_25), .B (n_11), .C (n_89), .Q (n_156));
  OAI210 g5607(.A (n_6), .B (n_224), .C (n_93), .Q (n_155));
  NAND22 g5608(.A (n_16), .B (n_90), .Q (n_154));
  AOI220 g5609(.A (n_87), .B (\I1_ex_mem[12] [3]), .C (n_75), .D
       (\I1_ex_mem[14] [3]), .Q (n_153));
  AOI220 g5610(.A (n_77), .B (\I1_ex_mem[3] [2]), .C (n_82), .D
       (\I1_ex_mem[5] [2]), .Q (n_152));
  AOI220 g5611(.A (n_80), .B (\I1_ex_mem[8] [1]), .C (n_86), .D
       (\I1_ex_mem[4] [1]), .Q (n_151));
  AOI220 g5612(.A (n_74), .B (\I1_ex_mem[1] [5]), .C (n_83), .D
       (\I1_ex_mem[10] [5]), .Q (n_150));
  AOI220 g5613(.A (n_77), .B (\I1_ex_mem[3] [4]), .C (n_79), .D
       (\I1_ex_mem[9] [4]), .Q (n_149));
  AOI220 g5614(.A (n_81), .B (\I1_ex_mem[6] [2]), .C (n_78), .D
       (\I1_ex_mem[7] [2]), .Q (n_148));
  AOI220 g5615(.A (n_73), .B (\I1_ex_mem[2] [3]), .C (n_79), .D
       (\I1_ex_mem[9] [3]), .Q (n_147));
  AOI220 g5616(.A (n_86), .B (\I1_ex_mem[4] [5]), .C (n_81), .D
       (\I1_ex_mem[6] [5]), .Q (n_146));
  AOI220 g5617(.A (n_88), .B (\I1_ex_mem[11] [0]), .C (n_78), .D
       (\I1_ex_mem[7] [0]), .Q (n_145));
  AOI220 g5618(.A (n_87), .B (\I1_ex_mem[12] [0]), .C (n_75), .D
       (\I1_ex_mem[14] [0]), .Q (n_144));
  AOI220 g5619(.A (n_73), .B (\I1_ex_mem[2] [0]), .C (n_81), .D
       (\I1_ex_mem[6] [0]), .Q (n_143));
  AOI220 g5620(.A (n_80), .B (\I1_ex_mem[8] [0]), .C (n_76), .D
       (\I1_ex_mem[13] [0]), .Q (n_142));
  AOI220 g5621(.A (n_74), .B (\I1_ex_mem[1] [0]), .C (n_83), .D
       (\I1_ex_mem[10] [0]), .Q (n_141));
  AOI220 g5622(.A (n_84), .B (\I1_ex_mem[0] [0]), .C (n_86), .D
       (\I1_ex_mem[4] [0]), .Q (n_140));
  AOI220 g5623(.A (n_84), .B (\I1_ex_mem[0] [1]), .C (n_83), .D
       (\I1_ex_mem[10] [1]), .Q (n_139));
  AOI220 g5624(.A (n_73), .B (\I1_ex_mem[2] [1]), .C (n_79), .D
       (\I1_ex_mem[9] [1]), .Q (n_138));
  AOI220 g5625(.A (n_77), .B (\I1_ex_mem[3] [1]), .C (n_78), .D
       (\I1_ex_mem[7] [1]), .Q (n_137));
  AOI220 g5626(.A (n_82), .B (\I1_ex_mem[5] [1]), .C (n_88), .D
       (\I1_ex_mem[11] [1]), .Q (n_136));
  AOI220 g5627(.A (n_81), .B (\I1_ex_mem[6] [1]), .C (n_87), .D
       (\I1_ex_mem[12] [1]), .Q (n_135));
  AOI220 g5628(.A (n_87), .B (\I1_ex_mem[12] [2]), .C (n_75), .D
       (\I1_ex_mem[14] [2]), .Q (n_134));
  AOI220 g5629(.A (n_84), .B (\I1_ex_mem[0] [2]), .C (n_79), .D
       (\I1_ex_mem[9] [2]), .Q (n_133));
  AOI220 g5630(.A (n_83), .B (\I1_ex_mem[10] [2]), .C (n_88), .D
       (\I1_ex_mem[11] [2]), .Q (n_132));
  AOI220 g5631(.A (n_86), .B (\I1_ex_mem[4] [3]), .C (n_76), .D
       (\I1_ex_mem[13] [3]), .Q (n_131));
  AOI220 g5632(.A (n_86), .B (\I1_ex_mem[4] [2]), .C (n_76), .D
       (\I1_ex_mem[13] [2]), .Q (n_130));
  AOI220 g5633(.A (n_74), .B (\I1_ex_mem[1] [2]), .C (n_73), .D
       (\I1_ex_mem[2] [2]), .Q (n_129));
  AOI220 g5634(.A (n_74), .B (\I1_ex_mem[1] [3]), .C (n_88), .D
       (\I1_ex_mem[11] [3]), .Q (n_128));
  AOI220 g5635(.A (n_80), .B (\I1_ex_mem[8] [3]), .C (n_77), .D
       (\I1_ex_mem[3] [3]), .Q (n_127));
  AOI220 g5636(.A (n_83), .B (\I1_ex_mem[10] [3]), .C (n_81), .D
       (\I1_ex_mem[6] [3]), .Q (n_126));
  AOI220 g5637(.A (n_80), .B (\I1_ex_mem[8] [6]), .C (n_79), .D
       (\I1_ex_mem[9] [6]), .Q (n_125));
  AOI220 g5638(.A (n_74), .B (\I1_ex_mem[1] [4]), .C (n_73), .D
       (\I1_ex_mem[2] [4]), .Q (n_124));
  AOI220 g5639(.A (n_81), .B (\I1_ex_mem[6] [4]), .C (n_88), .D
       (\I1_ex_mem[11] [4]), .Q (n_123));
  AOI220 g5640(.A (n_84), .B (\I1_ex_mem[0] [4]), .C (n_83), .D
       (\I1_ex_mem[10] [4]), .Q (n_122));
  AOI220 g5641(.A (n_84), .B (\I1_ex_mem[0] [5]), .C (n_73), .D
       (\I1_ex_mem[2] [5]), .Q (n_121));
  AOI220 g5642(.A (n_77), .B (\I1_ex_mem[3] [5]), .C (n_78), .D
       (\I1_ex_mem[7] [5]), .Q (n_120));
  AOI220 g5643(.A (n_87), .B (\I1_ex_mem[12] [5]), .C (n_76), .D
       (\I1_ex_mem[13] [5]), .Q (n_119));
  AOI220 g5644(.A (n_79), .B (\I1_ex_mem[9] [5]), .C (n_75), .D
       (\I1_ex_mem[14] [5]), .Q (n_118));
  AOI220 g5645(.A (n_73), .B (\I1_ex_mem[2] [6]), .C (n_83), .D
       (\I1_ex_mem[10] [6]), .Q (n_117));
  AOI220 g5646(.A (n_82), .B (\I1_ex_mem[5] [3]), .C (n_78), .D
       (\I1_ex_mem[7] [3]), .Q (n_116));
  AOI220 g5647(.A (n_82), .B (\I1_ex_mem[5] [4]), .C (n_78), .D
       (\I1_ex_mem[7] [4]), .Q (n_115));
  AOI220 g5648(.A (n_86), .B (\I1_ex_mem[4] [6]), .C (n_76), .D
       (\I1_ex_mem[13] [6]), .Q (n_114));
  AOI220 g5649(.A (n_81), .B (\I1_ex_mem[6] [6]), .C (n_87), .D
       (\I1_ex_mem[12] [6]), .Q (n_113));
  AOI220 g5650(.A (n_74), .B (\I1_ex_mem[1] [6]), .C (n_82), .D
       (\I1_ex_mem[5] [6]), .Q (n_112));
  AOI220 g5651(.A (n_77), .B (\I1_ex_mem[3] [6]), .C (n_78), .D
       (\I1_ex_mem[7] [6]), .Q (n_111));
  AOI220 g5652(.A (n_87), .B (\I1_ex_mem[12] [4]), .C (n_75), .D
       (\I1_ex_mem[14] [4]), .Q (n_110));
  IMUX20 g5653(.A (I1_r_pointer[3]), .B (n_69), .S (n_44), .Q (n_109));
  INV2 g5656(.A (n_107), .Q (n_108));
  NAND20 g5657(.A (n_77), .B (\I1_ex_mem[3] [0]), .Q (n_107));
  INV2 g5658(.A (n_105), .Q (n_106));
  NAND20 g5659(.A (n_82), .B (\I1_ex_mem[5] [5]), .Q (n_105));
  INV2 g5660(.A (n_103), .Q (n_104));
  NAND20 g5661(.A (n_86), .B (\I1_ex_mem[4] [4]), .Q (n_103));
  INV2 g5662(.A (n_101), .Q (n_102));
  NAND20 g5663(.A (n_84), .B (\I1_ex_mem[0] [3]), .Q (n_101));
  INV2 g5664(.A (n_99), .Q (n_100));
  NAND20 g5665(.A (n_76), .B (\I1_ex_mem[13] [1]), .Q (n_99));
  INV2 g5666(.A (n_97), .Q (n_98));
  NAND20 g5667(.A (n_84), .B (\I1_ex_mem[0] [6]), .Q (n_97));
  INV3 g5668(.A (n_96), .Q (n_95));
  NOR20 g5669(.A (n_45), .B (n_70), .Q (n_96));
  CLKIN3 g5670(.A (n_93), .Q (n_94));
  NAND20 g5671(.A (n_70), .B (I1_rinc), .Q (n_93));
  CLKIN3 g5672(.A (n_91), .Q (n_92));
  NOR31 g5673(.A (I1_w_full), .B (n_59), .C (n_3), .Q (n_91));
  AOI221 g5674(.A (n_15), .B (n_64), .C (I1_w_pointer[2]), .D (n_60),
       .Q (n_90));
  AOI221 g5675(.A (n_54), .B (A_counter[1]), .C (n_26), .D
       (A_counter[2]), .Q (n_89));
  NOR20 g5678(.A (n_23), .B (n_66), .Q (n_88));
  NOR20 g5679(.A (n_24), .B (n_62), .Q (n_87));
  NOR20 g5680(.A (n_24), .B (n_68), .Q (n_86));
  NOR21 g5681(.A (n_63), .B (n_21), .Q (n_85));
  NOR20 g5682(.A (n_24), .B (n_61), .Q (n_84));
  NOR20 g5683(.A (n_18), .B (n_66), .Q (n_83));
  NOR20 g5684(.A (n_17), .B (n_68), .Q (n_82));
  NOR20 g5685(.A (n_18), .B (n_68), .Q (n_81));
  NOR20 g5686(.A (n_24), .B (n_66), .Q (n_80));
  NOR20 g5687(.A (n_17), .B (n_66), .Q (n_79));
  NOR20 g5688(.A (n_23), .B (n_68), .Q (n_78));
  NOR20 g5689(.A (n_23), .B (n_61), .Q (n_77));
  NOR20 g5690(.A (n_17), .B (n_62), .Q (n_76));
  NOR20 g5691(.A (n_18), .B (n_62), .Q (n_75));
  NOR20 g5692(.A (n_17), .B (n_61), .Q (n_74));
  NOR20 g5693(.A (n_18), .B (n_61), .Q (n_73));
  AOI211 g5694(.A (n_10), .B (I1_w_full), .C (n_60), .Q (n_72));
  OAI311 g5695(.A (n_46), .B (I1_w_full), .C (I1_w_pointer[0]), .D
       (n_67), .Q (n_71));
  ADD21 g5696(.A (n_39), .B (I1_r_pointer[3]), .CO (n_70), .S (n_69));
  NAND20 g5697(.A (n_51), .B (n_7), .Q (n_68));
  OAI212 g5698(.A (n_46), .B (n_37), .C (I1_w_pointer[0]), .Q (n_67));
  NAND20 g5699(.A (n_50), .B (I1_r_pointer[3]), .Q (n_66));
  NOR21 g5700(.A (n_53), .B (n_21), .Q (n_65));
  CLKIN2 g5701(.A (n_64), .Q (n_63));
  NOR21 g5702(.A (n_53), .B (I1_w_full), .Q (n_64));
  NAND20 g5703(.A (n_51), .B (I1_r_pointer[3]), .Q (n_62));
  NAND20 g5704(.A (n_50), .B (n_7), .Q (n_61));
  OAI212 g5705(.A (n_5), .B (I1_w_pointer[3]), .C (n_52), .Q (n_60));
  OAI212 g5706(.A (n_48), .B (n_33), .C (n_29), .Q (n_59));
  IMUX20 g5708(.A (I1_r_pointer[1]), .B (n_31), .S (n_44), .Q (n_57));
  IMUX20 g5709(.A (I1_r_pointer[2]), .B (n_40), .S (n_44), .Q (n_56));
  IMUX20 g5710(.A (n_44), .B (n_45), .S (I1_r_pointer[0]), .Q (n_55));
  IMUX21 g5711(.A (n_47), .B (A_counter[2]), .S (A_counter[0]), .Q
       (n_54));
  CLKIN3 g5712(.A (n_52), .Q (n_53));
  NOR21 g5713(.A (n_28), .B (n_48), .Q (n_52));
  NOR20 g5714(.A (n_0), .B (n_45), .Q (n_51));
  NOR20 g5715(.A (I1_r_pointer[2]), .B (n_45), .Q (n_50));
  NOR21 g5716(.A (A_counter[2]), .B (n_42), .Q (n_49));
  NAND22 g5718(.A (I1_w_pointer[0]), .B (I1_winc), .Q (n_48));
  NAND22 g5719(.A (n_25), .B (A_counter[2]), .Q (n_47));
  NAND22 g5720(.A (n_29), .B (I1_winc), .Q (n_46));
  INV2 g5721(.A (n_45), .Q (n_44));
  NAND20 g5722(.A (I1_rinc), .B (n_6), .Q (n_45));
  NOR21 g5723(.A (n_36), .B (n_26), .Q (n_43));
  NAND22 g5724(.A (n_26), .B (n_25), .Q (n_42));
  NAND20 g5725(.A (I1_rinc), .B (n_38), .Q (n_41));
  ADD21 g5726(.A (n_22), .B (I1_r_pointer[2]), .CO (n_39), .S (n_40));
  NOR21 g5730(.A (n_5), .B (n_32), .Q (n_37));
  CLKIN2 g5731(.A (n_25), .Q (n_36));
  AOI211 g5735(.A (n_5), .B (I1_data_en), .C (n_30), .Q (n_34));
  INV3 g5736(.A (n_32), .Q (n_33));
  NOR21 g5737(.A (n_8), .B (n_21), .Q (n_32));
  NAND20 g5738(.A (n_18), .B (n_17), .Q (n_31));
  NOR21 g5739(.A (I1_data_en), .B (I1_w_full), .Q (n_30));
  CLKIN3 g5740(.A (n_28), .Q (n_29));
  NOR20 g5741(.A (I1_data_en), .B (n_6), .Q (n_28));
  NAND22 g5742(.A (n_5), .B (I1_data_en), .Q (n_27));
  NOR21 g5743(.A (A_counter[1]), .B (n_11), .Q (n_26));
  NOR21 g5744(.A (spi_cs), .B (n_4), .Q (n_25));
  NAND20 g5745(.A (n_2), .B (n_12), .Q (n_24));
  CLKIN3 g5746(.A (n_22), .Q (n_23));
  NOR20 g5747(.A (n_12), .B (n_2), .Q (n_22));
  NAND22 g5748(.A (I1_w_pointer[1]), .B (I1_w_pointer[2]), .Q (n_21));
  NAND22 g5749(.A (n_10), .B (n_9), .Q (n_20));
  NOR21 g5750(.A (I1_r_empty), .B (I1_w_full), .Q (n_19));
  NAND20 g5751(.A (n_2), .B (I1_r_pointer[1]), .Q (n_18));
  NAND20 g5752(.A (I1_r_pointer[0]), .B (n_12), .Q (n_17));
  NAND22 g5753(.A (n_9), .B (I1_w_pointer[2]), .Q (n_16));
  CLKIN2 g5754(.A (n_14), .Q (n_15));
  NAND22 g5755(.A (n_10), .B (I1_w_pointer[1]), .Q (n_14));
  NAND20 g5756(.A (I1_w_full), .B (n_6), .Q (n_13));
  INV2 g5767(.A (A_counter[3]), .Q (n_4));
  CLKIN3 g5768(.A (n_reset), .Q (n_3));
  CLKIN0 g5770(.A (n_27), .Q (n_223));
  NOR21 g2(.A (n_5), .B (n_41), .Q (n_224));
endmodule

