`timescale 1 ns / 1 ps
// Generated by Cadence Encounter(R) RTL Compiler v11.20-s017_1

// Verification Directory fv/spi_final_O 

module spi_final_O(data_out, spi_mosi_out, spi_miso_in, read_req,
     m_clk, n_reset);
  input spi_miso_in, read_req, m_clk, n_reset;
  output [119:0] data_out;
  output spi_mosi_out;
  wire spi_miso_in, read_req, m_clk, n_reset;
  wire [119:0] data_out;
  wire spi_mosi_out;
  wire [7:0] O2_data;
  wire [0:3] A_counter;
  wire [2:0] O2_point;
  wire [2:0] O2_point_add;
  wire [3:0] O1_r_pointer;
  wire [7:0] spi_miso_out;
  wire [3:0] O1_w_pointer;
  wire [2:0] O2_control;
  wire O1_r_empty, O1_read_en, O1_rinc, O1_w_full, O1_winc,
       UNCONNECTED, UNCONNECTED0, UNCONNECTED1;
  wire UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5,
       UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9;
  wire UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13,
       UNCONNECTED14, UNCONNECTED15, UNCONNECTED16, UNCONNECTED17;
  wire UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, UNCONNECTED25;
  wire UNCONNECTED26, UNCONNECTED27, UNCONNECTED28, UNCONNECTED29,
       UNCONNECTED30, UNCONNECTED31, UNCONNECTED32, UNCONNECTED33;
  wire UNCONNECTED34, UNCONNECTED35, UNCONNECTED36, UNCONNECTED37,
       UNCONNECTED38, UNCONNECTED39, UNCONNECTED40, UNCONNECTED41;
  wire UNCONNECTED42, UNCONNECTED43, UNCONNECTED44, UNCONNECTED45,
       UNCONNECTED46, UNCONNECTED47, UNCONNECTED48, UNCONNECTED49;
  wire UNCONNECTED50, UNCONNECTED51, UNCONNECTED52, UNCONNECTED53,
       UNCONNECTED54, UNCONNECTED55, UNCONNECTED56, UNCONNECTED57;
  wire UNCONNECTED58, UNCONNECTED59, UNCONNECTED60, UNCONNECTED61,
       UNCONNECTED62, UNCONNECTED63, UNCONNECTED64, UNCONNECTED65;
  wire UNCONNECTED66, UNCONNECTED67, UNCONNECTED68, UNCONNECTED69,
       UNCONNECTED70, UNCONNECTED71, UNCONNECTED72, UNCONNECTED73;
  wire UNCONNECTED74, UNCONNECTED75, UNCONNECTED76, UNCONNECTED77,
       UNCONNECTED78, UNCONNECTED79, UNCONNECTED80, UNCONNECTED81;
  wire UNCONNECTED82, UNCONNECTED83, UNCONNECTED84, UNCONNECTED85,
       UNCONNECTED86, UNCONNECTED87, UNCONNECTED88, UNCONNECTED89;
  wire UNCONNECTED90, UNCONNECTED91, UNCONNECTED92, UNCONNECTED93,
       UNCONNECTED94, UNCONNECTED95, UNCONNECTED96, UNCONNECTED97;
  wire UNCONNECTED98, UNCONNECTED99, UNCONNECTED100, UNCONNECTED101,
       UNCONNECTED102, UNCONNECTED103, UNCONNECTED104, UNCONNECTED105;
  wire UNCONNECTED106, UNCONNECTED107, UNCONNECTED108, UNCONNECTED109,
       UNCONNECTED110, UNCONNECTED111, UNCONNECTED112, UNCONNECTED113;
  wire UNCONNECTED114, UNCONNECTED115, UNCONNECTED116, UNCONNECTED117,
       UNCONNECTED118, UNCONNECTED119, UNCONNECTED120, UNCONNECTED121;
  wire UNCONNECTED122, UNCONNECTED123, UNCONNECTED124, UNCONNECTED125,
       UNCONNECTED126, UNCONNECTED127, UNCONNECTED128, UNCONNECTED129;
  wire UNCONNECTED130, UNCONNECTED131, UNCONNECTED132, UNCONNECTED133,
       UNCONNECTED134, UNCONNECTED135, UNCONNECTED136, UNCONNECTED137;
  wire UNCONNECTED138, UNCONNECTED139, UNCONNECTED140, UNCONNECTED141,
       UNCONNECTED142, control_clk_miso, n_113, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_245;
  wire n_246, n_247, n_248, n_249, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_288, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_299, n_300, n_301, n_302;
  wire n_303, n_304, n_305, n_306, n_307, n_308, n_309, n_310;
  wire n_311, n_312, n_313, n_314, n_315, n_316, n_317, n_318;
  wire n_319, n_320, n_321, n_322, n_323, n_324, n_325, n_326;
  wire n_327, n_328, n_329, n_330, n_331, n_332, n_333, n_334;
  wire n_335, n_336, n_337, n_338, n_339, n_340, n_341, n_342;
  wire n_343, n_344, n_345, n_346, n_347, n_348, n_349, n_350;
  wire n_351, n_352, n_353, n_354, n_355, n_356, n_357, n_358;
  wire n_359, n_360, n_361, n_362, n_363, n_364, n_365, n_366;
  wire n_367, n_368, n_369, n_370, n_371, n_372, n_373, n_374;
  wire n_375, n_376, n_377, n_378, n_379, n_380, n_381, n_382;
  wire n_383, n_384, n_385, n_386, n_387, n_388, n_389, n_390;
  wire n_391, n_392, n_393, n_394, n_395, n_396, n_397, n_398;
  wire n_399, n_400, n_401, n_402, n_403, n_404, n_535, n_536;
  wire n_551, n_552, n_553, n_554, n_555, n_556, n_557, n_558;
  wire n_559, n_560, n_561, n_562, n_563, n_564, n_565, n_566;
  wire n_567, n_568, n_569, n_570, n_571, n_572, n_573, n_574;
  wire n_575, n_576, n_577, n_578, n_579, n_580, n_581, n_582;
  wire n_583, n_584, n_585, n_586, n_587, n_588, n_589, n_590;
  wire n_591, n_592, n_593, n_594, n_595, n_596, n_597, n_598;
  wire n_599, n_600, n_601, n_602, n_603, n_604, n_605, n_606;
  wire n_607, n_608, n_609, n_610, n_611, n_612, n_613, n_614;
  wire n_615, n_616, n_617, n_618, n_619, n_620, n_621, n_622;
  wire n_623, n_624, n_625, n_626, n_627, n_628, n_629, n_630;
  wire n_631, n_632, n_633, n_634, n_635, n_636, n_637, n_638;
  wire n_639, n_640, n_641, n_642, n_643, n_644, n_645, n_646;
  wire n_647, n_648, n_649, n_650, n_651, n_652, n_653, n_654;
  wire n_655, n_656, n_657, n_658, n_659, n_660, n_661, n_662;
  wire n_663, n_664, n_665, spi_clk, spi_cs;
  DFC3 \O2_data_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_403), .Q
       (O2_data[1]), .QN (UNCONNECTED));
  DFC3 \O2_data_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_400), .Q
       (O2_data[2]), .QN (UNCONNECTED0));
  DFC3 \O2_data_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_401), .Q
       (O2_data[0]), .QN (UNCONNECTED1));
  DFC3 \O2_data_reg[3] (.RN (n_reset), .C (spi_clk), .D (n_396), .Q
       (O2_data[3]), .QN (n_607));
  DFC3 \O2_data_reg[4] (.RN (n_reset), .C (spi_clk), .D (n_404), .Q
       (O2_data[4]), .QN (UNCONNECTED2));
  DFC3 \O2_data_reg[5] (.RN (n_reset), .C (spi_clk), .D (n_402), .Q
       (O2_data[5]), .QN (UNCONNECTED3));
  DFC3 \O2_data_reg[6] (.RN (n_reset), .C (spi_clk), .D (n_399), .Q
       (O2_data[6]), .QN (UNCONNECTED4));
  NAND20 g3206(.A (n_392), .B (n_376), .Q (n_404));
  NAND20 g3207(.A (n_371), .B (n_387), .Q (n_403));
  OAI210 g3208(.A (n_390), .B (n_397), .C (n_374), .Q (n_402));
  NAND20 g3205(.A (n_378), .B (n_389), .Q (n_401));
  OAI210 g3209(.A (n_398), .B (n_395), .C (n_368), .Q (n_400));
  OAI210 g3210(.A (n_398), .B (n_397), .C (n_372), .Q (n_399));
  OAI220 g3213(.A (n_341), .B (n_607), .C (n_395), .D (n_340), .Q
       (n_396));
  DFC3 O1_r_empty_reg(.RN (n_reset), .C (m_clk), .D (n_383), .Q
       (O1_r_empty), .QN (n_665));
  DFC3 \A_counter_reg[0] (.RN (n_reset), .C (m_clk), .D (n_393), .Q
       (A_counter[0]), .QN (UNCONNECTED5));
  DFC3 \O2_point_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_385), .Q
       (O2_point[2]), .QN (n_330));
  DFC3 \O2_point_add_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_394),
       .Q (O2_point_add[2]), .QN (n_585));
  DFC3 \O2_point_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_384), .Q
       (O2_point[0]), .QN (n_118));
  DFC3 \O2_point_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_391), .Q
       (O2_point[1]), .QN (UNCONNECTED6));
  DFC3 \O2_point_add_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_366),
       .Q (O2_point_add[1]), .QN (UNCONNECTED7));
  DFC3 O2_spi_mosi_out_reg(.RN (n_reset), .C (spi_clk), .D (n_364), .Q
       (spi_mosi_out), .QN (UNCONNECTED8));
  DFC3 \O1_r_pointer_reg[3] (.RN (n_reset), .C (m_clk), .D (n_379), .Q
       (O1_r_pointer[3]), .QN (UNCONNECTED9));
  DFC3 \O1_r_pointer_reg[0] (.RN (n_reset), .C (m_clk), .D (n_381), .Q
       (O1_r_pointer[0]), .QN (UNCONNECTED10));
  DFC3 \O1_r_pointer_reg[1] (.RN (n_reset), .C (m_clk), .D (n_358), .Q
       (O1_r_pointer[1]), .QN (UNCONNECTED11));
  DFC3 \O1_r_pointer_reg[2] (.RN (n_reset), .C (m_clk), .D (n_382), .Q
       (O1_r_pointer[2]), .QN (UNCONNECTED12));
  NAND30 g3221(.A (n_314), .B (n_335), .C (n_322), .Q (n_394));
  INV2 g3211(.A (n_377), .Q (n_393));
  NAND20 g3340(.A (n_360), .B (n_388), .Q (n_392));
  OAI210 g3228(.A (n_390), .B (n_325), .C (n_339), .Q (n_391));
  NAND20 g3341(.A (n_386), .B (n_388), .Q (n_389));
  NAND20 g3342(.A (n_386), .B (n_303), .Q (n_387));
  INV0 g3229(.A (n_365), .Q (n_385));
  INV0 g3231(.A (n_363), .Q (n_384));
  INV2 g3200(.A (n_359), .Q (n_383));
  NOR21 g3203(.A (n_280), .B (n_380), .Q (n_382));
  NOR21 g3204(.A (n_287), .B (n_380), .Q (n_381));
  NOR21 g3074(.A (n_336), .B (n_380), .Q (n_379));
  OAI210 g3222(.A (n_375), .B (n_369), .C (O2_data[0]), .Q (n_378));
  AOI221 g3212(.A (n_333), .B (A_counter[2]), .C (n_283), .D
       (A_counter[0]), .Q (n_377));
  OAI210 g3223(.A (n_375), .B (n_373), .C (O2_data[4]), .Q (n_376));
  OAI210 g3224(.A (n_370), .B (n_373), .C (O2_data[5]), .Q (n_374));
  OAI210 g3225(.A (n_367), .B (n_373), .C (O2_data[6]), .Q (n_372));
  OAI210 g3226(.A (n_370), .B (n_369), .C (O2_data[1]), .Q (n_371));
  OAI210 g3227(.A (n_367), .B (n_369), .C (O2_data[2]), .Q (n_368));
  INV0 g3344(.A (n_342), .Q (n_366));
  AOI220 g3230(.A (n_326), .B (n_362), .C (n_361), .D (O2_point[2]), .Q
       (n_365));
  OAI2110 g3349(.A (n_327), .B (n_238), .C (n_301), .D (n_323), .Q
       (n_364));
  AOI220 g3232(.A (n_324), .B (n_362), .C (n_361), .D (O2_point[0]), .Q
       (n_363));
  INV0 g3368(.A (n_386), .Q (n_395));
  INV0 g3371(.A (n_360), .Q (n_397));
  NOR21 g3201(.A (O1_r_empty), .B (n_380), .Q (n_359));
  TFEC3 A_spi_clk_reg(.RN (n_reset), .C (m_clk), .T (n_320), .Q
       (spi_clk), .QN (UNCONNECTED13));
  NOR21 g3202(.A (n_289), .B (n_380), .Q (n_358));
  DLQ3 \O1_data_out_reg[39] (.GN (n_357), .D (1'b0), .Q (data_out[39]));
  DLQ3 \O1_data_out_reg[103] (.GN (n_357), .D (1'b0), .Q
       (data_out[103]));
  DLQ3 \O1_data_out_reg[63] (.GN (n_357), .D (1'b0), .Q (data_out[63]));
  DLQ3 \O1_data_out_reg[71] (.GN (n_357), .D (1'b0), .Q (data_out[71]));
  DLQ3 \O1_data_out_reg[111] (.GN (n_357), .D (1'b0), .Q
       (data_out[111]));
  DLQ3 \O1_data_out_reg[79] (.GN (n_357), .D (1'b0), .Q (data_out[79]));
  DFE1 \O1_ex_mem_reg[0][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_354), .Q (UNCONNECTED14), .QN (n_613));
  DLQ3 \O1_data_out_reg[47] (.GN (n_357), .D (1'b0), .Q (data_out[47]));
  DLQ3 \O1_data_out_reg[119] (.GN (n_357), .D (1'b0), .Q
       (data_out[119]));
  DLQ3 \O1_data_out_reg[87] (.GN (n_357), .D (1'b0), .Q (data_out[87]));
  DLQ3 \O1_data_out_reg[95] (.GN (n_357), .D (1'b0), .Q (data_out[95]));
  DLQ3 \O1_data_out_reg[55] (.GN (n_357), .D (1'b0), .Q (data_out[55]));
  DLQ3 \O1_data_out_reg[15] (.GN (n_357), .D (1'b0), .Q (data_out[15]));
  DLQ3 \O1_data_out_reg[7] (.GN (n_357), .D (1'b0), .Q (data_out[7]));
  DFE1 \O1_ex_mem_reg[8][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_355), .Q (UNCONNECTED15), .QN (n_556));
  DFC3 \O2_point_add_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_332),
       .Q (O2_point_add[0]), .QN (n_286));
  DFE1 \O1_ex_mem_reg[12][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_356), .Q (UNCONNECTED16), .QN (n_632));
  DFE1 \O1_ex_mem_reg[12][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_356), .Q (UNCONNECTED17), .QN (n_605));
  DFE1 \O1_ex_mem_reg[12][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_356), .Q (UNCONNECTED18), .QN (n_646));
  DFE1 \O1_ex_mem_reg[12][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_356), .Q (UNCONNECTED19), .QN (n_560));
  DFE1 \O1_ex_mem_reg[12][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_356), .Q (UNCONNECTED20), .QN (n_558));
  DFE1 \O1_ex_mem_reg[12][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_356), .Q (UNCONNECTED21), .QN (n_561));
  DFE1 \O1_ex_mem_reg[12][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_356), .Q (UNCONNECTED22), .QN (n_570));
  DFE1 \O1_ex_mem_reg[8][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_355), .Q (UNCONNECTED23), .QN (n_559));
  DFE1 \O1_ex_mem_reg[8][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_355), .Q (UNCONNECTED24), .QN (n_584));
  DFE1 \O1_ex_mem_reg[8][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_355), .Q (UNCONNECTED25), .QN (n_563));
  DFE1 \O1_ex_mem_reg[8][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_355), .Q (UNCONNECTED26), .QN (n_601));
  DFE1 \O1_ex_mem_reg[8][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_355), .Q (UNCONNECTED27), .QN (n_642));
  DFE1 \O1_ex_mem_reg[8][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_355), .Q (UNCONNECTED28), .QN (n_581));
  DFE1 \O1_ex_mem_reg[0][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_354), .Q (UNCONNECTED29), .QN (n_602));
  DFE1 \O1_ex_mem_reg[0][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_354), .Q (UNCONNECTED30), .QN (n_580));
  DFE1 \O1_ex_mem_reg[0][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_354), .Q (UNCONNECTED31), .QN (n_583));
  DFE1 \O1_ex_mem_reg[0][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_354), .Q (UNCONNECTED32), .QN (n_576));
  DFE1 \O1_ex_mem_reg[0][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_354), .Q (UNCONNECTED33), .QN (n_557));
  DFE1 \O1_ex_mem_reg[0][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_354), .Q (UNCONNECTED34), .QN (n_626));
  DFE1 \O1_ex_mem_reg[9][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_353), .Q (UNCONNECTED35), .QN (n_573));
  DFE1 \O1_ex_mem_reg[9][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_353), .Q (UNCONNECTED36), .QN (n_565));
  DFE1 \O1_ex_mem_reg[9][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_353), .Q (UNCONNECTED37), .QN (n_628));
  DFE1 \O1_ex_mem_reg[9][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_353), .Q (UNCONNECTED38), .QN (n_603));
  DFE1 \O1_ex_mem_reg[9][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_353), .Q (UNCONNECTED39), .QN (n_638));
  DFE1 \O1_ex_mem_reg[9][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_353), .Q (UNCONNECTED40), .QN (n_567));
  DFE1 \O1_ex_mem_reg[9][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_353), .Q (UNCONNECTED41), .QN (n_566));
  DFE1 \O1_ex_mem_reg[10][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_352), .Q (UNCONNECTED42), .QN (n_625));
  DFE1 \O1_ex_mem_reg[10][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_352), .Q (UNCONNECTED43), .QN (n_614));
  DFE1 \O1_ex_mem_reg[10][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_352), .Q (UNCONNECTED44), .QN (n_586));
  DFE1 \O1_ex_mem_reg[10][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_352), .Q (UNCONNECTED45), .QN (n_588));
  DLQ3 \O1_data_out_reg[31] (.GN (n_357), .D (1'b0), .Q (data_out[31]));
  DFE1 \O1_ex_mem_reg[10][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_352), .Q (UNCONNECTED46), .QN (n_664));
  DFE1 \O1_ex_mem_reg[13][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_351), .Q (UNCONNECTED47), .QN (n_589));
  DLQ3 \O1_data_out_reg[9] (.GN (n_357), .D (n_122), .Q (data_out[9]));
  DFE1 \O1_ex_mem_reg[13][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_351), .Q (UNCONNECTED48), .QN (n_623));
  DFE1 \O1_ex_mem_reg[13][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_351), .Q (UNCONNECTED49), .QN (n_592));
  DFE1 \O1_ex_mem_reg[13][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_351), .Q (UNCONNECTED50), .QN (n_594));
  DLQ3 \O1_data_out_reg[16] (.GN (n_357), .D (n_173), .Q
       (data_out[16]));
  DFE1 \O1_ex_mem_reg[13][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_351), .Q (UNCONNECTED51), .QN (n_575));
  DFE1 \O1_ex_mem_reg[13][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_351), .Q (UNCONNECTED52), .QN (n_652));
  DFE1 \O1_ex_mem_reg[14][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_350), .Q (UNCONNECTED53), .QN (n_595));
  DFE1 \O1_ex_mem_reg[14][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_350), .Q (UNCONNECTED54), .QN (n_598));
  DFE1 \O1_ex_mem_reg[14][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_350), .Q (UNCONNECTED55), .QN (n_655));
  DFE1 \O1_ex_mem_reg[14][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_350), .Q (UNCONNECTED56), .QN (n_599));
  DFE1 \O1_ex_mem_reg[14][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_350), .Q (UNCONNECTED57), .QN (n_578));
  DLQ3 \O1_data_out_reg[13] (.GN (n_357), .D (n_205), .Q
       (data_out[13]));
  DFE1 \O1_ex_mem_reg[11][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_349), .Q (UNCONNECTED58), .QN (n_579));
  DFE1 \O1_ex_mem_reg[11][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_349), .Q (UNCONNECTED59), .QN (n_624));
  DFE1 \O1_ex_mem_reg[11][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_349), .Q (UNCONNECTED60), .QN (n_644));
  DLQ3 \O1_data_out_reg[8] (.GN (n_357), .D (n_200), .Q (data_out[8]));
  DFE1 \O1_ex_mem_reg[11][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_349), .Q (UNCONNECTED61), .QN (n_606));
  DFE1 \O1_ex_mem_reg[11][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_349), .Q (UNCONNECTED62), .QN (n_610));
  DFE1 \O1_ex_mem_reg[11][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_349), .Q (UNCONNECTED63), .QN (n_608));
  DLQ3 \O1_data_out_reg[86] (.GN (n_357), .D (n_135), .Q
       (data_out[86]));
  DFE1 \O1_ex_mem_reg[1][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_348), .Q (UNCONNECTED64), .QN (n_641));
  DFE1 \O1_ex_mem_reg[1][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_348), .Q (UNCONNECTED65), .QN (n_593));
  DFE1 \O1_ex_mem_reg[1][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_348), .Q (UNCONNECTED66), .QN (n_568));
  DFE1 \O1_ex_mem_reg[1][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_348), .Q (UNCONNECTED67), .QN (n_651));
  DFE1 \O1_ex_mem_reg[1][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_348), .Q (UNCONNECTED68), .QN (n_647));
  DFE1 \O1_ex_mem_reg[1][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_348), .Q (UNCONNECTED69), .QN (n_649));
  DFE1 \O1_ex_mem_reg[2][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_347), .Q (UNCONNECTED70), .QN (n_619));
  DLQ3 \O1_data_out_reg[81] (.GN (n_357), .D (n_210), .Q
       (data_out[81]));
  DFE1 \O1_ex_mem_reg[2][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_347), .Q (UNCONNECTED71), .QN (n_609));
  DFE1 \O1_ex_mem_reg[2][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_347), .Q (UNCONNECTED72), .QN (n_643));
  DFE1 \O1_ex_mem_reg[2][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_347), .Q (UNCONNECTED73), .QN (n_656));
  DLQ3 \O1_data_out_reg[114] (.GN (n_357), .D (n_185), .Q
       (data_out[114]));
  DFE1 \O1_ex_mem_reg[2][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_347), .Q (UNCONNECTED74), .QN (n_645));
  DFE1 \O1_ex_mem_reg[3][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_346), .Q (UNCONNECTED75), .QN (n_658));
  DLQ3 \O1_data_out_reg[75] (.GN (n_357), .D (n_115), .Q
       (data_out[75]));
  DFE1 \O1_ex_mem_reg[3][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_346), .Q (UNCONNECTED76), .QN (n_604));
  DFE1 \O1_ex_mem_reg[3][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_346), .Q (UNCONNECTED77), .QN (n_627));
  DFE1 \O1_ex_mem_reg[3][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_346), .Q (UNCONNECTED78), .QN (n_648));
  DFE1 \O1_ex_mem_reg[3][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_346), .Q (UNCONNECTED79), .QN (n_650));
  DFE1 \O1_ex_mem_reg[3][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_346), .Q (UNCONNECTED80), .QN (n_630));
  DFE1 \O1_ex_mem_reg[4][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_345), .Q (UNCONNECTED81), .QN (n_621));
  DFE1 \O1_ex_mem_reg[4][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_345), .Q (UNCONNECTED82), .QN (n_634));
  DLQ3 \O1_data_out_reg[69] (.GN (n_357), .D (n_160), .Q
       (data_out[69]));
  DFE1 \O1_ex_mem_reg[4][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_345), .Q (UNCONNECTED83), .QN (n_555));
  DFE1 \O1_ex_mem_reg[4][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_345), .Q (UNCONNECTED84), .QN (n_633));
  DFE1 \O1_ex_mem_reg[4][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_345), .Q (UNCONNECTED85), .QN (n_552));
  DLQ3 \O1_data_out_reg[109] (.GN (n_357), .D (n_198), .Q
       (data_out[109]));
  DFE1 \O1_ex_mem_reg[4][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_345), .Q (UNCONNECTED86), .QN (n_577));
  DFE1 \O1_ex_mem_reg[5][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_344), .Q (UNCONNECTED87), .QN (n_572));
  DFE1 \O1_ex_mem_reg[5][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_344), .Q (UNCONNECTED88), .QN (n_662));
  DLQ3 \O1_data_out_reg[64] (.GN (n_357), .D (n_217), .Q
       (data_out[64]));
  DFE1 \O1_ex_mem_reg[5][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_344), .Q (UNCONNECTED89), .QN (n_663));
  DFE1 \O1_ex_mem_reg[5][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_344), .Q (UNCONNECTED90), .QN (n_635));
  DFE1 \O1_ex_mem_reg[5][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_344), .Q (UNCONNECTED91), .QN (n_660));
  DFE1 \O1_ex_mem_reg[5][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_344), .Q (UNCONNECTED92), .QN (n_590));
  DFE1 \O1_ex_mem_reg[6][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_343), .Q (UNCONNECTED93), .QN (n_639));
  DFE1 \O1_ex_mem_reg[6][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_343), .Q (UNCONNECTED94), .QN (n_637));
  DFE1 \O1_ex_mem_reg[6][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_343), .Q (UNCONNECTED95), .QN (n_612));
  DLQ3 \O1_data_out_reg[59] (.GN (n_357), .D (n_202), .Q
       (data_out[59]));
  DFE1 \O1_ex_mem_reg[6][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_343), .Q (UNCONNECTED96), .QN (n_571));
  DFE1 \O1_ex_mem_reg[6][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_343), .Q (UNCONNECTED97), .QN (n_631));
  DLQ3 \O1_data_out_reg[56] (.GN (n_357), .D (n_149), .Q
       (data_out[56]));
  DFE1 \O1_ex_mem_reg[5][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_344), .Q (UNCONNECTED98), .QN (n_600));
  DFE1 \O1_ex_mem_reg[6][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_343), .Q (UNCONNECTED99), .QN (n_629));
  DFE1 \O1_ex_mem_reg[6][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_343), .Q (UNCONNECTED100), .QN (n_569));
  DLQ3 \O1_data_out_reg[52] (.GN (n_357), .D (n_154), .Q
       (data_out[52]));
  DFE1 \O1_ex_mem_reg[4][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_345), .Q (UNCONNECTED101), .QN (n_640));
  DFE1 \O1_ex_mem_reg[3][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_346), .Q (UNCONNECTED102), .QN (n_596));
  DFE1 \O1_ex_mem_reg[2][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_347), .Q (UNCONNECTED103), .QN (n_618));
  DLQ3 \O1_data_out_reg[46] (.GN (n_357), .D (n_130), .Q
       (data_out[46]));
  DLQ3 \O1_data_out_reg[42] (.GN (n_357), .D (n_222), .Q
       (data_out[42]));
  DFE1 \O1_ex_mem_reg[13][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_351), .Q (UNCONNECTED104), .QN (n_622));
  DFE1 \O1_ex_mem_reg[11][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_349), .Q (UNCONNECTED105), .QN (n_620));
  DLQ3 \O1_data_out_reg[38] (.GN (n_357), .D (n_152), .Q
       (data_out[38]));
  DFE1 \O1_ex_mem_reg[2][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_347), .Q (UNCONNECTED106), .QN (n_553));
  DFE1 \O1_ex_mem_reg[10][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_352), .Q (UNCONNECTED107), .QN (n_653));
  AOI210 g3345(.A (n_290), .B (O2_point_add[1]), .C (n_328), .Q
       (n_342));
  DFE1 \O1_ex_mem_reg[1][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_348), .Q (UNCONNECTED108), .QN (n_554));
  AOI210 g3346(.A (n_340), .B (n_299), .C (n_369), .Q (n_341));
  DLQ3 \O1_data_out_reg[2] (.GN (n_357), .D (n_168), .Q (data_out[2]));
  DFE1 \O1_ex_mem_reg[10][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_352), .Q (UNCONNECTED109), .QN (n_564));
  AOI210 g3350(.A (n_313), .B (O2_point[1]), .C (n_256), .Q (n_339));
  DFE1 \O1_ex_mem_reg[14][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_350), .Q (UNCONNECTED110), .QN (n_617));
  NOR20 g3369(.A (O2_point[2]), .B (n_338), .Q (n_386));
  NOR20 g3372(.A (n_330), .B (n_338), .Q (n_360));
  DFE1 \O1_ex_mem_reg[14][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_350), .Q (UNCONNECTED111), .QN (n_654));
  DLQ3 \O1_data_out_reg[1] (.GN (n_357), .D (n_132), .Q (data_out[1]));
  DLQ3 \O1_data_out_reg[20] (.GN (n_357), .D (n_190), .Q
       (data_out[20]));
  DLQ3 \O1_data_out_reg[21] (.GN (n_357), .D (n_182), .Q
       (data_out[21]));
  DLQ3 \O1_data_out_reg[22] (.GN (n_357), .D (n_146), .Q
       (data_out[22]));
  DLQ3 \O1_data_out_reg[24] (.GN (n_357), .D (n_170), .Q
       (data_out[24]));
  DLQ3 \O1_data_out_reg[25] (.GN (n_357), .D (n_167), .Q
       (data_out[25]));
  DLQ3 \O1_data_out_reg[26] (.GN (n_357), .D (n_143), .Q
       (data_out[26]));
  DLQ3 \O1_data_out_reg[27] (.GN (n_357), .D (n_191), .Q
       (data_out[27]));
  DLQ3 \O1_data_out_reg[28] (.GN (n_357), .D (n_142), .Q
       (data_out[28]));
  DLQ3 \O1_data_out_reg[29] (.GN (n_357), .D (n_206), .Q
       (data_out[29]));
  DLQ3 \O1_data_out_reg[30] (.GN (n_357), .D (n_117), .Q
       (data_out[30]));
  DLQ3 \O1_data_out_reg[32] (.GN (n_357), .D (n_218), .Q
       (data_out[32]));
  DLQ3 \O1_data_out_reg[33] (.GN (n_357), .D (n_144), .Q
       (data_out[33]));
  DLQ3 \O1_data_out_reg[34] (.GN (n_357), .D (n_208), .Q
       (data_out[34]));
  DLQ3 \O1_data_out_reg[35] (.GN (n_357), .D (n_164), .Q
       (data_out[35]));
  DLQ3 \O1_data_out_reg[36] (.GN (n_357), .D (n_137), .Q
       (data_out[36]));
  DLQ3 \O1_data_out_reg[37] (.GN (n_357), .D (n_147), .Q
       (data_out[37]));
  DLQ3 \O1_data_out_reg[3] (.GN (n_357), .D (n_178), .Q (data_out[3]));
  DLQ3 \O1_data_out_reg[40] (.GN (n_357), .D (n_166), .Q
       (data_out[40]));
  DLQ3 \O1_data_out_reg[41] (.GN (n_357), .D (n_176), .Q
       (data_out[41]));
  DLQ3 \O1_data_out_reg[43] (.GN (n_357), .D (n_181), .Q
       (data_out[43]));
  DLQ3 \O1_data_out_reg[44] (.GN (n_357), .D (n_189), .Q
       (data_out[44]));
  DLQ3 \O1_data_out_reg[45] (.GN (n_357), .D (n_223), .Q
       (data_out[45]));
  DLQ3 \O1_data_out_reg[48] (.GN (n_357), .D (n_163), .Q
       (data_out[48]));
  DLQ3 \O1_data_out_reg[49] (.GN (n_357), .D (n_138), .Q
       (data_out[49]));
  DLQ3 \O1_data_out_reg[4] (.GN (n_357), .D (n_215), .Q (data_out[4]));
  DLQ3 \O1_data_out_reg[100] (.GN (n_357), .D (n_158), .Q
       (data_out[100]));
  DLQ3 \O1_data_out_reg[50] (.GN (n_357), .D (n_157), .Q
       (data_out[50]));
  DLQ3 \O1_data_out_reg[51] (.GN (n_357), .D (n_125), .Q
       (data_out[51]));
  DLQ3 \O1_data_out_reg[101] (.GN (n_357), .D (n_156), .Q
       (data_out[101]));
  DLQ3 \O1_data_out_reg[53] (.GN (n_357), .D (n_136), .Q
       (data_out[53]));
  DLQ3 \O1_data_out_reg[102] (.GN (n_357), .D (n_148), .Q
       (data_out[102]));
  DLQ3 \O1_data_out_reg[54] (.GN (n_357), .D (n_145), .Q
       (data_out[54]));
  DLQ3 \O1_data_out_reg[57] (.GN (n_357), .D (n_161), .Q
       (data_out[57]));
  DLQ3 \O1_data_out_reg[104] (.GN (n_357), .D (n_150), .Q
       (data_out[104]));
  DLQ3 \O1_data_out_reg[58] (.GN (n_357), .D (n_141), .Q
       (data_out[58]));
  DLQ3 \O1_data_out_reg[105] (.GN (n_357), .D (n_199), .Q
       (data_out[105]));
  DLQ3 \O1_data_out_reg[5] (.GN (n_357), .D (n_180), .Q (data_out[5]));
  DLQ3 \O1_data_out_reg[60] (.GN (n_357), .D (n_183), .Q
       (data_out[60]));
  DLQ3 \O1_data_out_reg[106] (.GN (n_357), .D (n_186), .Q
       (data_out[106]));
  DLQ3 \O1_data_out_reg[61] (.GN (n_357), .D (n_203), .Q
       (data_out[61]));
  DLQ3 \O1_data_out_reg[62] (.GN (n_357), .D (n_195), .Q
       (data_out[62]));
  DLQ3 \O1_data_out_reg[107] (.GN (n_357), .D (n_133), .Q
       (data_out[107]));
  DLQ3 \O1_data_out_reg[108] (.GN (n_357), .D (n_194), .Q
       (data_out[108]));
  DLQ3 \O1_data_out_reg[65] (.GN (n_357), .D (n_212), .Q
       (data_out[65]));
  DLQ3 \O1_data_out_reg[66] (.GN (n_357), .D (n_216), .Q
       (data_out[66]));
  DLQ3 \O1_data_out_reg[67] (.GN (n_357), .D (n_192), .Q
       (data_out[67]));
  DLQ3 \O1_data_out_reg[68] (.GN (n_357), .D (n_221), .Q
       (data_out[68]));
  DLQ3 \O1_data_out_reg[10] (.GN (n_357), .D (n_201), .Q
       (data_out[10]));
  DLQ3 \O1_data_out_reg[6] (.GN (n_357), .D (n_211), .Q (data_out[6]));
  DLQ3 \O1_data_out_reg[110] (.GN (n_357), .D (n_175), .Q
       (data_out[110]));
  DLQ3 \O1_data_out_reg[70] (.GN (n_357), .D (n_116), .Q
       (data_out[70]));
  DLQ3 \O1_data_out_reg[72] (.GN (n_357), .D (n_196), .Q
       (data_out[72]));
  DLQ3 \O1_data_out_reg[73] (.GN (n_357), .D (n_128), .Q
       (data_out[73]));
  DLQ3 \O1_data_out_reg[112] (.GN (n_357), .D (n_224), .Q
       (data_out[112]));
  DLQ3 \O1_data_out_reg[74] (.GN (n_357), .D (n_193), .Q
       (data_out[74]));
  DLQ3 \O1_data_out_reg[113] (.GN (n_357), .D (n_126), .Q
       (data_out[113]));
  DLQ3 \O1_data_out_reg[76] (.GN (n_357), .D (n_159), .Q
       (data_out[76]));
  DLQ3 \O1_data_out_reg[77] (.GN (n_357), .D (n_153), .Q
       (data_out[77]));
  DLQ3 \O1_data_out_reg[78] (.GN (n_357), .D (n_121), .Q
       (data_out[78]));
  DLQ3 \O1_data_out_reg[115] (.GN (n_357), .D (n_151), .Q
       (data_out[115]));
  DLQ3 \O1_data_out_reg[80] (.GN (n_357), .D (n_188), .Q
       (data_out[80]));
  DLQ3 \O1_data_out_reg[116] (.GN (n_357), .D (n_177), .Q
       (data_out[116]));
  DLQ3 \O1_data_out_reg[82] (.GN (n_357), .D (n_162), .Q
       (data_out[82]));
  DLQ3 \O1_data_out_reg[83] (.GN (n_357), .D (n_140), .Q
       (data_out[83]));
  DLQ3 \O1_data_out_reg[117] (.GN (n_357), .D (n_204), .Q
       (data_out[117]));
  DLQ3 \O1_data_out_reg[84] (.GN (n_357), .D (n_174), .Q
       (data_out[84]));
  DLQ3 \O1_data_out_reg[85] (.GN (n_357), .D (n_123), .Q
       (data_out[85]));
  DLQ3 \O1_data_out_reg[118] (.GN (n_357), .D (n_213), .Q
       (data_out[118]));
  DLQ3 \O1_data_out_reg[88] (.GN (n_357), .D (n_197), .Q
       (data_out[88]));
  DLQ3 \O1_data_out_reg[11] (.GN (n_357), .D (n_220), .Q
       (data_out[11]));
  DLQ3 \O1_data_out_reg[89] (.GN (n_357), .D (n_214), .Q
       (data_out[89]));
  DLQ3 \O1_data_out_reg[12] (.GN (n_357), .D (n_165), .Q
       (data_out[12]));
  DLQ3 \O1_data_out_reg[90] (.GN (n_357), .D (n_129), .Q
       (data_out[90]));
  DLQ3 \O1_data_out_reg[91] (.GN (n_357), .D (n_171), .Q
       (data_out[91]));
  DLQ3 \O1_data_out_reg[92] (.GN (n_357), .D (n_139), .Q
       (data_out[92]));
  DLQ3 \O1_data_out_reg[0] (.GN (n_357), .D (n_187), .Q (data_out[0]));
  DLQ3 \O1_data_out_reg[93] (.GN (n_357), .D (n_155), .Q
       (data_out[93]));
  DLQ3 \O1_data_out_reg[14] (.GN (n_357), .D (n_169), .Q
       (data_out[14]));
  DLQ3 \O1_data_out_reg[94] (.GN (n_357), .D (n_207), .Q
       (data_out[94]));
  DLQ3 \O1_data_out_reg[96] (.GN (n_357), .D (n_179), .Q
       (data_out[96]));
  DLQ3 \O1_data_out_reg[97] (.GN (n_357), .D (n_124), .Q
       (data_out[97]));
  DLQ3 \O1_data_out_reg[98] (.GN (n_357), .D (n_172), .Q
       (data_out[98]));
  DLQ3 \O1_data_out_reg[99] (.GN (n_357), .D (n_127), .Q
       (data_out[99]));
  DLQ3 \O1_data_out_reg[17] (.GN (n_357), .D (n_134), .Q
       (data_out[17]));
  DLQ3 \O1_data_out_reg[18] (.GN (n_357), .D (n_184), .Q
       (data_out[18]));
  DLQ3 \O1_data_out_reg[19] (.GN (n_357), .D (n_131), .Q
       (data_out[19]));
  DLQ3 \O1_data_out_reg[23] (.GN (n_357), .D (1'b0), .Q (data_out[23]));
  DFE1 \O1_ex_mem_reg[7][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_337), .Q (UNCONNECTED112), .QN (n_587));
  DFC3 \O1_w_pointer_reg[3] (.RN (n_reset), .C (control_clk_miso), .D
       (n_321), .Q (O1_w_pointer[3]), .QN (n_247));
  DFE1 \O1_ex_mem_reg[7][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_337), .Q (UNCONNECTED113), .QN (n_562));
  DFE1 \O1_ex_mem_reg[7][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_337), .Q (UNCONNECTED114), .QN (n_574));
  DFE1 \O1_ex_mem_reg[7][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_337), .Q (UNCONNECTED115), .QN (n_659));
  DFE1 \O1_ex_mem_reg[7][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_337), .Q (UNCONNECTED116), .QN (n_661));
  DFE1 \O1_ex_mem_reg[7][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_337), .Q (UNCONNECTED117), .QN (n_616));
  DFE1 \O1_ex_mem_reg[7][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_337), .Q (UNCONNECTED118), .QN (n_611));
  NOR21 g3220(.A (O1_rinc), .B (n_317), .Q (n_380));
  IMUX21 g3214(.A (O1_r_pointer[3]), .B (n_293), .S (n_288), .Q
       (n_336));
  NAND20 g3373(.A (n_315), .B (O2_point_add[1]), .Q (n_335));
  TFSC1 \A_counter_reg[1] (.RN (n_reset), .C (m_clk), .SD
       (A_counter[1]), .SE (n_285), .Q (A_counter[1]), .QN
       (UNCONNECTED119));
  DFC3 O1_w_full_reg(.RN (n_reset), .C (control_clk_miso), .D (n_296),
       .Q (O1_w_full), .QN (n_209));
  DFC3 \O1_w_pointer_reg[2] (.RN (n_reset), .C (control_clk_miso), .D
       (n_295), .Q (O1_w_pointer[2]), .QN (n_269));
  DFEC1 \O2_final_data_reg[0] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[0]), .E (n_334), .Q (UNCONNECTED120), .QN (n_657));
  DFEC1 \O2_final_data_reg[1] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[1]), .E (n_334), .Q (UNCONNECTED121), .QN (n_591));
  DFEC1 \O2_final_data_reg[4] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[4]), .E (n_334), .Q (UNCONNECTED122), .QN (n_582));
  DFEC1 \O2_final_data_reg[5] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[5]), .E (n_334), .Q (UNCONNECTED123), .QN (n_551));
  DFEC1 \O2_final_data_reg[6] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[6]), .E (n_334), .Q (UNCONNECTED124), .QN (n_615));
  DFEC1 \O2_final_data_reg[3] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[3]), .E (n_334), .Q (UNCONNECTED125), .QN (n_597));
  DFEC1 \O2_final_data_reg[2] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[2]), .E (n_334), .Q (UNCONNECTED126), .QN (n_636));
  OAI311 g3347(.A (n_282), .B (A_counter[0]), .C (n_318), .D (n_319),
       .Q (n_333));
  OAI2110 g3374(.A (n_286), .B (n_254), .C (n_300), .D (n_297), .Q
       (n_332));
  OAI210 g3375(.A (n_331), .B (O2_point[2]), .C (n_329), .Q (n_373));
  OAI210 g3376(.A (n_331), .B (n_330), .C (n_329), .Q (n_369));
  NOR21 g3219(.A (n_246), .B (n_316), .Q (n_357));
  OAI220 g3378(.A (n_236), .B (n_253), .C (n_327), .D
       (O2_point_add[1]), .Q (n_328));
  OAI220 g3379(.A (n_325), .B (n_340), .C (n_330), .D (spi_cs), .Q
       (n_326));
  IMUX20 g3381(.A (n_325), .B (n_312), .S (O2_point[0]), .Q (n_324));
  NAND20 g3387(.A (n_302), .B (spi_miso_in), .Q (n_338));
  NAND20 g3392(.A (n_322), .B (n_298), .Q (n_323));
  DFEC1 \A_counter_reg[2] (.RN (n_reset), .C (m_clk), .D (n_239), .E
       (n_284), .Q (A_counter[2]), .QN (UNCONNECTED127));
  DFC3 \O1_w_pointer_reg[0] (.RN (n_reset), .C (control_clk_miso), .D
       (n_276), .Q (O1_w_pointer[0]), .QN (n_119));
  DFC3 \O2_control_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_279), .Q
       (O2_control[2]), .QN (UNCONNECTED128));
  NOR20 g3343(.A (n_294), .B (n_281), .Q (n_321));
  NOR31 g3348(.A (n_319), .B (n_318), .C (A_counter[2]), .Q (n_320));
  CLKIN2 g3351(.A (n_316), .Q (n_317));
  NOR20 g3383(.A (O2_point_add[2]), .B (n_327), .Q (n_315));
  OAI210 g3394(.A (n_272), .B (n_362), .C (O2_point_add[2]), .Q
       (n_314));
  OAI210 g3395(.A (n_312), .B (O2_point[2]), .C (n_268), .Q (n_313));
  NOR20 g3407(.A (n_311), .B (n_306), .Q (n_354));
  TFEC3 O2_control_clk_miso_reg(.RN (n_reset), .C (spi_clk), .T
       (n_278), .Q (control_clk_miso), .QN (n_255));
  NOR20 g3405(.A (n_311), .B (n_304), .Q (n_356));
  NOR20 g3406(.A (n_311), .B (n_310), .Q (n_355));
  DFC3 \O2_control_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_267), .Q
       (O2_control[0]), .QN (UNCONNECTED129));
  NOR20 g3411(.A (n_331), .B (n_388), .Q (n_375));
  NOR20 g3412(.A (n_305), .B (n_310), .Q (n_352));
  NOR20 g3415(.A (n_308), .B (n_309), .Q (n_344));
  NOR20 g3413(.A (n_307), .B (n_310), .Q (n_349));
  NOR20 g3414(.A (n_311), .B (n_309), .Q (n_345));
  NOR20 g3409(.A (n_308), .B (n_310), .Q (n_353));
  NOR20 g3418(.A (n_307), .B (n_306), .Q (n_346));
  DFC3 \O1_w_pointer_reg[1] (.RN (n_reset), .C (control_clk_miso), .D
       (n_265), .Q (O1_w_pointer[1]), .QN (n_219));
  DFP3 \O2_control_reg[1] (.SN (n_reset), .C (spi_clk), .D (n_266), .Q
       (O2_control[1]), .QN (UNCONNECTED130));
  NOR20 g3420(.A (n_305), .B (n_304), .Q (n_350));
  NOR20 g3421(.A (n_331), .B (n_233), .Q (n_367));
  NOR20 g3422(.A (n_331), .B (n_303), .Q (n_370));
  INV0 g3423(.A (n_325), .Q (n_302));
  NOR20 g3425(.A (n_308), .B (n_306), .Q (n_348));
  NOR20 g3426(.A (n_305), .B (n_306), .Q (n_347));
  NAND30 g3427(.A (n_300), .B (n_299), .C (spi_mosi_out), .Q (n_301));
  NOR20 g3419(.A (n_308), .B (n_304), .Q (n_351));
  INV0 g3416(.A (n_297), .Q (n_298));
  NOR20 g3408(.A (n_305), .B (n_309), .Q (n_343));
  INV0 g3388(.A (n_277), .Q (n_296));
  NOR20 g3390(.A (n_275), .B (n_294), .Q (n_295));
  IMUX20 g3397(.A (n_299), .B (n_292), .S (n_291), .Q (n_329));
  ADD22 g3352(.A (n_241), .B (O1_r_pointer[3]), .CO (n_316), .S
       (n_293));
  DFC3 \O2_spi_miso_out_reg[0] (.RN (n_reset), .C (control_clk_miso),
       .D (n_261), .Q (spi_miso_out[0]), .QN (UNCONNECTED131));
  DFC3 \O2_spi_miso_out_reg[3] (.RN (n_reset), .C (control_clk_miso),
       .D (n_263), .Q (spi_miso_out[3]), .QN (UNCONNECTED132));
  DFC3 \O2_spi_miso_out_reg[2] (.RN (n_reset), .C (control_clk_miso),
       .D (n_259), .Q (spi_miso_out[2]), .QN (UNCONNECTED133));
  TFSC1 \A_counter_reg[3] (.RN (n_reset), .C (m_clk), .SD
       (A_counter[3]), .SE (spi_cs), .Q (A_counter[3]), .QN
       (UNCONNECTED134));
  NAND20 g3410(.A (O2_point_add[0]), .B (n_292), .Q (n_327));
  NAND20 g3424(.A (n_291), .B (n_299), .Q (n_325));
  OAI210 g3429(.A (n_255), .B (O2_point_add[2]), .C (n_271), .Q
       (n_290));
  IMUX20 g3434(.A (O1_r_pointer[1]), .B (n_226), .S (n_288), .Q
       (n_289));
  XNR21 g3436(.A (O1_r_pointer[0]), .B (n_288), .Q (n_287));
  NOR20 g3446(.A (n_252), .B (n_249), .Q (n_337));
  NAND20 g3417(.A (n_286), .B (n_292), .Q (n_297));
  DFC3 \O2_spi_miso_out_reg[4] (.RN (n_reset), .C (control_clk_miso),
       .D (n_260), .Q (spi_miso_out[4]), .QN (UNCONNECTED135));
  NAND22 g3370(.A (n_284), .B (A_counter[2]), .Q (n_285));
  OAI212 g3377(.A (n_282), .B (A_counter[2]), .C (n_284), .Q (n_283));
  IMUX20 g3380(.A (O1_w_pointer[3]), .B (n_535), .S (n_274), .Q
       (n_281));
  IMUX20 g3382(.A (O1_r_pointer[2]), .B (n_242), .S (n_288), .Q
       (n_280));
  NOR20 g3386(.A (n_278), .B (n_264), .Q (n_279));
  AOI210 g3389(.A (n_665), .B (O1_w_full), .C (n_294), .Q (n_277));
  NOR20 g3393(.A (n_251), .B (n_294), .Q (n_276));
  DFC3 \O2_spi_miso_out_reg[1] (.RN (n_reset), .C (control_clk_miso),
       .D (n_258), .Q (spi_miso_out[1]), .QN (UNCONNECTED136));
  DFC3 \O2_spi_miso_out_reg[5] (.RN (n_reset), .C (control_clk_miso),
       .D (n_257), .Q (spi_miso_out[5]), .QN (UNCONNECTED137));
  DFC3 \O2_spi_miso_out_reg[6] (.RN (n_reset), .C (control_clk_miso),
       .D (n_262), .Q (spi_miso_out[6]), .QN (UNCONNECTED138));
  IMUX20 g3433(.A (O1_w_pointer[2]), .B (n_240), .S (n_274), .Q
       (n_275));
  NAND20 g3444(.A (n_273), .B (n_269), .Q (n_310));
  NAND20 g3445(.A (n_270), .B (O1_w_pointer[2]), .Q (n_309));
  NAND20 g3447(.A (n_273), .B (O1_w_pointer[2]), .Q (n_304));
  INV0 g3448(.A (n_271), .Q (n_272));
  NAND20 g3450(.A (n_270), .B (n_269), .Q (n_306));
  INV0 g3452(.A (n_361), .Q (n_268));
  INV0 g3454(.A (n_292), .Q (n_312));
  INV0 g3456(.A (n_299), .Q (n_331));
  NOR30 g3460(.A (n_362), .B (n_235), .C (spi_cs), .Q (n_334));
  NOR20 g3384(.A (O2_control[0]), .B (n_278), .Q (n_267));
  NOR20 g3385(.A (n_237), .B (n_278), .Q (n_266));
  NOR20 g3391(.A (n_245), .B (n_294), .Q (n_265));
  INV2 g3396(.A (n_284), .Q (n_318));
  INV0 g3430(.A (n_243), .Q (n_264));
  NOR20 g3437(.A (spi_cs), .B (n_597), .Q (n_263));
  NOR20 g3438(.A (spi_cs), .B (n_615), .Q (n_262));
  NOR20 g3439(.A (spi_cs), .B (n_657), .Q (n_261));
  NOR20 g3440(.A (spi_cs), .B (n_582), .Q (n_260));
  NOR20 g3441(.A (spi_cs), .B (n_636), .Q (n_259));
  NOR20 g3442(.A (spi_cs), .B (n_591), .Q (n_258));
  NOR20 g3443(.A (spi_cs), .B (n_551), .Q (n_257));
  NOR20 g3449(.A (spi_cs), .B (n_286), .Q (n_271));
  NOR20 g3451(.A (spi_cs), .B (n_398), .Q (n_256));
  NOR20 g3453(.A (spi_cs), .B (n_291), .Q (n_361));
  NOR20 g3455(.A (control_clk_miso), .B (spi_cs), .Q (n_292));
  NOR20 g3457(.A (spi_cs), .B (n_255), .Q (n_299));
  NOR21 g3458(.A (spi_cs), .B (n_113), .Q (n_284));
  AOI210 g3459(.A (n_253), .B (control_clk_miso), .C (spi_cs), .Q
       (n_254));
  INV0 g3464(.A (n_270), .Q (n_252));
  IMUX20 g3467(.A (n_274), .B (n_248), .S (O1_w_pointer[0]), .Q
       (n_251));
  NOR21 g3461(.A (O1_rinc), .B (O1_r_empty), .Q (n_288));
  NOR30 g3463(.A (n_248), .B (n_247), .C (n_246), .Q (n_273));
  NOR30 g3465(.A (n_248), .B (O1_w_pointer[3]), .C (n_246), .Q (n_270));
  IMUX20 g3466(.A (O1_w_pointer[1]), .B (n_234), .S (n_274), .Q
       (n_245));
  ADD21 g3431(.A (n_227), .B (O2_control[2]), .CO (n_278), .S (n_243));
  ADD22 g3432(.A (n_225), .B (O1_r_pointer[2]), .CO (n_241), .S
       (n_242));
  NOR30 g3428(.A (n_249), .B (n_247), .C (O1_winc), .Q (n_294));
  NAND20 g3470(.A (n_362), .B (n_291), .Q (n_300));
  IMUX20 g3474(.A (O1_w_pointer[2]), .B (n_269), .S (n_307), .Q
       (n_240));
  DFC3 O1_rinc_reg(.RN (n_reset), .C (m_clk), .D (n_536), .Q
       (UNCONNECTED139), .QN (O1_rinc));
  NOR21 g3480(.A (A_counter[2]), .B (n_232), .Q (n_239));
  INV0 g3482(.A (n_274), .Q (n_248));
  DFC3 O1_spi_cs_reg(.RN (n_reset), .C (m_clk), .D (n_120), .Q
       (spi_cs), .QN (UNCONNECTED140));
  AOI210 g3462(.A (O2_point_add[2]), .B (spi_mosi_out), .C (n_229), .Q
       (n_238));
  INV0 g3471(.A (n_228), .Q (n_237));
  INV0 g3476(.A (n_236), .Q (n_362));
  INV0 g3478(.A (n_291), .Q (n_235));
  NAND20 g3481(.A (n_230), .B (O1_w_pointer[2]), .Q (n_249));
  NOR20 g3483(.A (O1_winc), .B (O1_w_full), .Q (n_274));
  NAND20 g3484(.A (n_305), .B (n_308), .Q (n_234));
  INV0 g3602(.A (n_398), .Q (n_233));
  INV2 g3593(.A (n_319), .Q (n_232));
  NOR20 g3477(.A (n_330), .B (n_340), .Q (n_236));
  NOR20 g3479(.A (n_286), .B (n_253), .Q (n_291));
  INV0 g3598(.A (n_230), .Q (n_307));
  INV0 g3604(.A (n_303), .Q (n_390));
  INV0 g3606(.A (n_229), .Q (n_322));
  ADD21 g3472(.A (O2_control[0]), .B (O2_control[1]), .CO (n_227), .S
       (n_228));
  ADD22 g3473(.A (O1_r_pointer[0]), .B (O1_r_pointer[1]), .CO (n_225),
       .S (n_226));
  NOR20 g3561(.A (n_246), .B (n_595), .Q (n_224));
  NOR20 g3524(.A (n_246), .B (n_660), .Q (n_223));
  NOR20 g3525(.A (n_246), .B (n_662), .Q (n_222));
  NOR20 g3567(.A (n_246), .B (n_556), .Q (n_221));
  NOR20 g3599(.A (n_219), .B (n_119), .Q (n_230));
  NOR20 g3580(.A (n_246), .B (n_651), .Q (n_220));
  NAND20 g3608(.A (O1_w_pointer[0]), .B (n_219), .Q (n_308));
  NOR20 g3607(.A (O2_point_add[1]), .B (n_585), .Q (n_229));
  NAND20 g3603(.A (n_118), .B (O2_point[1]), .Q (n_398));
  NOR20 g3551(.A (n_246), .B (n_621), .Q (n_218));
  NOR20 g3515(.A (n_246), .B (n_559), .Q (n_217));
  NOR20 g3564(.A (n_246), .B (n_563), .Q (n_216));
  NAND22 g3594(.A (n_282), .B (A_counter[0]), .Q (n_319));
  NOR20 g3591(.A (n_246), .B (n_557), .Q (n_215));
  NOR20 g3588(.A (n_246), .B (n_624), .Q (n_214));
  NOR20 g3589(.A (n_246), .B (n_654), .Q (n_213));
  NOR20 g3511(.A (n_246), .B (n_584), .Q (n_212));
  NOR20 g3585(.A (n_246), .B (n_626), .Q (n_211));
  NOR20 g3509(.A (n_246), .B (n_625), .Q (n_210));
  DFC3 O1_winc_reg(.RN (n_reset), .C (m_clk), .D (n_209), .Q
       (UNCONNECTED141), .QN (O1_winc));
  NOR20 g3488(.A (n_246), .B (n_555), .Q (n_208));
  NOR20 g3489(.A (n_246), .B (n_608), .Q (n_207));
  NOR20 g3490(.A (n_246), .B (n_630), .Q (n_206));
  NOR20 g3491(.A (n_246), .B (n_647), .Q (n_205));
  NOR20 g3492(.A (n_246), .B (n_578), .Q (n_204));
  NOR20 g3493(.A (n_246), .B (n_616), .Q (n_203));
  NOR20 g3494(.A (n_246), .B (n_659), .Q (n_202));
  NOR20 g3495(.A (n_246), .B (n_568), .Q (n_201));
  NOR20 g3496(.A (n_246), .B (n_641), .Q (n_200));
  NOR20 g3497(.A (n_246), .B (n_622), .Q (n_199));
  NOR20 g3498(.A (n_246), .B (n_575), .Q (n_198));
  NOR20 g3499(.A (n_246), .B (n_579), .Q (n_197));
  NOR20 g3500(.A (n_246), .B (n_573), .Q (n_196));
  NOR20 g3502(.A (n_246), .B (n_611), .Q (n_195));
  NOR20 g3503(.A (n_246), .B (n_594), .Q (n_194));
  NOR20 g3504(.A (n_246), .B (n_628), .Q (n_193));
  NOR20 g3505(.A (n_246), .B (n_601), .Q (n_192));
  NOR20 g3506(.A (n_246), .B (n_648), .Q (n_191));
  NOR20 g3583(.A (n_246), .B (n_656), .Q (n_190));
  NOR20 g3507(.A (n_246), .B (n_635), .Q (n_189));
  NOR20 g3508(.A (n_246), .B (n_564), .Q (n_188));
  NOR20 g3510(.A (n_246), .B (n_602), .Q (n_187));
  NOR20 g3512(.A (n_246), .B (n_623), .Q (n_186));
  NOR20 g3513(.A (n_246), .B (n_617), .Q (n_185));
  NOR20 g3514(.A (n_246), .B (n_609), .Q (n_184));
  NOR20 g3516(.A (n_246), .B (n_661), .Q (n_183));
  NOR20 g3517(.A (n_246), .B (n_618), .Q (n_182));
  NOR20 g3518(.A (n_246), .B (n_663), .Q (n_181));
  NOR20 g3519(.A (n_246), .B (n_613), .Q (n_180));
  NOR20 g3520(.A (n_246), .B (n_632), .Q (n_179));
  NOR20 g3521(.A (n_246), .B (n_576), .Q (n_178));
  NOR20 g3522(.A (n_246), .B (n_599), .Q (n_177));
  NOR20 g3523(.A (n_246), .B (n_572), .Q (n_176));
  NOR20 g3581(.A (n_246), .B (n_652), .Q (n_175));
  NOR20 g3526(.A (n_246), .B (n_653), .Q (n_174));
  NOR20 g3527(.A (n_246), .B (n_619), .Q (n_173));
  NOR20 g3528(.A (n_246), .B (n_646), .Q (n_172));
  NOR20 g3529(.A (n_246), .B (n_620), .Q (n_171));
  NOR20 g3530(.A (n_246), .B (n_658), .Q (n_170));
  NOR20 g3531(.A (n_246), .B (n_649), .Q (n_169));
  NOR20 g3532(.A (n_246), .B (n_583), .Q (n_168));
  NOR20 g3533(.A (n_246), .B (n_604), .Q (n_167));
  NOR20 g3534(.A (n_246), .B (n_600), .Q (n_166));
  NOR20 g3535(.A (n_246), .B (n_554), .Q (n_165));
  NOR20 g3536(.A (n_246), .B (n_640), .Q (n_164));
  NOR20 g3537(.A (n_246), .B (n_639), .Q (n_163));
  NOR20 g3538(.A (n_246), .B (n_614), .Q (n_162));
  NOR20 g3539(.A (n_246), .B (n_574), .Q (n_161));
  NOR20 g3540(.A (n_246), .B (n_642), .Q (n_160));
  NOR20 g3541(.A (n_246), .B (n_638), .Q (n_159));
  NOR20 g3542(.A (n_246), .B (n_558), .Q (n_158));
  NOR20 g3543(.A (n_246), .B (n_637), .Q (n_157));
  NOR20 g3544(.A (n_246), .B (n_561), .Q (n_156));
  NOR20 g3545(.A (n_246), .B (n_610), .Q (n_155));
  NOR20 g3546(.A (n_246), .B (n_571), .Q (n_154));
  NOR20 g3547(.A (n_246), .B (n_567), .Q (n_153));
  NOR20 g3548(.A (n_246), .B (n_577), .Q (n_152));
  NOR20 g3549(.A (n_246), .B (n_655), .Q (n_151));
  NOR20 g3550(.A (n_246), .B (n_589), .Q (n_150));
  NOR20 g3552(.A (n_246), .B (n_562), .Q (n_149));
  NOR20 g3553(.A (n_246), .B (n_570), .Q (n_148));
  NOR20 g3554(.A (n_246), .B (n_552), .Q (n_147));
  NOR20 g3555(.A (n_246), .B (n_645), .Q (n_146));
  NOR20 g3556(.A (n_246), .B (n_631), .Q (n_145));
  NOR20 g3557(.A (n_246), .B (n_634), .Q (n_144));
  NOR20 g3558(.A (n_246), .B (n_627), .Q (n_143));
  NOR20 g3559(.A (n_246), .B (n_650), .Q (n_142));
  NOR20 g3560(.A (n_246), .B (n_587), .Q (n_141));
  NOR20 g3579(.A (n_246), .B (n_586), .Q (n_140));
  NOR20 g3562(.A (n_246), .B (n_606), .Q (n_139));
  NOR20 g3563(.A (n_246), .B (n_569), .Q (n_138));
  NOR20 g3565(.A (n_246), .B (n_633), .Q (n_137));
  NOR20 g3566(.A (n_246), .B (n_629), .Q (n_136));
  NOR20 g3568(.A (n_246), .B (n_664), .Q (n_135));
  NOR20 g3569(.A (n_246), .B (n_553), .Q (n_134));
  NOR20 g3570(.A (n_246), .B (n_592), .Q (n_133));
  NOR20 g3572(.A (n_246), .B (n_580), .Q (n_132));
  NOR20 g3574(.A (n_246), .B (n_643), .Q (n_131));
  NOR20 g3575(.A (n_246), .B (n_590), .Q (n_130));
  NOR20 g3577(.A (n_246), .B (n_644), .Q (n_129));
  NOR20 g3576(.A (n_246), .B (n_565), .Q (n_128));
  NOR20 g3578(.A (n_246), .B (n_560), .Q (n_127));
  NOR20 g3582(.A (n_246), .B (n_598), .Q (n_126));
  NOR20 g3584(.A (n_246), .B (n_612), .Q (n_125));
  NOR20 g3586(.A (n_246), .B (n_605), .Q (n_124));
  NOR20 g3587(.A (n_246), .B (n_588), .Q (n_123));
  NOR20 g3590(.A (n_246), .B (n_593), .Q (n_122));
  NOR20 g3592(.A (n_246), .B (n_566), .Q (n_121));
  NOR21 g3595(.A (n_209), .B (O1_r_empty), .Q (n_120));
  NAND20 g3596(.A (n_119), .B (n_219), .Q (n_311));
  NOR20 g3605(.A (O2_point[1]), .B (n_118), .Q (n_303));
  NAND20 g3609(.A (n_119), .B (O1_w_pointer[1]), .Q (n_305));
  NOR20 g3501(.A (n_246), .B (n_596), .Q (n_117));
  NOR20 g3573(.A (n_246), .B (n_581), .Q (n_116));
  NOR20 g3571(.A (n_246), .B (n_603), .Q (n_115));
  DFC3 O1_read_en_reg(.RN (n_reset), .C (read_req), .D (O1_w_full), .Q
       (UNCONNECTED142), .QN (O1_read_en));
  NOR20 g3601(.A (O2_point[1]), .B (O2_point[0]), .Q (n_388));
  NAND20 g3597(.A (O2_point_add[1]), .B (O2_point_add[2]), .Q (n_253));
  NAND20 g3600(.A (O2_point[0]), .B (O2_point[1]), .Q (n_340));
  INV2 g3616(.A (A_counter[3]), .Q (n_113));
  CLKIN2 g3614(.A (A_counter[1]), .Q (n_282));
  CLKIN6 g3663(.A (n_reset), .Q (n_246));
  NAND22 g2(.A (n_247), .B (n_249), .Q (n_535));
  NOR21 g4013(.A (O1_read_en), .B (n_209), .Q (n_536));
endmodule

