`timescale 1 ns / 1 ps
// Generated by Cadence Encounter(R) RTL Compiler v11.20-s017_1

// Verification Directory fv/spi_mosi 

module spi_mosi(control_clk, spi_mosi_out, spi_cs, spi_clk, n_reset,
     spi_mosi_in);
  input spi_cs, spi_clk, n_reset;
  input [7:0] spi_mosi_in;
  output control_clk, spi_mosi_out;
  wire spi_cs, spi_clk, n_reset;
  wire [7:0] spi_mosi_in;
  wire control_clk, spi_mosi_out;
  wire [3:0] point_add;
  wire [2:0] point;
  wire [7:0] data;
  wire [2:0] control;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_88, n_89;
  wire n_90;
  DFC3 spi_mosi_out_reg(.RN (n_reset), .C (spi_clk), .D (n_75), .Q
       (spi_mosi_out), .QN (n_89));
  OAI212 g1716(.A (n_60), .B (n_28), .C (n_74), .Q (n_75));
  NAND22 g1717(.A (n_73), .B (n_65), .Q (n_74));
  OAI212 g1718(.A (point_add[1]), .B (n_72), .C (n_23), .Q (n_73));
  IMUX21 g1719(.A (n_29), .B (n_71), .S (point_add[3]), .Q (n_72));
  AOI2111 g1720(.A (n_62), .B (point[2]), .C (point_add[0]), .D (n_70),
       .Q (n_71));
  DFC3 \point_add_reg[3] (.RN (n_reset), .C (spi_clk), .D (n_69), .Q
       (point_add[3]), .QN (n_88));
  MUX22 g1722(.A (n_89), .B (n_68), .S (control_clk), .Q (n_70));
  OAI212 g1727(.A (spi_cs), .B (n_31), .C (n_66), .Q (n_69));
  DFC3 \point_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_67), .Q
       (point[1]), .QN (UNCONNECTED));
  DFC3 \point_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_64), .Q
       (point[0]), .QN (n_11));
  AOI2111 g1732(.A (n_51), .B (data[1]), .C (point[2]), .D (n_55), .Q
       (n_68));
  DFC3 \point_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_59), .Q
       (point[2]), .QN (n_90));
  OAI221 g1733(.A (n_56), .B (spi_cs), .C (n_63), .D (n_49), .Q (n_67));
  AOI311 g1734(.A (point_add[3]), .B (point_add[1]), .C (n_65), .D
       (n_61), .Q (n_66));
  OAI222 g1735(.A (n_53), .B (spi_cs), .C (n_63), .D (point[0]), .Q
       (n_64));
  AOI211 g1742(.A (n_21), .B (spi_mosi_out), .C (n_50), .Q (n_62));
  DFC3 \control_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_58), .Q
       (control[2]), .QN (UNCONNECTED0));
  NOR21 g1739(.A (n_60), .B (n_46), .Q (n_61));
  TFEC3 control_clk_reg(.RN (n_reset), .C (spi_clk), .T (n_57), .Q
       (control_clk), .QN (n_38));
  OAI311 g1731(.A (point[2]), .B (n_54), .C (n_63), .D (n_42), .Q
       (n_59));
  DFP3 \control_reg[1] (.SN (n_reset), .C (spi_clk), .D (n_48), .Q
       (control[1]), .QN (UNCONNECTED1));
  DFC3 \control_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_43), .Q
       (control[0]), .QN (UNCONNECTED2));
  DFC3 \point_add_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_44), .Q
       (point_add[1]), .QN (UNCONNECTED3));
  DFP3 \point_add_reg[0] (.SN (n_reset), .C (spi_clk), .D (n_47), .Q
       (point_add[0]), .QN (n_10));
  NOR21 g1741(.A (n_57), .B (n_41), .Q (n_58));
  OAI212 g1746(.A (n_11), .B (n_52), .C (point[1]), .Q (n_56));
  OAI222 g1747(.A (n_34), .B (point[0]), .C (n_54), .D (data[3]), .Q
       (n_55));
  AOI221 g1748(.A (n_52), .B (point[0]), .C (n_51), .D (n_38), .Q
       (n_53));
  OAI222 g1751(.A (n_35), .B (point[0]), .C (n_49), .D (data[5]), .Q
       (n_50));
  DFSP1 \point_add_reg[2] (.SN (n_reset), .C (spi_clk), .D (n_22), .SD
       (n_65), .SE (n_45), .Q (point_add[2]), .QN (UNCONNECTED4));
  NOR21 g1740(.A (n_25), .B (n_57), .Q (n_48));
  NOR21 g1744(.A (spi_cs), .B (n_39), .Q (n_47));
  XNR21 g1752(.A (point_add[3]), .B (n_45), .Q (n_46));
  NOR21 g1753(.A (spi_cs), .B (n_36), .Q (n_44));
  NOR21 g1738(.A (control[0]), .B (n_57), .Q (n_43));
  OAI2111 g1745(.A (n_54), .B (n_30), .C (point[2]), .D (n_40), .Q
       (n_42));
  INV3 g1749(.A (n_33), .Q (n_41));
  NAND31 g1754(.A (n_37), .B (control_clk), .C (n_40), .Q (n_63));
  IMUX21 g1755(.A (point_add[0]), .B (n_27), .S (n_38), .Q (n_39));
  OAI212 g1757(.A (control_clk), .B (point[2]), .C (n_37), .Q (n_52));
  INV3 g1758(.A (n_32), .Q (n_36));
  IMUX21 g1760(.A (data[4]), .B (data[6]), .S (point[1]), .Q (n_35));
  IMUX21 g1761(.A (data[0]), .B (data[2]), .S (point[1]), .Q (n_34));
  ADD22 g1750(.A (n_19), .B (control[2]), .CO (n_57), .S (n_33));
  ADD22 g1759(.A (n_24), .B (point_add[1]), .CO (n_45), .S (n_32));
  OAI311 g1756(.A (point_add[0]), .B (n_90), .C (n_54), .D (n_26), .Q
       (n_31));
  INV3 g1763(.A (n_30), .Q (n_37));
  INV2 g1776(.A (n_28), .Q (n_29));
  DFC3 \data_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_13), .Q
       (data[1]), .QN (UNCONNECTED5));
  NOR21 g1762(.A (point_add[0]), .B (n_26), .Q (n_27));
  NAND22 g1764(.A (n_26), .B (n_10), .Q (n_30));
  INV3 g1765(.A (n_20), .Q (n_25));
  DFC3 \data_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_12), .Q
       (data[2]), .QN (UNCONNECTED6));
  DFC1 \data_reg[3] (.RN (n_reset), .C (spi_clk), .D (n_18), .Q
       (UNCONNECTED7), .QN (data[3]));
  DFC3 \data_reg[4] (.RN (n_reset), .C (spi_clk), .D (n_17), .Q
       (data[4]), .QN (UNCONNECTED8));
  DFC3 \data_reg[5] (.RN (n_reset), .C (spi_clk), .D (n_16), .Q
       (UNCONNECTED9), .QN (data[5]));
  DFC3 \data_reg[6] (.RN (n_reset), .C (spi_clk), .D (n_15), .Q
       (data[6]), .QN (UNCONNECTED10));
  DFC3 \data_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_14), .Q
       (data[0]), .QN (UNCONNECTED11));
  AOI211 g1777(.A (spi_mosi_out), .B (control_clk), .C (n_24), .Q
       (n_28));
  OAI222 g1778(.A (point_add[1]), .B (point_add[0]), .C (spi_mosi_out),
       .D (n_38), .Q (n_23));
  INV1 g1780(.A (n_60), .Q (n_22));
  INV3 g1790(.A (n_51), .Q (n_49));
  NAND22 g1774(.A (n_54), .B (control_clk), .Q (n_21));
  ADD22 g1766(.A (control[0]), .B (control[1]), .CO (n_19), .S (n_20));
  NAND22 g1781(.A (point_add[2]), .B (n_40), .Q (n_60));
  NOR21 g1782(.A (spi_cs), .B (n_9), .Q (n_18));
  NOR21 g1783(.A (spi_cs), .B (n_6), .Q (n_17));
  NOR21 g1784(.A (spi_cs), .B (n_2), .Q (n_16));
  NOR21 g1785(.A (spi_cs), .B (n_5), .Q (n_15));
  NOR21 g1786(.A (spi_cs), .B (n_4), .Q (n_14));
  NOR21 g1787(.A (spi_cs), .B (n_1), .Q (n_13));
  NOR21 g1788(.A (spi_cs), .B (n_3), .Q (n_12));
  NOR21 g1791(.A (n_11), .B (point[1]), .Q (n_51));
  NOR21 g1792(.A (control_clk), .B (n_10), .Q (n_24));
  NOR31 g1775(.A (n_88), .B (point_add[1]), .C (point_add[2]), .Q
       (n_26));
  NAND22 g1789(.A (point[1]), .B (point[0]), .Q (n_54));
  NOR21 g1779(.A (spi_cs), .B (point_add[2]), .Q (n_65));
  INV3 g1805(.A (spi_mosi_in[3]), .Q (n_9));
  INV3 g1801(.A (spi_mosi_in[4]), .Q (n_6));
  INV3 g1804(.A (spi_mosi_in[6]), .Q (n_5));
  INV3 g1796(.A (spi_cs), .Q (n_40));
  INV3 g1797(.A (spi_mosi_in[0]), .Q (n_4));
  INV3 g1799(.A (spi_mosi_in[2]), .Q (n_3));
  INV3 g1802(.A (spi_mosi_in[5]), .Q (n_2));
  INV3 g1794(.A (spi_mosi_in[1]), .Q (n_1));
endmodule

