# ####################################################################

#  Created by Encounter(R) RTL Compiler v11.20-s017_1 on Tue Jul 19 16:32:42 +0200 2016

# ####################################################################

set sdc_version 1.7

set_units -capacitance 1000.0fF
set_units -time 1000.0ps

# Set the current design
current_design spi_final_O

create_clock -name "m_clk" -add -period 50.0 -waveform {0.0 25.0} [get_ports m_clk]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks m_clk] -add_delay 0.0 [get_ports n_reset]
set_input_delay -clock [get_clocks m_clk] -add_delay 0.0 [get_ports m_clk]
set_input_delay -clock [get_clocks m_clk] -add_delay 0.0 [get_ports read_req]
set_input_delay -clock [get_clocks m_clk] -add_delay 0.0 [get_ports spi_miso_in]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports spi_mosi_out]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[0]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[1]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[2]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[3]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[4]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[5]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[6]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[7]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[8]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[9]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[10]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[11]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[12]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[13]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[14]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[15]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[16]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[17]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[18]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[19]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[20]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[21]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[22]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[23]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[24]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[25]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[26]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[27]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[28]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[29]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[30]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[31]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[32]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[33]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[34]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[35]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[36]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[37]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[38]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[39]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[40]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[41]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[42]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[43]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[44]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[45]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[46]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[47]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[48]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[49]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[50]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[51]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[52]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[53]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[54]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[55]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[56]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[57]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[58]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[59]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[60]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[61]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[62]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[63]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[64]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[65]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[66]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[67]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[68]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[69]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[70]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[71]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[72]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[73]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[74]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[75]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[76]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[77]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[78]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[79]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[80]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[81]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[82]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[83]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[84]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[85]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[86]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[87]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[88]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[89]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[90]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[91]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[92]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[93]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[94]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[95]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[96]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[97]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[98]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[99]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[100]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[101]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[102]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[103]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[104]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[105]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[106]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[107]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[108]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[109]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[110]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[111]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[112]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[113]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[114]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[115]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[116]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[117]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[118]}]
set_output_delay -clock [get_clocks m_clk] -add_delay 0.002 [get_ports {data_out[119]}]
set_ideal_net [get_nets spi_miso_in]
set_ideal_net [get_nets read_req]
set_ideal_net [get_nets m_clk]
set_ideal_net [get_nets n_reset]
set_ideal_net [get_nets spi_mosi_out]
set_ideal_net [get_nets {data_out[65]}]
set_ideal_net [get_nets {data_out[90]}]
set_ideal_net [get_nets {data_out[71]}]
set_ideal_net [get_nets {data_out[111]}]
set_ideal_net [get_nets {data_out[79]}]
set_ideal_net [get_nets {data_out[7]}]
set_ideal_net [get_nets {data_out[119]}]
set_ideal_net [get_nets {data_out[55]}]
set_ideal_net [get_nets {data_out[5]}]
set_ideal_net [get_nets {data_out[87]}]
set_ideal_net [get_nets {data_out[95]}]
set_ideal_net [get_nets {data_out[103]}]
set_ideal_net [get_nets {data_out[104]}]
set_ideal_net [get_nets {data_out[63]}]
set_ideal_net [get_nets {data_out[15]}]
set_ideal_net [get_nets {data_out[102]}]
set_ideal_net [get_nets {data_out[47]}]
set_ideal_net [get_nets {data_out[19]}]
set_ideal_net [get_nets {data_out[17]}]
set_ideal_net [get_nets {data_out[11]}]
set_ideal_net [get_nets {data_out[49]}]
set_ideal_net [get_nets {data_out[44]}]
set_ideal_net [get_nets {data_out[82]}]
set_ideal_net [get_nets {data_out[40]}]
set_ideal_net [get_nets {data_out[115]}]
set_ideal_net [get_nets {data_out[76]}]
set_ideal_net [get_nets {data_out[32]}]
set_ideal_net [get_nets {data_out[28]}]
set_ideal_net [get_nets {data_out[110]}]
set_ideal_net [get_nets {data_out[68]}]
set_ideal_net [get_nets {data_out[1]}]
set_ideal_net [get_nets {data_out[20]}]
set_ideal_net [get_nets {data_out[21]}]
set_ideal_net [get_nets {data_out[22]}]
set_ideal_net [get_nets {data_out[24]}]
set_ideal_net [get_nets {data_out[25]}]
set_ideal_net [get_nets {data_out[26]}]
set_ideal_net [get_nets {data_out[27]}]
set_ideal_net [get_nets {data_out[29]}]
set_ideal_net [get_nets {data_out[2]}]
set_ideal_net [get_nets {data_out[30]}]
set_ideal_net [get_nets {data_out[33]}]
set_ideal_net [get_nets {data_out[34]}]
set_ideal_net [get_nets {data_out[35]}]
set_ideal_net [get_nets {data_out[36]}]
set_ideal_net [get_nets {data_out[37]}]
set_ideal_net [get_nets {data_out[38]}]
set_ideal_net [get_nets {data_out[3]}]
set_ideal_net [get_nets {data_out[41]}]
set_ideal_net [get_nets {data_out[42]}]
set_ideal_net [get_nets {data_out[43]}]
set_ideal_net [get_nets {data_out[45]}]
set_ideal_net [get_nets {data_out[46]}]
set_ideal_net [get_nets {data_out[48]}]
set_ideal_net [get_nets {data_out[4]}]
set_ideal_net [get_nets {data_out[100]}]
set_ideal_net [get_nets {data_out[50]}]
set_ideal_net [get_nets {data_out[51]}]
set_ideal_net [get_nets {data_out[101]}]
set_ideal_net [get_nets {data_out[52]}]
set_ideal_net [get_nets {data_out[53]}]
set_ideal_net [get_nets {data_out[54]}]
set_ideal_net [get_nets {data_out[56]}]
set_ideal_net [get_nets {data_out[57]}]
set_ideal_net [get_nets {data_out[58]}]
set_ideal_net [get_nets {data_out[59]}]
set_ideal_net [get_nets {data_out[105]}]
set_ideal_net [get_nets {data_out[60]}]
set_ideal_net [get_nets {data_out[106]}]
set_ideal_net [get_nets {data_out[61]}]
set_ideal_net [get_nets {data_out[62]}]
set_ideal_net [get_nets {data_out[107]}]
set_ideal_net [get_nets {data_out[64]}]
set_ideal_net [get_nets {data_out[108]}]
set_ideal_net [get_nets {data_out[66]}]
set_ideal_net [get_nets {data_out[109]}]
set_ideal_net [get_nets {data_out[67]}]
set_ideal_net [get_nets {data_out[10]}]
set_ideal_net [get_nets {data_out[69]}]
set_ideal_net [get_nets {data_out[6]}]
set_ideal_net [get_nets {data_out[70]}]
set_ideal_net [get_nets {data_out[72]}]
set_ideal_net [get_nets {data_out[73]}]
set_ideal_net [get_nets {data_out[112]}]
set_ideal_net [get_nets {data_out[74]}]
set_ideal_net [get_nets {data_out[75]}]
set_ideal_net [get_nets {data_out[113]}]
set_ideal_net [get_nets {data_out[77]}]
set_ideal_net [get_nets {data_out[114]}]
set_ideal_net [get_nets {data_out[78]}]
set_ideal_net [get_nets {data_out[80]}]
set_ideal_net [get_nets {data_out[81]}]
set_ideal_net [get_nets {data_out[116]}]
set_ideal_net [get_nets {data_out[83]}]
set_ideal_net [get_nets {data_out[117]}]
set_ideal_net [get_nets {data_out[84]}]
set_ideal_net [get_nets {data_out[85]}]
set_ideal_net [get_nets {data_out[118]}]
set_ideal_net [get_nets {data_out[86]}]
set_ideal_net [get_nets {data_out[88]}]
set_ideal_net [get_nets {data_out[89]}]
set_ideal_net [get_nets {data_out[8]}]
set_ideal_net [get_nets {data_out[12]}]
set_ideal_net [get_nets {data_out[91]}]
set_ideal_net [get_nets {data_out[13]}]
set_ideal_net [get_nets {data_out[92]}]
set_ideal_net [get_nets {data_out[93]}]
set_ideal_net [get_nets {data_out[14]}]
set_ideal_net [get_nets {data_out[94]}]
set_ideal_net [get_nets {data_out[96]}]
set_ideal_net [get_nets {data_out[97]}]
set_ideal_net [get_nets {data_out[16]}]
set_ideal_net [get_nets {data_out[98]}]
set_ideal_net [get_nets {data_out[99]}]
set_ideal_net [get_nets {data_out[9]}]
set_ideal_net [get_nets {data_out[18]}]
set_ideal_net [get_nets {data_out[23]}]
set_ideal_net [get_nets {data_out[31]}]
set_ideal_net [get_nets {data_out[39]}]
set_ideal_net [get_nets spi_cs]
set_wire_load_mode "enclosed"
set_wire_load_selection_group "sub_micron" -library "c35_CORELIB_TYP"
set_dont_use [get_lib_cells c35_CORELIB_TYP/DLY12]
set_dont_use [get_lib_cells c35_CORELIB_TYP/DLY22]
set_dont_use [get_lib_cells c35_CORELIB_TYP/DLY32]
set_dont_use [get_lib_cells c35_CORELIB_TYP/DLY42]
set_dont_use [get_lib_cells c35_CORELIB_TYP/BUSHD]
set_dont_use [get_lib_cells c35_CORELIB_TYP/TIE0]
set_dont_use [get_lib_cells c35_CORELIB_TYP/TIE1]
set_dont_use [get_lib_cells c35_CORELIB_TYP/TIELOW]
set_dont_use [get_lib_cells c35_CORELIB_TYP/TIEHIGH]
set_dont_use [get_lib_cells c35_CORELIB_TYP/FILLANT1]
set_dont_use [get_lib_cells c35_CORELIB_TYP/FILLANT2]
set_dont_use [get_lib_cells c35_CORELIB_TYP/FILLANT5]
set_dont_use [get_lib_cells c35_CORELIB_TYP/FILLANT10]
set_dont_use [get_lib_cells c35_CORELIB_TYP/FILLANT25]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCD24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBCU24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBC24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSD24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBSU24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBS24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTD24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBTU24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BBT24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT2P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT12P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT12SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT12SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BT24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDD1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDD2P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDD4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDD8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDD12P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDD16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDD24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDU1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDU2P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDU4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDU8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDU12P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDU16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BUDU24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU2P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU4SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU8SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU8SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU12P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU12SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU12SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU16SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU16SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU24P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU24SMP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/BU24SP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/CBU1P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/CBU2P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ICCK2P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ICCK4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ICCK8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ICCK16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ICDP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ICP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ICUP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ISDP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ISP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ISUP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ITCK2P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ITCK4P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ITCK8P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ITCK16P]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ITDP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ITP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/ITUP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/GND3ALLP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/GND3IP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/GND3OP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/GND3RP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/VDD3ALLP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/VDD3IP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/VDD3OP]
set_dont_use [get_lib_cells c35_IOLIB_TYP/VDD3RP]
