`timescale 1 ns / 1 ps
// Generated by Cadence Encounter(R) RTL Compiler v11.20-s017_1

// Verification Directory fv/spi_final_O 

module spi_final_O(data_out, spi_mosi_out, spi_miso_in, read_req,
     m_clk, n_reset);
  input spi_miso_in, read_req, m_clk, n_reset;
  output [119:0] data_out;
  output spi_mosi_out;
  wire spi_miso_in, read_req, m_clk, n_reset;
  wire [119:0] data_out;
  wire spi_mosi_out;
  wire [7:0] O2_data;
  wire [0:3] A_counter;
  wire [2:0] O2_point_add;
  wire [2:0] O2_point;
  wire [3:0] O1_r_pointer;
  wire [7:0] spi_miso_out;
  wire [3:0] O1_w_pointer;
  wire [2:0] O2_control;
  wire O1_r_empty, O1_read_en, O1_rinc, O1_w_full, O1_winc,
       UNCONNECTED, UNCONNECTED0, UNCONNECTED1;
  wire UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5,
       UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9;
  wire UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13,
       UNCONNECTED14, UNCONNECTED15, UNCONNECTED16, UNCONNECTED17;
  wire UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, UNCONNECTED25;
  wire UNCONNECTED26, UNCONNECTED27, UNCONNECTED28, UNCONNECTED29,
       UNCONNECTED30, UNCONNECTED31, UNCONNECTED32, UNCONNECTED33;
  wire UNCONNECTED34, UNCONNECTED35, UNCONNECTED36, UNCONNECTED37,
       UNCONNECTED38, UNCONNECTED39, UNCONNECTED40, UNCONNECTED41;
  wire UNCONNECTED42, UNCONNECTED43, UNCONNECTED44, UNCONNECTED45,
       UNCONNECTED46, UNCONNECTED47, UNCONNECTED48, UNCONNECTED49;
  wire UNCONNECTED50, UNCONNECTED51, UNCONNECTED52, UNCONNECTED53,
       UNCONNECTED54, UNCONNECTED55, UNCONNECTED56, UNCONNECTED57;
  wire UNCONNECTED58, UNCONNECTED59, UNCONNECTED60, UNCONNECTED61,
       UNCONNECTED62, UNCONNECTED63, UNCONNECTED64, UNCONNECTED65;
  wire UNCONNECTED66, UNCONNECTED67, UNCONNECTED68, UNCONNECTED69,
       UNCONNECTED70, UNCONNECTED71, UNCONNECTED72, UNCONNECTED73;
  wire UNCONNECTED74, UNCONNECTED75, UNCONNECTED76, UNCONNECTED77,
       UNCONNECTED78, UNCONNECTED79, UNCONNECTED80, UNCONNECTED81;
  wire UNCONNECTED82, UNCONNECTED83, UNCONNECTED84, UNCONNECTED85,
       UNCONNECTED86, UNCONNECTED87, UNCONNECTED88, UNCONNECTED89;
  wire UNCONNECTED90, UNCONNECTED91, UNCONNECTED92, UNCONNECTED93,
       UNCONNECTED94, UNCONNECTED95, UNCONNECTED96, UNCONNECTED97;
  wire UNCONNECTED98, UNCONNECTED99, UNCONNECTED100, UNCONNECTED101,
       UNCONNECTED102, UNCONNECTED103, UNCONNECTED104, UNCONNECTED105;
  wire UNCONNECTED106, UNCONNECTED107, UNCONNECTED108, UNCONNECTED109,
       UNCONNECTED110, UNCONNECTED111, UNCONNECTED112, UNCONNECTED113;
  wire UNCONNECTED114, UNCONNECTED115, UNCONNECTED116, UNCONNECTED117,
       UNCONNECTED118, UNCONNECTED119, UNCONNECTED120, UNCONNECTED121;
  wire UNCONNECTED122, UNCONNECTED123, UNCONNECTED124, UNCONNECTED125,
       UNCONNECTED126, UNCONNECTED127, UNCONNECTED128, UNCONNECTED129;
  wire UNCONNECTED130, UNCONNECTED131, UNCONNECTED132, UNCONNECTED133,
       UNCONNECTED134, UNCONNECTED135, UNCONNECTED136, UNCONNECTED137;
  wire UNCONNECTED138, UNCONNECTED139, control_clk_miso, n_75, n_116,
       n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_253, n_254, n_255, n_257, n_258, n_259;
  wire n_260, n_261, n_262, n_263, n_264, n_265, n_266, n_267;
  wire n_268, n_269, n_270, n_271, n_272, n_273, n_274, n_275;
  wire n_276, n_277, n_278, n_279, n_280, n_281, n_282, n_283;
  wire n_284, n_285, n_286, n_287, n_288, n_289, n_290, n_291;
  wire n_292, n_293, n_294, n_295, n_296, n_297, n_298, n_299;
  wire n_300, n_301, n_302, n_303, n_304, n_305, n_306, n_307;
  wire n_308, n_309, n_310, n_311, n_312, n_313, n_314, n_315;
  wire n_316, n_317, n_318, n_319, n_320, n_322, n_323, n_324;
  wire n_325, n_326, n_327, n_328, n_329, n_330, n_331, n_332;
  wire n_333, n_334, n_335, n_336, n_337, n_338, n_339, n_340;
  wire n_341, n_342, n_343, n_344, n_345, n_346, n_347, n_348;
  wire n_349, n_350, n_351, n_352, n_353, n_354, n_355, n_356;
  wire n_357, n_358, n_359, n_360, n_361, n_362, n_363, n_364;
  wire n_365, n_366, n_367, n_368, n_369, n_370, n_371, n_372;
  wire n_373, n_374, n_375, n_376, n_377, n_378, n_379, n_380;
  wire n_381, n_382, n_383, n_384, n_385, n_386, n_387, n_388;
  wire n_389, n_390, n_391, n_392, n_393, n_394, n_395, n_396;
  wire n_397, n_398, n_399, n_400, n_401, n_402, n_403, n_404;
  wire n_534, n_535, n_536, n_551, n_552, n_553, n_554, n_555;
  wire n_556, n_557, n_558, n_559, n_560, n_561, n_562, n_563;
  wire n_564, n_565, n_566, n_567, n_568, n_569, n_570, n_571;
  wire n_572, n_573, n_574, n_575, n_576, n_577, n_578, n_579;
  wire n_580, n_581, n_582, n_583, n_584, n_585, n_586, n_587;
  wire n_588, n_589, n_590, n_591, n_592, n_593, n_594, n_595;
  wire n_596, n_597, n_598, n_599, n_600, n_601, n_602, n_603;
  wire n_604, n_605, n_606, n_607, n_608, n_609, n_610, n_611;
  wire n_612, n_613, n_614, n_615, n_616, n_617, n_618, n_619;
  wire n_620, n_621, n_622, n_623, n_624, n_625, n_626, n_627;
  wire n_628, n_629, n_630, n_631, n_632, n_633, n_634, n_635;
  wire n_636, n_637, n_638, n_639, n_640, n_641, n_642, n_643;
  wire n_644, n_645, n_646, n_647, n_648, n_649, n_650, n_651;
  wire n_652, n_653, n_654, n_655, n_656, n_657, n_658, n_659;
  wire n_660, n_661, n_662, n_663, n_664, n_665, n_666, n_667;
  wire spi_clk, spi_cs;
  DFC3 \O2_data_reg[3] (.RN (n_reset), .C (spi_clk), .D (n_396), .Q
       (O2_data[3]), .QN (n_604));
  DFC3 \O2_data_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_402), .Q
       (O2_data[1]), .QN (UNCONNECTED));
  DFC3 \O2_data_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_401), .Q
       (O2_data[2]), .QN (UNCONNECTED0));
  DFC3 \O2_data_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_404), .Q
       (O2_data[0]), .QN (UNCONNECTED1));
  DFC3 \O2_data_reg[4] (.RN (n_reset), .C (spi_clk), .D (n_403), .Q
       (O2_data[4]), .QN (UNCONNECTED2));
  DFC3 \O2_data_reg[5] (.RN (n_reset), .C (spi_clk), .D (n_400), .Q
       (O2_data[5]), .QN (UNCONNECTED3));
  DFC3 \O2_data_reg[6] (.RN (n_reset), .C (spi_clk), .D (n_399), .Q
       (O2_data[6]), .QN (UNCONNECTED4));
  DFC3 \A_counter_reg[0] (.RN (n_reset), .C (m_clk), .D (n_394), .Q
       (A_counter[0]), .QN (n_658));
  NAND20 g3147(.A (n_389), .B (n_366), .Q (n_404));
  NAND20 g3148(.A (n_390), .B (n_365), .Q (n_403));
  NAND20 g3149(.A (n_387), .B (n_361), .Q (n_402));
  OAI210 g3150(.A (n_398), .B (n_395), .C (n_356), .Q (n_401));
  OAI210 g3151(.A (n_391), .B (n_397), .C (n_363), .Q (n_400));
  OAI210 g3152(.A (n_398), .B (n_397), .C (n_358), .Q (n_399));
  OAI220 g3153(.A (n_346), .B (n_604), .C (n_395), .D (n_345), .Q
       (n_396));
  DFC3 \O2_point_add_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_393),
       .Q (O2_point_add[2]), .QN (n_627));
  DFC3 \O2_point_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_392), .Q
       (O2_point[1]), .QN (UNCONNECTED5));
  OAI212 g3004(.A (A_counter[2]), .B (n_308), .C (n_350), .Q (n_394));
  DFC3 \O2_point_add_reg[1] (.RN (n_reset), .C (spi_clk), .D (n_357),
       .Q (O2_point_add[1]), .QN (UNCONNECTED6));
  DFC3 \O2_point_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_354), .Q
       (O2_point[0]), .QN (n_124));
  DFC3 O2_spi_mosi_out_reg(.RN (n_reset), .C (spi_clk), .D (n_352), .Q
       (spi_mosi_out), .QN (UNCONNECTED7));
  DFC3 \O1_r_pointer_reg[0] (.RN (n_reset), .C (m_clk), .D (n_367), .Q
       (O1_r_pointer[0]), .QN (UNCONNECTED8));
  DFC3 \O1_r_pointer_reg[3] (.RN (n_reset), .C (m_clk), .D (n_351), .Q
       (O1_r_pointer[3]), .QN (UNCONNECTED9));
  DFC3 \O1_r_pointer_reg[2] (.RN (n_reset), .C (m_clk), .D (n_377), .Q
       (O1_r_pointer[2]), .QN (UNCONNECTED10));
  DFC3 \O1_r_pointer_reg[1] (.RN (n_reset), .C (m_clk), .D (n_385), .Q
       (O1_r_pointer[1]), .QN (UNCONNECTED11));
  NAND30 g3163(.A (n_304), .B (n_336), .C (n_322), .Q (n_393));
  OAI210 g3170(.A (n_391), .B (n_353), .C (n_344), .Q (n_392));
  NAND20 g3279(.A (n_349), .B (n_388), .Q (n_390));
  NAND20 g3280(.A (n_386), .B (n_388), .Q (n_389));
  NAND20 g3281(.A (n_386), .B (n_300), .Q (n_387));
  DFC3 O1_r_empty_reg(.RN (n_reset), .C (m_clk), .D (n_342), .Q
       (O1_r_empty), .QN (UNCONNECTED12));
  NOR21 g3144(.A (n_320), .B (n_376), .Q (n_385));
  DFC3 \O2_point_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_339), .Q
       (O2_point[2]), .QN (n_329));
  DFE1 \O1_ex_mem_reg[11][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_375), .Q (UNCONNECTED13), .QN (n_607));
  DFE1 \O1_ex_mem_reg[4][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_384), .Q (UNCONNECTED14), .QN (n_563));
  DFE1 \O1_ex_mem_reg[4][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_384), .Q (UNCONNECTED15), .QN (n_605));
  DFE1 \O1_ex_mem_reg[4][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_384), .Q (UNCONNECTED16), .QN (n_554));
  DFE1 \O1_ex_mem_reg[4][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_384), .Q (UNCONNECTED17), .QN (n_565));
  DFE1 \O1_ex_mem_reg[4][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_384), .Q (UNCONNECTED18), .QN (n_612));
  DFE1 \O1_ex_mem_reg[4][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_384), .Q (UNCONNECTED19), .QN (n_608));
  DFE1 \O1_ex_mem_reg[4][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_384), .Q (UNCONNECTED20), .QN (n_606));
  DFE1 \O1_ex_mem_reg[10][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_378), .Q (UNCONNECTED21), .QN (n_600));
  DFE1 \O1_ex_mem_reg[5][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_383), .Q (UNCONNECTED22), .QN (n_564));
  DFE1 \O1_ex_mem_reg[5][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_383), .Q (UNCONNECTED23), .QN (n_633));
  DFE1 \O1_ex_mem_reg[5][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_383), .Q (UNCONNECTED24), .QN (n_611));
  DFE1 \O1_ex_mem_reg[7][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_382), .Q (UNCONNECTED25), .QN (n_622));
  DFE1 \O1_ex_mem_reg[5][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_383), .Q (UNCONNECTED26), .QN (n_567));
  DFE1 \O1_ex_mem_reg[5][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_383), .Q (UNCONNECTED27), .QN (n_610));
  DFE1 \O1_ex_mem_reg[5][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_383), .Q (UNCONNECTED28), .QN (n_562));
  DFE1 \O1_ex_mem_reg[7][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_382), .Q (UNCONNECTED29), .QN (n_649));
  DFE1 \O1_ex_mem_reg[5][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_383), .Q (UNCONNECTED30), .QN (n_624));
  DFE1 \O1_ex_mem_reg[6][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_381), .Q (UNCONNECTED31), .QN (n_561));
  DFE1 \O1_ex_mem_reg[6][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_381), .Q (UNCONNECTED32), .QN (n_571));
  DFE1 \O1_ex_mem_reg[6][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_381), .Q (UNCONNECTED33), .QN (n_570));
  DFE1 \O1_ex_mem_reg[6][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_381), .Q (UNCONNECTED34), .QN (n_632));
  DFE1 \O1_ex_mem_reg[6][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_381), .Q (UNCONNECTED35), .QN (n_596));
  DFE1 \O1_ex_mem_reg[6][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_381), .Q (UNCONNECTED36), .QN (n_590));
  DFE1 \O1_ex_mem_reg[6][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_381), .Q (UNCONNECTED37), .QN (n_599));
  DFE1 \O1_ex_mem_reg[12][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_380), .Q (UNCONNECTED38), .QN (n_628));
  DFE1 \O1_ex_mem_reg[12][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_380), .Q (UNCONNECTED39), .QN (n_595));
  DFE1 \O1_ex_mem_reg[12][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_380), .Q (UNCONNECTED40), .QN (n_557));
  DFE1 \O1_ex_mem_reg[12][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_380), .Q (UNCONNECTED41), .QN (n_574));
  DFE1 \O1_ex_mem_reg[12][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_380), .Q (UNCONNECTED42), .QN (n_580));
  DFE1 \O1_ex_mem_reg[12][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_380), .Q (UNCONNECTED43), .QN (n_581));
  DFE1 \O1_ex_mem_reg[12][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_380), .Q (UNCONNECTED44), .QN (n_556));
  DFE1 \O1_ex_mem_reg[0][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_379), .Q (UNCONNECTED45), .QN (n_582));
  DFE1 \O1_ex_mem_reg[0][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_379), .Q (UNCONNECTED46), .QN (n_559));
  DFE1 \O1_ex_mem_reg[0][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_379), .Q (UNCONNECTED47), .QN (n_639));
  DFE1 \O1_ex_mem_reg[0][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_379), .Q (UNCONNECTED48), .QN (n_603));
  DFE1 \O1_ex_mem_reg[0][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_379), .Q (UNCONNECTED49), .QN (n_558));
  DFE1 \O1_ex_mem_reg[0][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_379), .Q (UNCONNECTED50), .QN (n_575));
  DFE1 \O1_ex_mem_reg[0][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_379), .Q (UNCONNECTED51), .QN (n_635));
  DFE1 \O1_ex_mem_reg[7][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_382), .Q (UNCONNECTED52), .QN (n_568));
  DFE1 \O1_ex_mem_reg[7][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_382), .Q (UNCONNECTED53), .QN (n_592));
  DFE1 \O1_ex_mem_reg[7][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_382), .Q (UNCONNECTED54), .QN (n_614));
  DFE1 \O1_ex_mem_reg[7][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_382), .Q (UNCONNECTED55), .QN (n_560));
  DFE1 \O1_ex_mem_reg[7][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_382), .Q (UNCONNECTED56), .QN (n_621));
  DFE1 \O1_ex_mem_reg[10][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_378), .Q (UNCONNECTED57), .QN (n_655));
  DFE1 \O1_ex_mem_reg[10][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_378), .Q (UNCONNECTED58), .QN (n_602));
  NOR21 g3145(.A (n_325), .B (n_376), .Q (n_377));
  DFE1 \O1_ex_mem_reg[10][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_378), .Q (UNCONNECTED59), .QN (n_617));
  DFE1 \O1_ex_mem_reg[10][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_378), .Q (UNCONNECTED60), .QN (n_656));
  DFE1 \O1_ex_mem_reg[10][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_378), .Q (UNCONNECTED61), .QN (n_634));
  DFE1 \O1_ex_mem_reg[10][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_378), .Q (UNCONNECTED62), .QN (n_583));
  DFE1 \O1_ex_mem_reg[11][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_375), .Q (UNCONNECTED63), .QN (n_637));
  DFE1 \O1_ex_mem_reg[11][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_375), .Q (UNCONNECTED64), .QN (n_644));
  DFE1 \O1_ex_mem_reg[11][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_375), .Q (UNCONNECTED65), .QN (n_654));
  DFE1 \O1_ex_mem_reg[11][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_375), .Q (UNCONNECTED66), .QN (n_619));
  DFE1 \O1_ex_mem_reg[11][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_375), .Q (UNCONNECTED67), .QN (n_626));
  DFE1 \O1_ex_mem_reg[13][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_374), .Q (UNCONNECTED68), .QN (n_660));
  DFE1 \O1_ex_mem_reg[11][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_375), .Q (UNCONNECTED69), .QN (n_555));
  DFE1 \O1_ex_mem_reg[13][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_374), .Q (UNCONNECTED70), .QN (n_569));
  DFE1 \O1_ex_mem_reg[13][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_374), .Q (UNCONNECTED71), .QN (n_646));
  DFE1 \O1_ex_mem_reg[13][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_374), .Q (UNCONNECTED72), .QN (n_653));
  DFE1 \O1_ex_mem_reg[13][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_374), .Q (UNCONNECTED73), .QN (n_648));
  DFE1 \O1_ex_mem_reg[14][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_373), .Q (UNCONNECTED74), .QN (n_589));
  DFE1 \O1_ex_mem_reg[14][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_373), .Q (UNCONNECTED75), .QN (n_659));
  DFE1 \O1_ex_mem_reg[14][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_373), .Q (UNCONNECTED76), .QN (n_629));
  DFE1 \O1_ex_mem_reg[14][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_373), .Q (UNCONNECTED77), .QN (n_588));
  DFE1 \O1_ex_mem_reg[14][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_373), .Q (UNCONNECTED78), .QN (n_579));
  DFE1 \O1_ex_mem_reg[14][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_373), .Q (UNCONNECTED79), .QN (n_650));
  DFE1 \O1_ex_mem_reg[1][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_372), .Q (UNCONNECTED80), .QN (n_616));
  DFE1 \O1_ex_mem_reg[1][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_372), .Q (UNCONNECTED81), .QN (n_636));
  DFE1 \O1_ex_mem_reg[1][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_372), .Q (UNCONNECTED82), .QN (n_609));
  DFE1 \O1_ex_mem_reg[1][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_372), .Q (UNCONNECTED83), .QN (n_647));
  DFE1 \O1_ex_mem_reg[1][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_372), .Q (UNCONNECTED84), .QN (n_587));
  DFE1 \O1_ex_mem_reg[2][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_371), .Q (UNCONNECTED85), .QN (n_631));
  DFE1 \O1_ex_mem_reg[2][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_371), .Q (UNCONNECTED86), .QN (n_594));
  DFE1 \O1_ex_mem_reg[2][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_371), .Q (UNCONNECTED87), .QN (n_652));
  DFE1 \O1_ex_mem_reg[2][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_371), .Q (UNCONNECTED88), .QN (n_663));
  DFE1 \O1_ex_mem_reg[2][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_371), .Q (UNCONNECTED89), .QN (n_591));
  DFE1 \O1_ex_mem_reg[2][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_371), .Q (UNCONNECTED90), .QN (n_623));
  DFE1 \O1_ex_mem_reg[2][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_371), .Q (UNCONNECTED91), .QN (n_618));
  DFE1 \O1_ex_mem_reg[3][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_370), .Q (UNCONNECTED92), .QN (n_662));
  DFE1 \O1_ex_mem_reg[3][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_370), .Q (UNCONNECTED93), .QN (n_597));
  DFE1 \O1_ex_mem_reg[3][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_370), .Q (UNCONNECTED94), .QN (n_665));
  DFE1 \O1_ex_mem_reg[3][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_370), .Q (UNCONNECTED95), .QN (n_641));
  DFE1 \O1_ex_mem_reg[3][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_370), .Q (UNCONNECTED96), .QN (n_584));
  DFE1 \O1_ex_mem_reg[8][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_369), .Q (UNCONNECTED97), .QN (n_642));
  DFE1 \O1_ex_mem_reg[8][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_369), .Q (UNCONNECTED98), .QN (n_640));
  DFE1 \O1_ex_mem_reg[8][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_369), .Q (UNCONNECTED99), .QN (n_598));
  DFE1 \O1_ex_mem_reg[8][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_369), .Q (UNCONNECTED100), .QN (n_576));
  DFE1 \O1_ex_mem_reg[8][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_369), .Q (UNCONNECTED101), .QN (n_651));
  DFE1 \O1_ex_mem_reg[8][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_369), .Q (UNCONNECTED102), .QN (n_613));
  DFE1 \O1_ex_mem_reg[9][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_368), .Q (UNCONNECTED103), .QN (n_630));
  DFE1 \O1_ex_mem_reg[9][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_368), .Q (UNCONNECTED104), .QN (n_578));
  DFE1 \O1_ex_mem_reg[9][3] (.C (control_clk_miso), .D
       (spi_miso_out[3]), .E (n_368), .Q (UNCONNECTED105), .QN (n_585));
  DFE1 \O1_ex_mem_reg[9][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_368), .Q (UNCONNECTED106), .QN (n_586));
  DFE1 \O1_ex_mem_reg[9][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_368), .Q (UNCONNECTED107), .QN (n_572));
  NOR21 g3146(.A (n_319), .B (n_376), .Q (n_367));
  DFE1 \O1_ex_mem_reg[8][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_369), .Q (UNCONNECTED108), .QN (n_643));
  DFE1 \O1_ex_mem_reg[9][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_368), .Q (UNCONNECTED109), .QN (n_625));
  DFE1 \O1_ex_mem_reg[9][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_368), .Q (UNCONNECTED110), .QN (n_601));
  DFE1 \O1_ex_mem_reg[3][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_370), .Q (UNCONNECTED111), .QN (n_573));
  DFE1 \O1_ex_mem_reg[3][0] (.C (control_clk_miso), .D
       (spi_miso_out[0]), .E (n_370), .Q (UNCONNECTED112), .QN (n_657));
  DFE1 \O1_ex_mem_reg[1][6] (.C (control_clk_miso), .D
       (spi_miso_out[6]), .E (n_372), .Q (UNCONNECTED113), .QN (n_645));
  OAI210 g3164(.A (n_364), .B (n_359), .C (O2_data[0]), .Q (n_366));
  DFE1 \O1_ex_mem_reg[1][2] (.C (control_clk_miso), .D
       (spi_miso_out[2]), .E (n_372), .Q (UNCONNECTED114), .QN (n_664));
  OAI210 g3165(.A (n_364), .B (n_362), .C (O2_data[4]), .Q (n_365));
  OAI210 g3166(.A (n_360), .B (n_362), .C (O2_data[5]), .Q (n_363));
  DFE1 \O1_ex_mem_reg[14][5] (.C (control_clk_miso), .D
       (spi_miso_out[5]), .E (n_373), .Q (UNCONNECTED115), .QN (n_638));
  OAI210 g3168(.A (n_360), .B (n_359), .C (O2_data[1]), .Q (n_361));
  OAI210 g3167(.A (n_355), .B (n_362), .C (O2_data[6]), .Q (n_358));
  INV0 g3283(.A (n_347), .Q (n_357));
  OAI210 g3169(.A (n_355), .B (n_359), .C (O2_data[2]), .Q (n_356));
  OAI2110 g3286(.A (O2_point[0]), .B (n_353), .C (n_338), .D (n_290),
       .Q (n_354));
  OAI2110 g3287(.A (n_326), .B (n_240), .C (n_299), .D (n_323), .Q
       (n_352));
  NOR21 g3017(.A (n_340), .B (n_376), .Q (n_351));
  AOI221 g3018(.A (n_334), .B (A_counter[1]), .C (A_counter[0]), .D
       (n_307), .Q (n_350));
  INV0 g3307(.A (n_386), .Q (n_395));
  INV0 g3311(.A (n_349), .Q (n_397));
  DFE1 \O1_ex_mem_reg[13][1] (.C (control_clk_miso), .D
       (spi_miso_out[1]), .E (n_374), .Q (UNCONNECTED116), .QN (n_566));
  DFE1 \O1_ex_mem_reg[13][4] (.C (control_clk_miso), .D
       (spi_miso_out[4]), .E (n_374), .Q (UNCONNECTED117), .QN (n_620));
  TFEC3 A_spi_clk_reg(.RN (n_reset), .C (m_clk), .T (n_309), .Q
       (spi_clk), .QN (UNCONNECTED118));
  DLQ3 \O1_data_out_reg[65] (.GN (n_348), .D (n_211), .Q
       (data_out[65]));
  DLQ3 \O1_data_out_reg[90] (.GN (n_348), .D (n_193), .Q
       (data_out[90]));
  DLQ3 \O1_data_out_reg[71] (.GN (n_348), .D (1'b0), .Q (data_out[71]));
  DLQ3 \O1_data_out_reg[111] (.GN (n_348), .D (1'b0), .Q
       (data_out[111]));
  DLQ3 \O1_data_out_reg[79] (.GN (n_348), .D (1'b0), .Q (data_out[79]));
  DLQ3 \O1_data_out_reg[7] (.GN (n_348), .D (1'b0), .Q (data_out[7]));
  DLQ3 \O1_data_out_reg[119] (.GN (n_348), .D (1'b0), .Q
       (data_out[119]));
  DLQ3 \O1_data_out_reg[55] (.GN (n_348), .D (1'b0), .Q (data_out[55]));
  DLQ3 \O1_data_out_reg[5] (.GN (n_348), .D (n_137), .Q (data_out[5]));
  DLQ3 \O1_data_out_reg[87] (.GN (n_348), .D (1'b0), .Q (data_out[87]));
  DLQ3 \O1_data_out_reg[95] (.GN (n_348), .D (1'b0), .Q (data_out[95]));
  DLQ3 \O1_data_out_reg[103] (.GN (n_348), .D (1'b0), .Q
       (data_out[103]));
  DLQ3 \O1_data_out_reg[104] (.GN (n_348), .D (n_139), .Q
       (data_out[104]));
  DLQ3 \O1_data_out_reg[63] (.GN (n_348), .D (1'b0), .Q (data_out[63]));
  DFC3 \O2_point_add_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_331),
       .Q (O2_point_add[0]), .QN (n_291));
  DLQ3 \O1_data_out_reg[15] (.GN (n_348), .D (1'b0), .Q (data_out[15]));
  DLQ3 \O1_data_out_reg[102] (.GN (n_348), .D (n_165), .Q
       (data_out[102]));
  DLQ3 \O1_data_out_reg[47] (.GN (n_348), .D (1'b0), .Q (data_out[47]));
  DLQ3 \O1_data_out_reg[19] (.GN (n_348), .D (n_202), .Q
       (data_out[19]));
  DLQ3 \O1_data_out_reg[17] (.GN (n_348), .D (n_172), .Q
       (data_out[17]));
  DLQ3 \O1_data_out_reg[0] (.GN (n_348), .D (n_123), .Q (data_out[0]));
  DLQ3 \O1_data_out_reg[11] (.GN (n_348), .D (n_209), .Q
       (data_out[11]));
  DLQ3 \O1_data_out_reg[49] (.GN (n_348), .D (n_159), .Q
       (data_out[49]));
  DLQ3 \O1_data_out_reg[44] (.GN (n_348), .D (n_190), .Q
       (data_out[44]));
  DLQ3 \O1_data_out_reg[82] (.GN (n_348), .D (n_142), .Q
       (data_out[82]));
  DLQ3 \O1_data_out_reg[40] (.GN (n_348), .D (n_171), .Q
       (data_out[40]));
  DLQ3 \O1_data_out_reg[115] (.GN (n_348), .D (n_184), .Q
       (data_out[115]));
  AOI210 g3284(.A (n_289), .B (O2_point_add[1]), .C (n_327), .Q
       (n_347));
  DLQ3 \O1_data_out_reg[76] (.GN (n_348), .D (n_133), .Q
       (data_out[76]));
  DLQ3 \O1_data_out_reg[32] (.GN (n_348), .D (n_153), .Q
       (data_out[32]));
  AOI210 g3288(.A (n_345), .B (n_297), .C (n_359), .Q (n_346));
  DLQ3 \O1_data_out_reg[28] (.GN (n_348), .D (n_157), .Q
       (data_out[28]));
  AOI210 g3290(.A (n_337), .B (O2_point[1]), .C (n_260), .Q (n_344));
  DLQ3 \O1_data_out_reg[110] (.GN (n_348), .D (n_186), .Q
       (data_out[110]));
  NOR20 g3308(.A (O2_point[2]), .B (n_343), .Q (n_386));
  NOR20 g3312(.A (n_329), .B (n_343), .Q (n_349));
  DLQ3 \O1_data_out_reg[68] (.GN (n_348), .D (n_220), .Q
       (data_out[68]));
  NAND22 g3143(.A (n_341), .B (n_534), .Q (n_342));
  JKC3 \A_counter_reg[2] (.RN (n_reset), .C (m_clk), .J (n_296), .K
       (n_284), .Q (n_306), .QN (A_counter[2]));
  DLQ3 \O1_data_out_reg[1] (.GN (n_348), .D (n_121), .Q (data_out[1]));
  DLQ3 \O1_data_out_reg[20] (.GN (n_348), .D (n_188), .Q
       (data_out[20]));
  DLQ3 \O1_data_out_reg[21] (.GN (n_348), .D (n_219), .Q
       (data_out[21]));
  DLQ3 \O1_data_out_reg[22] (.GN (n_348), .D (n_147), .Q
       (data_out[22]));
  DLQ3 \O1_data_out_reg[24] (.GN (n_348), .D (n_222), .Q
       (data_out[24]));
  DLQ3 \O1_data_out_reg[25] (.GN (n_348), .D (n_131), .Q
       (data_out[25]));
  DLQ3 \O1_data_out_reg[26] (.GN (n_348), .D (n_181), .Q
       (data_out[26]));
  DLQ3 \O1_data_out_reg[27] (.GN (n_348), .D (n_178), .Q
       (data_out[27]));
  DLQ3 \O1_data_out_reg[29] (.GN (n_348), .D (n_213), .Q
       (data_out[29]));
  DLQ3 \O1_data_out_reg[2] (.GN (n_348), .D (n_195), .Q (data_out[2]));
  DLQ3 \O1_data_out_reg[30] (.GN (n_348), .D (n_218), .Q
       (data_out[30]));
  DLQ3 \O1_data_out_reg[33] (.GN (n_348), .D (n_141), .Q
       (data_out[33]));
  DLQ3 \O1_data_out_reg[34] (.GN (n_348), .D (n_170), .Q
       (data_out[34]));
  DLQ3 \O1_data_out_reg[35] (.GN (n_348), .D (n_183), .Q
       (data_out[35]));
  DLQ3 \O1_data_out_reg[36] (.GN (n_348), .D (n_217), .Q
       (data_out[36]));
  DLQ3 \O1_data_out_reg[37] (.GN (n_348), .D (n_212), .Q
       (data_out[37]));
  DLQ3 \O1_data_out_reg[38] (.GN (n_348), .D (n_223), .Q
       (data_out[38]));
  DLQ3 \O1_data_out_reg[3] (.GN (n_348), .D (n_227), .Q (data_out[3]));
  DLQ3 \O1_data_out_reg[41] (.GN (n_348), .D (n_168), .Q
       (data_out[41]));
  DLQ3 \O1_data_out_reg[42] (.GN (n_348), .D (n_150), .Q
       (data_out[42]));
  DLQ3 \O1_data_out_reg[43] (.GN (n_348), .D (n_167), .Q
       (data_out[43]));
  DLQ3 \O1_data_out_reg[45] (.GN (n_348), .D (n_200), .Q
       (data_out[45]));
  DLQ3 \O1_data_out_reg[46] (.GN (n_348), .D (n_163), .Q
       (data_out[46]));
  DLQ3 \O1_data_out_reg[48] (.GN (n_348), .D (n_155), .Q
       (data_out[48]));
  DLQ3 \O1_data_out_reg[4] (.GN (n_348), .D (n_180), .Q (data_out[4]));
  DLQ3 \O1_data_out_reg[100] (.GN (n_348), .D (n_208), .Q
       (data_out[100]));
  DLQ3 \O1_data_out_reg[50] (.GN (n_348), .D (n_156), .Q
       (data_out[50]));
  DLQ3 \O1_data_out_reg[51] (.GN (n_348), .D (n_149), .Q
       (data_out[51]));
  DLQ3 \O1_data_out_reg[101] (.GN (n_348), .D (n_154), .Q
       (data_out[101]));
  DLQ3 \O1_data_out_reg[52] (.GN (n_348), .D (n_151), .Q
       (data_out[52]));
  DLQ3 \O1_data_out_reg[53] (.GN (n_348), .D (n_221), .Q
       (data_out[53]));
  DLQ3 \O1_data_out_reg[54] (.GN (n_348), .D (n_224), .Q
       (data_out[54]));
  DLQ3 \O1_data_out_reg[56] (.GN (n_348), .D (n_162), .Q
       (data_out[56]));
  DLQ3 \O1_data_out_reg[57] (.GN (n_348), .D (n_120), .Q
       (data_out[57]));
  DLQ3 \O1_data_out_reg[58] (.GN (n_348), .D (n_143), .Q
       (data_out[58]));
  DLQ3 \O1_data_out_reg[59] (.GN (n_348), .D (n_118), .Q
       (data_out[59]));
  DLQ3 \O1_data_out_reg[105] (.GN (n_348), .D (n_117), .Q
       (data_out[105]));
  DLQ3 \O1_data_out_reg[60] (.GN (n_348), .D (n_201), .Q
       (data_out[60]));
  DLQ3 \O1_data_out_reg[106] (.GN (n_348), .D (n_173), .Q
       (data_out[106]));
  DLQ3 \O1_data_out_reg[61] (.GN (n_348), .D (n_225), .Q
       (data_out[61]));
  DLQ3 \O1_data_out_reg[62] (.GN (n_348), .D (n_140), .Q
       (data_out[62]));
  DLQ3 \O1_data_out_reg[107] (.GN (n_348), .D (n_196), .Q
       (data_out[107]));
  DLQ3 \O1_data_out_reg[64] (.GN (n_348), .D (n_216), .Q
       (data_out[64]));
  DLQ3 \O1_data_out_reg[108] (.GN (n_348), .D (n_203), .Q
       (data_out[108]));
  DLQ3 \O1_data_out_reg[66] (.GN (n_348), .D (n_126), .Q
       (data_out[66]));
  DLQ3 \O1_data_out_reg[109] (.GN (n_348), .D (n_187), .Q
       (data_out[109]));
  DLQ3 \O1_data_out_reg[67] (.GN (n_348), .D (n_138), .Q
       (data_out[67]));
  DLQ3 \O1_data_out_reg[10] (.GN (n_348), .D (n_164), .Q
       (data_out[10]));
  DLQ3 \O1_data_out_reg[69] (.GN (n_348), .D (n_214), .Q
       (data_out[69]));
  DLQ3 \O1_data_out_reg[6] (.GN (n_348), .D (n_191), .Q (data_out[6]));
  DLQ3 \O1_data_out_reg[70] (.GN (n_348), .D (n_194), .Q
       (data_out[70]));
  DLQ3 \O1_data_out_reg[72] (.GN (n_348), .D (n_119), .Q
       (data_out[72]));
  DLQ3 \O1_data_out_reg[73] (.GN (n_348), .D (n_199), .Q
       (data_out[73]));
  DLQ3 \O1_data_out_reg[112] (.GN (n_348), .D (n_144), .Q
       (data_out[112]));
  DLQ3 \O1_data_out_reg[74] (.GN (n_348), .D (n_116), .Q
       (data_out[74]));
  DLQ3 \O1_data_out_reg[75] (.GN (n_348), .D (n_189), .Q
       (data_out[75]));
  DLQ3 \O1_data_out_reg[113] (.GN (n_348), .D (n_148), .Q
       (data_out[113]));
  DLQ3 \O1_data_out_reg[77] (.GN (n_348), .D (n_146), .Q
       (data_out[77]));
  DLQ3 \O1_data_out_reg[114] (.GN (n_348), .D (n_197), .Q
       (data_out[114]));
  DLQ3 \O1_data_out_reg[78] (.GN (n_348), .D (n_158), .Q
       (data_out[78]));
  DLQ3 \O1_data_out_reg[80] (.GN (n_348), .D (n_166), .Q
       (data_out[80]));
  DLQ3 \O1_data_out_reg[81] (.GN (n_348), .D (n_182), .Q
       (data_out[81]));
  DLQ3 \O1_data_out_reg[116] (.GN (n_348), .D (n_177), .Q
       (data_out[116]));
  DLQ3 \O1_data_out_reg[83] (.GN (n_348), .D (n_134), .Q
       (data_out[83]));
  DLQ3 \O1_data_out_reg[117] (.GN (n_348), .D (n_169), .Q
       (data_out[117]));
  DLQ3 \O1_data_out_reg[84] (.GN (n_348), .D (n_145), .Q
       (data_out[84]));
  DLQ3 \O1_data_out_reg[85] (.GN (n_348), .D (n_176), .Q
       (data_out[85]));
  DLQ3 \O1_data_out_reg[118] (.GN (n_348), .D (n_210), .Q
       (data_out[118]));
  DLQ3 \O1_data_out_reg[86] (.GN (n_348), .D (n_135), .Q
       (data_out[86]));
  DLQ3 \O1_data_out_reg[88] (.GN (n_348), .D (n_136), .Q
       (data_out[88]));
  DLQ3 \O1_data_out_reg[89] (.GN (n_348), .D (n_185), .Q
       (data_out[89]));
  DLQ3 \O1_data_out_reg[8] (.GN (n_348), .D (n_160), .Q (data_out[8]));
  DLQ3 \O1_data_out_reg[12] (.GN (n_348), .D (n_122), .Q
       (data_out[12]));
  DLQ3 \O1_data_out_reg[91] (.GN (n_348), .D (n_132), .Q
       (data_out[91]));
  DLQ3 \O1_data_out_reg[13] (.GN (n_348), .D (n_179), .Q
       (data_out[13]));
  DLQ3 \O1_data_out_reg[92] (.GN (n_348), .D (n_161), .Q
       (data_out[92]));
  DLQ3 \O1_data_out_reg[93] (.GN (n_348), .D (n_207), .Q
       (data_out[93]));
  DLQ3 \O1_data_out_reg[14] (.GN (n_348), .D (n_205), .Q
       (data_out[14]));
  DLQ3 \O1_data_out_reg[94] (.GN (n_348), .D (n_192), .Q
       (data_out[94]));
  DLQ3 \O1_data_out_reg[96] (.GN (n_348), .D (n_206), .Q
       (data_out[96]));
  DLQ3 \O1_data_out_reg[97] (.GN (n_348), .D (n_174), .Q
       (data_out[97]));
  DLQ3 \O1_data_out_reg[16] (.GN (n_348), .D (n_204), .Q
       (data_out[16]));
  DLQ3 \O1_data_out_reg[98] (.GN (n_348), .D (n_130), .Q
       (data_out[98]));
  DLQ3 \O1_data_out_reg[99] (.GN (n_348), .D (n_215), .Q
       (data_out[99]));
  DLQ3 \O1_data_out_reg[9] (.GN (n_348), .D (n_175), .Q (data_out[9]));
  DLQ3 \O1_data_out_reg[18] (.GN (n_348), .D (n_152), .Q
       (data_out[18]));
  DLQ3 \O1_data_out_reg[23] (.GN (n_348), .D (1'b0), .Q (data_out[23]));
  DLQ3 \O1_data_out_reg[31] (.GN (n_348), .D (1'b0), .Q (data_out[31]));
  DLQ3 \O1_data_out_reg[39] (.GN (n_348), .D (1'b0), .Q (data_out[39]));
  DFC3 \O1_w_pointer_reg[3] (.RN (n_reset), .C (control_clk_miso), .D
       (n_310), .Q (O1_w_pointer[3]), .QN (n_287));
  INV3 g3161(.A (n_341), .Q (n_376));
  IMUX20 g3154(.A (O1_r_pointer[3]), .B (n_293), .S (n_324), .Q
       (n_340));
  OAI310 g3285(.A (O2_point[2]), .B (n_345), .C (n_353), .D (n_285), .Q
       (n_339));
  NAND20 g3309(.A (n_337), .B (O2_point[0]), .Q (n_338));
  NAND20 g3314(.A (n_305), .B (O2_point_add[1]), .Q (n_336));
  TFSC1 \A_counter_reg[1] (.RN (n_reset), .C (m_clk), .SD
       (A_counter[1]), .SE (n_333), .Q (A_counter[1]), .QN
       (UNCONNECTED119));
  DFC3 O1_w_full_reg(.RN (n_reset), .C (control_clk_miso), .D (n_295),
       .Q (O1_w_full), .QN (n_198));
  DFEC1 \O2_final_data_reg[0] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[0]), .E (n_335), .Q (UNCONNECTED120), .QN (n_615));
  DFEC1 \O2_final_data_reg[2] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[2]), .E (n_335), .Q (UNCONNECTED121), .QN (n_661));
  DFEC1 \O2_final_data_reg[4] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[4]), .E (n_335), .Q (UNCONNECTED122), .QN (n_666));
  DFEC1 \O2_final_data_reg[5] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[5]), .E (n_335), .Q (UNCONNECTED123), .QN (n_553));
  DFEC1 \O2_final_data_reg[6] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[6]), .E (n_335), .Q (UNCONNECTED124), .QN (n_667));
  DFEC1 \O2_final_data_reg[1] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[1]), .E (n_335), .Q (UNCONNECTED125), .QN (n_577));
  DFEC1 \O2_final_data_reg[3] (.RN (n_reset), .C (spi_clk), .D
       (O2_data[3]), .E (n_335), .Q (UNCONNECTED126), .QN (n_593));
  NAND22 g3162(.A (n_332), .B (O1_rinc), .Q (n_341));
  IMUX21 g3171(.A (n_333), .B (n_306), .S (A_counter[0]), .Q (n_334));
  NOR21 g3160(.A (n_226), .B (n_332), .Q (n_348));
  OAI2110 g3315(.A (n_291), .B (n_258), .C (n_298), .D (n_302), .Q
       (n_331));
  OAI210 g3316(.A (n_330), .B (O2_point[2]), .C (n_328), .Q (n_362));
  OAI210 g3317(.A (n_330), .B (n_329), .C (n_328), .Q (n_359));
  OAI220 g3318(.A (n_236), .B (n_257), .C (n_326), .D
       (O2_point_add[1]), .Q (n_327));
  IMUX20 g3319(.A (O1_r_pointer[2]), .B (n_246), .S (n_324), .Q
       (n_325));
  NAND20 g3325(.A (n_301), .B (spi_miso_in), .Q (n_343));
  NAND20 g3330(.A (n_322), .B (n_303), .Q (n_323));
  IMUX20 g3337(.A (O1_r_pointer[1]), .B (n_229), .S (n_324), .Q
       (n_320));
  XNR21 g3338(.A (O1_r_pointer[0]), .B (n_324), .Q (n_319));
  NOR20 g3357(.A (n_317), .B (n_318), .Q (n_382));
  NOR20 g3347(.A (n_315), .B (n_318), .Q (n_384));
  NOR20 g3346(.A (n_317), .B (n_316), .Q (n_375));
  DFC3 \O2_control_reg[2] (.RN (n_reset), .C (spi_clk), .D (n_282), .Q
       (O2_control[2]), .QN (UNCONNECTED127));
  NOR20 g3356(.A (n_314), .B (n_318), .Q (n_381));
  NOR20 g3352(.A (n_312), .B (n_316), .Q (n_368));
  NOR20 g3354(.A (n_315), .B (n_316), .Q (n_369));
  NOR20 g3353(.A (n_315), .B (n_311), .Q (n_380));
  NOR20 g3350(.A (n_314), .B (n_316), .Q (n_378));
  NOR20 g3358(.A (n_315), .B (n_313), .Q (n_379));
  NOR20 g3361(.A (n_314), .B (n_313), .Q (n_371));
  NOR20 g3349(.A (n_312), .B (n_318), .Q (n_383));
  NOR20 g3362(.A (n_312), .B (n_313), .Q (n_372));
  NOR20 g3365(.A (n_314), .B (n_311), .Q (n_373));
  NOR20 g3368(.A (n_312), .B (n_311), .Q (n_374));
  NOR20 g3282(.A (n_279), .B (n_283), .Q (n_310));
  NOR20 g3348(.A (n_317), .B (n_313), .Q (n_370));
  NOR31 g3289(.A (n_308), .B (n_307), .C (n_306), .Q (n_309));
  NOR20 g3322(.A (O2_point_add[2]), .B (n_326), .Q (n_305));
  OAI210 g3333(.A (n_278), .B (n_274), .C (O2_point_add[2]), .Q
       (n_304));
  OAI220 g3334(.A (n_294), .B (spi_cs), .C (O2_point[2]), .D (n_276),
       .Q (n_337));
  TFEC3 O2_control_clk_miso_reg(.RN (n_reset), .C (spi_clk), .T
       (n_281), .Q (control_clk_miso), .QN (n_259));
  DFC3 \O1_w_pointer_reg[2] (.RN (n_reset), .C (control_clk_miso), .D
       (n_270), .Q (O1_w_pointer[2]), .QN (n_237));
  DFC3 \O2_control_reg[0] (.RN (n_reset), .C (spi_clk), .D (n_273), .Q
       (O2_control[0]), .QN (UNCONNECTED128));
  DFC3 \O1_w_pointer_reg[1] (.RN (n_reset), .C (control_clk_miso), .D
       (n_271), .Q (O1_w_pointer[1]), .QN (n_125));
  NOR20 g3355(.A (n_330), .B (n_388), .Q (n_364));
  DFC3 \O1_w_pointer_reg[0] (.RN (n_reset), .C (control_clk_miso), .D
       (n_269), .Q (O1_w_pointer[0]), .QN (n_127));
  DFP3 \O2_control_reg[1] (.SN (n_reset), .C (spi_clk), .D (n_272), .Q
       (O2_control[1]), .QN (UNCONNECTED129));
  INV0 g3359(.A (n_302), .Q (n_303));
  NOR20 g3364(.A (n_330), .B (n_234), .Q (n_355));
  INV0 g3366(.A (n_353), .Q (n_301));
  NOR20 g3369(.A (n_330), .B (n_300), .Q (n_360));
  NAND30 g3370(.A (n_298), .B (n_297), .C (spi_mosi_out), .Q (n_299));
  NOR21 g3313(.A (n_307), .B (n_233), .Q (n_296));
  INV0 g3326(.A (n_280), .Q (n_295));
  IMUX20 g3336(.A (n_297), .B (n_292), .S (n_294), .Q (n_328));
  ADD22 g3291(.A (n_245), .B (O1_r_pointer[3]), .CO (n_332), .S
       (n_293));
  DFC3 \O2_spi_miso_out_reg[0] (.RN (n_reset), .C (control_clk_miso),
       .D (n_266), .Q (spi_miso_out[0]), .QN (UNCONNECTED130));
  DFC3 \O2_spi_miso_out_reg[2] (.RN (n_reset), .C (control_clk_miso),
       .D (n_265), .Q (spi_miso_out[2]), .QN (UNCONNECTED131));
  NAND20 g3351(.A (O2_point_add[0]), .B (n_292), .Q (n_326));
  TFSC1 \A_counter_reg[3] (.RN (n_reset), .C (m_clk), .SD
       (A_counter[3]), .SE (spi_cs), .Q (A_counter[3]), .QN
       (UNCONNECTED132));
  NAND20 g3360(.A (n_291), .B (n_292), .Q (n_302));
  NAND20 g3363(.A (n_300), .B (n_292), .Q (n_290));
  NAND20 g3367(.A (n_294), .B (n_297), .Q (n_353));
  OAI210 g3372(.A (n_259), .B (O2_point_add[2]), .C (n_277), .Q
       (n_289));
  NOR21 g3378(.A (n_551), .B (O1_r_empty), .Q (n_324));
  NAND20 g3386(.A (n_288), .B (O1_w_pointer[3]), .Q (n_316));
  NAND20 g3387(.A (n_286), .B (n_287), .Q (n_318));
  NAND20 g3388(.A (n_288), .B (n_287), .Q (n_313));
  NAND20 g3391(.A (n_286), .B (O1_w_pointer[3]), .Q (n_311));
  OAI2110 g3399(.A (n_345), .B (n_275), .C (O2_point[2]), .D (n_248),
       .Q (n_285));
  DFC3 \O2_spi_miso_out_reg[5] (.RN (n_reset), .C (control_clk_miso),
       .D (n_263), .Q (spi_miso_out[5]), .QN (UNCONNECTED133));
  DFC3 \O2_spi_miso_out_reg[3] (.RN (n_reset), .C (control_clk_miso),
       .D (n_264), .Q (spi_miso_out[3]), .QN (UNCONNECTED134));
  NAND22 g3310(.A (n_284), .B (n_306), .Q (n_333));
  IMUX20 g3320(.A (O1_w_pointer[3]), .B (n_535), .S (n_253), .Q
       (n_283));
  NOR20 g3324(.A (n_281), .B (n_268), .Q (n_282));
  AOI210 g3327(.A (n_249), .B (O1_w_full), .C (n_279), .Q (n_280));
  DFC3 \O2_spi_miso_out_reg[1] (.RN (n_reset), .C (control_clk_miso),
       .D (n_262), .Q (spi_miso_out[1]), .QN (UNCONNECTED135));
  DFC3 \O2_spi_miso_out_reg[4] (.RN (n_reset), .C (control_clk_miso),
       .D (n_267), .Q (spi_miso_out[4]), .QN (UNCONNECTED136));
  DFC3 \O2_spi_miso_out_reg[6] (.RN (n_reset), .C (control_clk_miso),
       .D (n_261), .Q (spi_miso_out[6]), .QN (UNCONNECTED137));
  INV0 g3389(.A (n_277), .Q (n_278));
  INV0 g3393(.A (n_292), .Q (n_276));
  INV0 g3396(.A (n_297), .Q (n_330));
  NOR30 g3400(.A (n_275), .B (n_274), .C (spi_cs), .Q (n_335));
  NOR20 g3321(.A (O2_control[0]), .B (n_281), .Q (n_273));
  NOR20 g3323(.A (n_239), .B (n_281), .Q (n_272));
  NOR20 g3328(.A (n_251), .B (n_279), .Q (n_271));
  NOR20 g3329(.A (n_254), .B (n_279), .Q (n_270));
  NOR20 g3331(.A (n_250), .B (n_279), .Q (n_269));
  CLKIN2 g3335(.A (n_284), .Q (n_307));
  INV0 g3373(.A (n_247), .Q (n_268));
  NOR20 g3379(.A (spi_cs), .B (n_666), .Q (n_267));
  NOR20 g3380(.A (spi_cs), .B (n_615), .Q (n_266));
  NOR20 g3381(.A (spi_cs), .B (n_661), .Q (n_265));
  NOR20 g3382(.A (spi_cs), .B (n_593), .Q (n_264));
  NOR20 g3383(.A (spi_cs), .B (n_553), .Q (n_263));
  NOR20 g3384(.A (spi_cs), .B (n_577), .Q (n_262));
  NOR20 g3385(.A (spi_cs), .B (n_667), .Q (n_261));
  NOR20 g3390(.A (spi_cs), .B (n_291), .Q (n_277));
  NOR20 g3392(.A (spi_cs), .B (n_398), .Q (n_260));
  NOR20 g3394(.A (control_clk_miso), .B (spi_cs), .Q (n_292));
  NOR21 g3395(.A (spi_cs), .B (n_75), .Q (n_284));
  NOR20 g3397(.A (spi_cs), .B (n_259), .Q (n_297));
  AOI210 g3398(.A (n_257), .B (control_clk_miso), .C (spi_cs), .Q
       (n_258));
  NOR20 g3403(.A (O1_w_pointer[2]), .B (n_255), .Q (n_288));
  NOR20 g3404(.A (n_237), .B (n_255), .Q (n_286));
  IMUX20 g3376(.A (O1_w_pointer[2]), .B (n_238), .S (n_253), .Q
       (n_254));
  DFC3 O1_rinc_reg(.RN (n_reset), .C (m_clk), .D (n_536), .Q (O1_rinc),
       .QN (n_551));
  IMUX20 g3406(.A (O1_w_pointer[1]), .B (n_235), .S (n_253), .Q
       (n_251));
  XNR20 g3408(.A (n_253), .B (O1_w_pointer[0]), .Q (n_250));
  NAND20 g3409(.A (O1_r_empty), .B (n_241), .Q (n_249));
  INV0 g3407(.A (spi_cs), .Q (n_248));
  ADD21 g3374(.A (n_230), .B (O2_control[2]), .CO (n_281), .S (n_247));
  ADD22 g3375(.A (n_228), .B (O1_r_pointer[2]), .CO (n_245), .S
       (n_246));
  NOR30 g3371(.A (n_244), .B (n_287), .C (O1_winc), .Q (n_279));
  NAND20 g3410(.A (n_253), .B (n_reset), .Q (n_255));
  NAND20 g3411(.A (n_294), .B (n_274), .Q (n_298));
  INV0 g3423(.A (n_253), .Q (n_241));
  DFC3 O1_spi_cs_reg(.RN (n_reset), .C (m_clk), .D (n_129), .Q
       (spi_cs), .QN (UNCONNECTED138));
  AOI210 g3405(.A (O2_point_add[2]), .B (spi_mosi_out), .C (n_232), .Q
       (n_240));
  INV0 g3413(.A (n_231), .Q (n_239));
  IMUX20 g3416(.A (O1_w_pointer[2]), .B (n_237), .S (n_317), .Q
       (n_238));
  INV0 g3418(.A (n_294), .Q (n_275));
  INV0 g3420(.A (n_236), .Q (n_274));
  NAND20 g3422(.A (n_128), .B (O1_w_pointer[2]), .Q (n_244));
  NOR21 g3424(.A (O1_winc), .B (O1_w_full), .Q (n_253));
  NAND20 g3425(.A (n_312), .B (n_314), .Q (n_235));
  INV0 g3549(.A (n_398), .Q (n_234));
  INV0 g3544(.A (n_300), .Q (n_391));
  INV3 g3534(.A (n_233), .Q (n_308));
  NOR20 g3419(.A (n_291), .B (n_257), .Q (n_294));
  NOR20 g3421(.A (n_329), .B (n_345), .Q (n_236));
  INV0 g3546(.A (n_232), .Q (n_322));
  ADD21 g3414(.A (O2_control[0]), .B (O2_control[1]), .CO (n_230), .S
       (n_231));
  ADD22 g3415(.A (O1_r_pointer[1]), .B (O1_r_pointer[0]), .CO (n_228),
       .S (n_229));
  NOR20 g3460(.A (n_226), .B (n_603), .Q (n_227));
  NOR20 g3458(.A (n_226), .B (n_622), .Q (n_225));
  NOR20 g3527(.A (n_226), .B (n_599), .Q (n_224));
  NOR20 g3457(.A (n_226), .B (n_606), .Q (n_223));
  NOR20 g3453(.A (n_226), .B (n_657), .Q (n_222));
  NOR20 g3450(.A (n_226), .B (n_590), .Q (n_221));
  NOR20 g3506(.A (n_226), .B (n_576), .Q (n_220));
  NOR20 g3505(.A (n_226), .B (n_623), .Q (n_219));
  NOR20 g3504(.A (n_226), .B (n_584), .Q (n_218));
  NOR20 g3502(.A (n_226), .B (n_612), .Q (n_217));
  NOR20 g3449(.A (n_226), .B (n_642), .Q (n_216));
  NOR20 g3501(.A (n_226), .B (n_574), .Q (n_215));
  NOR20 g3500(.A (n_226), .B (n_651), .Q (n_214));
  NOR20 g3547(.A (O2_point_add[1]), .B (n_627), .Q (n_232));
  NOR20 g3519(.A (n_226), .B (n_641), .Q (n_213));
  NOR20 g3498(.A (n_226), .B (n_608), .Q (n_212));
  NOR20 g3447(.A (n_226), .B (n_643), .Q (n_211));
  NOR20 g3448(.A (n_226), .B (n_650), .Q (n_210));
  NOR20 g3496(.A (n_226), .B (n_609), .Q (n_209));
  NAND20 g3542(.A (n_127), .B (n_125), .Q (n_315));
  NOR20 g3494(.A (n_226), .B (n_580), .Q (n_208));
  NOR20 g3532(.A (n_226), .B (n_619), .Q (n_207));
  NOR20 g3533(.A (n_226), .B (n_628), .Q (n_206));
  NOR20 g3529(.A (n_226), .B (n_645), .Q (n_205));
  NOR20 g3530(.A (n_226), .B (n_631), .Q (n_204));
  NOR20 g3528(.A (n_226), .B (n_620), .Q (n_203));
  NOR20 g3526(.A (n_226), .B (n_663), .Q (n_202));
  NOR20 g3442(.A (n_226), .B (n_560), .Q (n_201));
  NOR20 g3520(.A (n_226), .B (n_562), .Q (n_200));
  NOR20 g3443(.A (n_226), .B (n_578), .Q (n_199));
  DFC3 O1_winc_reg(.RN (n_reset), .C (m_clk), .D (n_198), .Q
       (UNCONNECTED139), .QN (O1_winc));
  NOR20 g3429(.A (n_226), .B (n_629), .Q (n_197));
  NOR20 g3430(.A (n_226), .B (n_646), .Q (n_196));
  NOR20 g3522(.A (n_226), .B (n_639), .Q (n_195));
  NOR20 g3431(.A (n_226), .B (n_613), .Q (n_194));
  NOR20 g3432(.A (n_226), .B (n_555), .Q (n_193));
  NOR20 g3433(.A (n_226), .B (n_626), .Q (n_192));
  NOR20 g3434(.A (n_226), .B (n_635), .Q (n_191));
  NOR20 g3435(.A (n_226), .B (n_610), .Q (n_190));
  NOR20 g3436(.A (n_226), .B (n_585), .Q (n_189));
  NOR20 g3437(.A (n_226), .B (n_591), .Q (n_188));
  NOR20 g3523(.A (n_226), .B (n_653), .Q (n_187));
  NOR20 g3439(.A (n_226), .B (n_648), .Q (n_186));
  NOR20 g3466(.A (n_226), .B (n_644), .Q (n_185));
  NOR20 g3441(.A (n_226), .B (n_588), .Q (n_184));
  NOR20 g3444(.A (n_226), .B (n_565), .Q (n_183));
  NOR20 g3445(.A (n_226), .B (n_602), .Q (n_182));
  NOR20 g3446(.A (n_226), .B (n_597), .Q (n_181));
  NOR20 g3468(.A (n_226), .B (n_558), .Q (n_180));
  NOR20 g3440(.A (n_226), .B (n_587), .Q (n_179));
  NOR20 g3451(.A (n_226), .B (n_665), .Q (n_178));
  NOR20 g3452(.A (n_226), .B (n_579), .Q (n_177));
  NOR20 g3454(.A (n_226), .B (n_634), .Q (n_176));
  NOR20 g3455(.A (n_226), .B (n_636), .Q (n_175));
  NOR20 g3456(.A (n_226), .B (n_595), .Q (n_174));
  NOR20 g3438(.A (n_226), .B (n_569), .Q (n_173));
  NOR20 g3459(.A (n_226), .B (n_594), .Q (n_172));
  NOR20 g3462(.A (n_226), .B (n_564), .Q (n_171));
  NOR20 g3463(.A (n_226), .B (n_554), .Q (n_170));
  NOR20 g3521(.A (n_226), .B (n_638), .Q (n_169));
  NOR20 g3465(.A (n_226), .B (n_633), .Q (n_168));
  NOR20 g3467(.A (n_226), .B (n_567), .Q (n_167));
  NOR20 g3469(.A (n_226), .B (n_655), .Q (n_166));
  NOR20 g3470(.A (n_226), .B (n_556), .Q (n_165));
  NOR20 g3471(.A (n_226), .B (n_664), .Q (n_164));
  NOR20 g3472(.A (n_226), .B (n_624), .Q (n_163));
  NOR20 g3473(.A (n_226), .B (n_568), .Q (n_162));
  NOR20 g3474(.A (n_226), .B (n_607), .Q (n_161));
  NOR20 g3475(.A (n_226), .B (n_616), .Q (n_160));
  NOR20 g3476(.A (n_226), .B (n_571), .Q (n_159));
  NOR20 g3477(.A (n_226), .B (n_625), .Q (n_158));
  NOR20 g3478(.A (n_226), .B (n_573), .Q (n_157));
  NOR20 g3479(.A (n_226), .B (n_570), .Q (n_156));
  NOR20 g3480(.A (n_226), .B (n_561), .Q (n_155));
  NOR20 g3481(.A (n_226), .B (n_581), .Q (n_154));
  NOR20 g3482(.A (n_226), .B (n_563), .Q (n_153));
  NOR20 g3483(.A (n_226), .B (n_652), .Q (n_152));
  NOR20 g3484(.A (n_226), .B (n_596), .Q (n_151));
  NOR20 g3485(.A (n_226), .B (n_611), .Q (n_150));
  NOR20 g3486(.A (n_226), .B (n_632), .Q (n_149));
  NOR20 g3487(.A (n_226), .B (n_659), .Q (n_148));
  NOR20 g3488(.A (n_226), .B (n_618), .Q (n_147));
  NOR20 g3489(.A (n_226), .B (n_572), .Q (n_146));
  NOR20 g3490(.A (n_226), .B (n_656), .Q (n_145));
  NOR20 g3491(.A (n_226), .B (n_589), .Q (n_144));
  NOR20 g3492(.A (n_226), .B (n_592), .Q (n_143));
  NOR20 g3493(.A (n_226), .B (n_600), .Q (n_142));
  NOR20 g3495(.A (n_226), .B (n_605), .Q (n_141));
  NOR20 g3497(.A (n_226), .B (n_621), .Q (n_140));
  NOR20 g3499(.A (n_226), .B (n_660), .Q (n_139));
  NOR20 g3503(.A (n_226), .B (n_598), .Q (n_138));
  NOR20 g3507(.A (n_226), .B (n_575), .Q (n_137));
  NOR20 g3509(.A (n_226), .B (n_637), .Q (n_136));
  NOR20 g3515(.A (n_226), .B (n_583), .Q (n_135));
  NOR20 g3517(.A (n_226), .B (n_617), .Q (n_134));
  NOR20 g3464(.A (n_226), .B (n_586), .Q (n_133));
  NOR20 g3516(.A (n_226), .B (n_654), .Q (n_132));
  NOR20 g3525(.A (n_226), .B (n_662), .Q (n_131));
  NOR20 g3531(.A (n_226), .B (n_557), .Q (n_130));
  NOR21 g3535(.A (A_counter[1]), .B (n_658), .Q (n_233));
  NOR21 g3536(.A (n_198), .B (O1_r_empty), .Q (n_129));
  INV0 g3538(.A (n_317), .Q (n_128));
  NAND20 g3543(.A (n_127), .B (O1_w_pointer[1]), .Q (n_314));
  NOR20 g3545(.A (O2_point[1]), .B (n_124), .Q (n_300));
  NOR20 g3508(.A (n_226), .B (n_640), .Q (n_126));
  NAND20 g3548(.A (O1_w_pointer[0]), .B (n_125), .Q (n_312));
  NAND20 g3550(.A (n_124), .B (O2_point[1]), .Q (n_398));
  NOR20 g3461(.A (n_226), .B (n_582), .Q (n_123));
  NOR20 g3514(.A (n_226), .B (n_647), .Q (n_122));
  NOR20 g3513(.A (n_226), .B (n_559), .Q (n_121));
  NOR20 g3512(.A (n_226), .B (n_649), .Q (n_120));
  NOR20 g3524(.A (n_226), .B (n_630), .Q (n_119));
  NOR20 g3510(.A (n_226), .B (n_614), .Q (n_118));
  NOR20 g3511(.A (n_226), .B (n_566), .Q (n_117));
  NOR20 g3518(.A (n_226), .B (n_601), .Q (n_116));
  NAND20 g3537(.A (O2_point[1]), .B (O2_point[0]), .Q (n_345));
  NOR20 g3541(.A (O2_point[0]), .B (O2_point[1]), .Q (n_388));
  NAND20 g3539(.A (O1_w_pointer[0]), .B (O1_w_pointer[1]), .Q (n_317));
  NAND20 g3540(.A (O2_point_add[2]), .B (O2_point_add[1]), .Q (n_257));
  DFC3 O1_read_en_reg(.RN (n_reset), .C (read_req), .D (O1_w_full), .Q
       (O1_read_en), .QN (n_552));
  CLKIN2 g3596(.A (A_counter[3]), .Q (n_75));
  CLKIN6 g3633(.A (n_reset), .Q (n_226));
  NAND22 g2(.A (O1_read_en), .B (O1_r_empty), .Q (n_534));
  NAND22 g3954(.A (n_287), .B (n_244), .Q (n_535));
  NOR21 g3955(.A (n_552), .B (n_198), .Q (n_536));
endmodule

